# Copyright (c) 2011 Tencent Inc.
# All rights reserved.
#
# Author: Huan Yu <huanyu@tencent.com>
#         Feng Chen <phongchen@tencent.com>
#         Yi Wang <yiwang@tencent.com>
#         Chong Peng <michaelpeng@tencent.com>
# Date:   October 20, 2011


"""
This is the build rules genearator module which invokes all the builder
objects to generate build rules.
"""


import os
import sys
import textwrap

from blade import rule_registry
from blade import util
from blade.ninja_rule import NinjaRule
from blade.rule_context import RuleContext


class _NinjaFileHeaderGenerator:
    """Generate global declarations and definitions for build script.

    Specifically it may consist of global functions and variables,
    environment setup, predefined rules and builders, utilities
    for the underlying build system.
    """
    # pylint: disable=too-many-public-methods
    def __init__(self, command, options, build_dir, blade_path, build_toolchain, blade):
        self.command = command
        self.options = options
        self.build_dir = build_dir
        self.blade_path = blade_path
        self.build_toolchain = build_toolchain
        self.build_accelerator = blade.build_accelerator
        self.blade = blade

        self.rules_buf = []
        self.__all_rule_names = set()


    def _add_line(self, rule):
        """Append one rule to buffer."""
        self.rules_buf.append('%s\n' % rule)

    def get_all_rule_names(self):
        return list(self.__all_rule_names)

    def _record_rule_name(self, name):
        """Record an emitted rule name (used by RuleContext.emit_rule)."""
        self.__all_rule_names.add(name)

    def generate_rule(self, name, command, description=None,
                      depfile=None, generator=False, pool=None,
                      restat=False, rspfile=None,
                      rspfile_content=None, deps=None):
        rule = NinjaRule(
            name=name, command=command, description=description,
            depfile=depfile, generator=generator, pool=pool, restat=restat,
            rspfile=rspfile, rspfile_content=rspfile_content, deps=deps)
        self.__all_rule_names.add(rule.name)
        for line in rule.emit():
            self._add_line(line)

    def generate_file_header(self):
        self._add_line(textwrap.dedent('''\
                # build.ninja generated by blade
                ninja_required_version = 1.7
                builddir = %s
                ''') % self.build_dir)
        # No more than 1 heavy target at a time
        self._add_line(textwrap.dedent('''\
                pool heavy_pool
                  depth = 1
                '''))

    def generate_common_rules(self):
        if os.name == 'nt':
            copy_cmd = 'cmd /c copy /y ${in} ${out} > nul'
        else:
            # -L dereferences symbolic-link sources so a prebuilt
            # `libfoo.so -> libfoo.so.2.2` resolves to a real file in the
            # build dir rather than a dangling symlink. Both GNU and BSD
            # cp default to following symlinks in single-file copy mode,
            # but issue #730 reported a build-1.1.2-era environment that
            # behaved otherwise; -L makes the intent explicit and
            # platform-independent.
            copy_cmd = 'cp -fL ${in} ${out}'
        self.generate_rule(name='copy',
                           command=copy_cmd,
                           description='COPY ${in} ${out}')


    def generate_version_rules(self):
        cc = self.build_toolchain.get_cc()
        cc_version = self.build_toolchain.get_cc_version()

        revision, url = util.load_scm(self.build_dir)
        args = '--scm=${out} --revision=${revision} --url=${url} --profile=${profile} --compiler="${compiler}"'
        self.generate_rule(name='scm',
                           command=self._builtin_command('scm', args),
                           description='SCM ${out}')
        scm = os.path.join(self.build_dir, 'scm.cc')
        self._add_line(textwrap.dedent('''\
                build %s: scm
                  revision = %s
                  url = %s
                  profile = %s
                  compiler = %s
                ''') % (scm, revision, url, self.options.profile, f'{cc} {cc_version}'))
        scm_obj = self.build_toolchain.object_file_of(scm)
        # The `cxx` rule routes through the inclusion wrapper, which needs an
        # `inclusion_stack` path (custom ninja vars cannot default at rule level).
        # scm.cc is not inclusion-checked, so point it at a throwaway file.
        self._add_line(textwrap.dedent('''\
                build %s: cxx %s
                  cppflags = -w -O2
                  cxx_warnings =
                  inclusion_stack = %s
                ''') % (scm_obj, scm, scm_obj + '.incstk'))


    def _builtin_command(self, builder, args=''):
        python = os.environ.get('BLADE_PYTHON_INTERPRETER') or sys.executable
        if os.name == 'nt':
            # On Windows, PYTHONPATH uses ';' and cmd.exe must be explicit
            python_cmd = f'set PYTHONPATH={self.blade_path};%PYTHONPATH% && {python} -m blade.builtin_tools {builder}'
            cmd = ['cmd /c', python_cmd]
        else:
            cmd = ['PYTHONPATH=%s:$$PYTHONPATH' % self.blade_path]
            cmd.append(f'{python} -m blade.builtin_tools {builder}')
        if args:
            cmd.append(args)
        else:
            cmd.append('${out} ${in}')
        return ' '.join(cmd)

    def generate(self):
        """Generate ninja rules by iterating the registered rule providers.

        The file header (and pool) is not a rule, so it is emitted first
        directly. Rule groups are contributed via the rule registry (see
        ``rule_registry`` and ``_register_builtin_rule_providers`` below) and
        emitted in a deterministic order, decoupling this method from the set
        of languages.
        """
        self.generate_file_header()
        ctx = RuleContext(self)
        for provider in rule_registry.rule_providers():
            provider(ctx)
        return self.rules_buf


def _register_builtin_rule_providers():
    """Register the built-in rule groups with the rule registry.

    M1 bridge: each provider delegates to the corresponding
    ``_NinjaFileHeaderGenerator.generate_*_rules`` method (unchanged) via
    ``ctx.generator``, preserving byte-identical output. The explicit order
    keys reproduce the original ``generate()`` sequence. Later milestones
    rewrite these providers to construct ``NinjaRule`` values directly against
    ``ctx`` and move them next to their target modules.
    """
    reg = rule_registry.register_rule_provider
    reg(lambda ctx: ctx.generator.generate_common_rules(),
        order=rule_registry.ORDER_COMMON, name='common')
    reg(lambda ctx: ctx.generator.generate_version_rules(),
        order=rule_registry.ORDER_VERSION, name='version')
    # 'cc' (cc_targets), 'cuda' (cu_targets), 'java_scala', 'proto', 'resource',
    # 'thrift', 'go', 'lex_yacc', 'python', 'shell', 'package' are registered by
    # their target modules -- M2. 'common' and 'version' are project-level
    # (no home module) and stay here.


_register_builtin_rule_providers()


class NinjaFileGenerator:
    """Generate ninja rules to build.ninja."""

    def __init__(self, ninja_path, blade_path, blade):
        self.script_path = ninja_path
        self.blade_path = blade_path
        self.blade = blade
        self.build_toolchain = blade.get_build_toolchain()
        self.build_dir = blade.get_build_dir()
        self.__all_rule_names = []

    def get_all_rule_names(self):
        return self.__all_rule_names

    def generate_build_code(self):
        """Generate ninja code to build.ninja."""
        ninja_script_header_generator = _NinjaFileHeaderGenerator(
            self.blade.get_command(),
            self.blade.get_options(),
            self.build_dir,
            self.blade_path,
            self.build_toolchain,
            self.blade)
        code = ninja_script_header_generator.generate()
        code += self.blade.generate_targets_build_code()
        # cc_library targets have accumulated their undefined-symbol check
        # specs on the BuildManager; emit the single ``ccchkund_batch``
        # ninja rule now that all targets are generated and the spec list
        # is complete.
        code += self._emit_cc_check_undefined_batch()
        self.__all_rule_names = ninja_script_header_generator.get_all_rule_names()
        return code

    def _emit_cc_check_undefined_batch(self):
        """Emit the project-wide ``ccchkund_batch`` ninja rule + write the
        manifest JSON for it. Returns the ninja-file fragment to append.

        Two regen modes:
          * **Fresh** -- at least one cc_library went through ``generate()``
            this run and registered a spec. Write the manifest from the
            current spec list (write-if-changed), then emit the directive.
          * **Cached** -- every cc_library's sub-ninja was reused, so no
            specs were registered this run, but a manifest from the
            previous run exists on disk. Re-emit the directive against
            that manifest so the main ``build.ninja`` regen stays
            idempotent.

        Returns an empty list when there is genuinely nothing to check
        (no registered specs *and* no manifest from a prior run -- MSVC
        toolchain, or every lib opted out via ``check_undefined = False``
        / ``allow_undefined = True``).
        """
        import json  # pylint: disable=import-outside-toplevel
        manifest_dir = os.path.join(self.build_dir, '.cache')
        manifest_path = os.path.join(manifest_dir, 'cc_check_undefined.manifest.json')
        stamp_path = os.path.join(manifest_dir, 'cc_check_undefined.stamp')
        specs = self.blade.cc_check_undefined_specs()
        if specs:
            os.makedirs(manifest_dir, exist_ok=True)
            # Stable ordering so the manifest is byte-stable across
            # rebuilds (deterministic ninja inputs => no spurious re-runs).
            specs = sorted(specs, key=lambda s: s['target_label'])
            new_payload = json.dumps(specs, indent=2, sort_keys=True)
            old_payload = None
            if os.path.exists(manifest_path):
                with open(manifest_path, encoding='utf-8') as f:
                    old_payload = f.read()
            if old_payload != new_payload:
                with open(manifest_path, 'w', encoding='utf-8') as f:
                    f.write(new_payload)
        elif os.path.exists(manifest_path):
            with open(manifest_path, encoding='utf-8') as f:
                specs = json.load(f)
        else:
            return []
        # Gather every distinct .syms / .allow path so ninja can re-run
        # the batch precisely when any input changes.
        syms = set()
        allow_files = set()
        for spec in specs:
            syms.add(spec['target_syms'])
            syms.update(spec['dep_syms'])
            syms.update(spec['sys_caches'])
            allow_files.add(spec['allow_file'])
        # Emit a single ninja `build` directive. inputs[0] = manifest;
        # the .syms files are the data inputs (any change triggers a
        # re-run); the .allow files are implicit deps (regex allowlists).
        inputs = ' '.join([manifest_path] + sorted(syms))
        implicit = ' '.join(sorted(allow_files))
        # Don't emit a `default` declaration -- ninja already builds every
        # "leaf" target when no default is declared, so the stamp gets
        # picked up. Adding a default would *override* ninja's leaf
        # auto-discovery and limit `ninja` (no args) to just this one
        # target, breaking the "blade build //some:target" path that
        # relies on every produced output being reachable.
        return [
            '\n# Project-wide cc_check_undefined batch (see builtin_tools.py)\n',
            'build %s: ccchkund_batch %s | %s\n' % (stamp_path, inputs, implicit),
        ]

    def generate_build_script(self):
        """Generate build script for underlying build system."""
        code = self.generate_build_code()
        with open(self.script_path, 'w', encoding='utf-8') as script:
            script.writelines(code)
