# Copyright (c) 2011 Tencent Inc.
# All rights reserved.
#
# Author: Huan Yu <huanyu@tencent.com>
#         Feng Chen <phongchen@tencent.com>
#         Yi Wang <yiwang@tencent.com>
#         Chong Peng <michaelpeng@tencent.com>
# Date:   October 20, 2011


"""
This is the build rules genearator module which invokes all the builder
objects to generate build rules.
"""


import glob
import os
import shutil
import sys
import textwrap

from blade import config
from blade import console
from blade import util


# To verify whether a header is included without depending on the library it
# belongs to, we use gcc's `-H` option to print the inclusion stack
# (https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html). That goes to
# stderr, mixed with diagnostics, so this awk program separates them: lines of
# the inclusion stack (leading dots) go to stdout (-> the `.incstk` file),
# everything else is forwarded to stderr.
#
# It lives in a generated wrapper script (see `_inclusion_wrapper_script`)
# instead of inline in the ninja command, so a failed compile no longer echoes
# the whole program. In a plain file it also needs no `$$`/`%%` escaping.
#
# `多个防止重包含可能对其有用：` is the Chinese of `Multiple include guards...`;
# after that marker the trailing file list is noise, but later lines (e.g. a
# cuda error) may still matter, so we don't `exit` early.
_INCLUSION_SPLITTER_AWK = r'''
/Multiple include guards may be useful for:|多个防止重包含可能对其有用：/ { stop = 1 }
/^\.+ [^\/]/ && !end { started = 1; print $0 }       # an inclusion-stack line
!/^\.+ / && started { end = 1 }                      # first line after the stack
!/^\.+ / && (!stop || (!/Multiple include guards may be useful for:|多个防止重包含可能对其有用：/ && !/^[a-zA-Z0-9\.\/\+_-]+$/)) { print $0 > "/dev/stderr" }
'''

# POSIX-sh wrapper that runs a compile/preprocess command and then splits its
# `-H` output via _INCLUSION_SPLITTER_AWK. Invoked as:
#   sh <this> <mode> <inclusion_file> <command...>
#     mode=compile : run once (cc/cxx/cuda objects; <command> already carries -H)
#     mode=hdrs    : try with -fdirectives-only, retry without it on failure
# Ninja runs each command via `/bin/sh -c` and exec-replaces itself for a single
# command, so this adds no extra process over the old inline pipeline.
_INCLUSION_WRAPPER_SCRIPT = '''\
#!/bin/sh
# Generated by blade; do not edit. See backend.py (_inclusion_wrapper_script).
mode=$1
out=$2
shift 2
err=$out.err
export LC_ALL=C
if [ "$mode" = hdrs ]; then
    # -fdirectives-only speeds up preprocessing but breaks on some edge cases
    # (e.g. __COUNTER__ tricks); retry without it, discarding the first
    # attempt's diagnostics.
    "$@" -fdirectives-only 2> "$err" || "$@" 2> "$err"
else
    "$@" 2> "$err"
fi
ec=$?
awk '%s' "$err" > "$out.new"
# write-if-changed: keep $out's mtime when the inclusion stack is unchanged, so
# ninja's `restat` can prune the inclusion check on recompiles that don't alter
# the set of included headers. See issue #1161.
if [ -f "$out" ] && cmp -s "$out.new" "$out"; then
    rm -f "$out.new"
else
    mv "$out.new" "$out"
fi
rm -f "$err"
exit $ec
''' % _INCLUSION_SPLITTER_AWK

# MSVC tee-wrapper: runs a compile command (cl.exe or nvcc with /showIncludes),
# tees stderr to both the real stderr (for Ninja's deps=msvc) and an incstk
# file (for inclusion checking). Invoked as:
#   python cc_wrapper.py ${inclusion_stack} -- <compile_command...>
#
# Unlike the POSIX shell wrapper, stderr is passed through unfiltered — Ninja
# needs the raw /showIncludes lines.  Bare source/header filenames that cl.exe
# echoes (e.g. "hello.h" without a path) are stripped from the incstk file
# only, matching what Ninja's CLParser::FilterInputFilename does for .c/.cpp
# etc., extended to header extensions.
_MSVC_TEE_WRAPPER_PY = r'''
import os, re, subprocess, sys

outfile = sys.argv[1]
# sys.argv[2] is "--"
cmd = sys.argv[3:]

_NOTE_PREFIX = 'Note: including file:'
_cwd = os.getcwd()

# Compilers echo the basename of the file they process.  Ninja's
# CLParser::FilterInputFilename strips it for source files (.c/.cc/.cxx/.cpp/
# .c++) but NOT for headers, so the cxxhdrs rule (/P on a .h) leaks a bare
# "foo.h" onto the build console; nvcc additionally echoes its source (.cu)
# and a zoo of intermediate temp names (tmpxft_*.cpp1.ii, *.cudafe1.cpp, ...).
# Enumerating extensions is hopeless, so match any lone filename token: no
# whitespace, no path separator, at least one dot, only filename-safe chars.
# Real diagnostics always carry spaces/colons/parens and never match.
_BARE_FILENAME_RE = re.compile(r'^[\w.+\-]+\.[\w.+\-]+$')

def _in_workspace(hdr):
    try:
        return os.path.commonpath([_cwd, hdr]) == _cwd
    except ValueError:  # different drive -> outside the workspace
        return False

# Merge stdout+stderr into one pipe (like Ninja).  Reading only stderr risks
# a pipe deadlock: if cl.exe writes enough to stdout (even with /nologo a
# leftover copyright banner fills the 4 KiB buffer), the process blocks and
# never drains its stderr output through the unread stdout pipe.
p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                     universal_newlines=True, encoding='utf-8', errors='replace')
with open(outfile + '.new', 'w', newline='', encoding='utf-8') as f:
    for line in p.stdout:
        if line.startswith(_NOTE_PREFIX):
            # Record only workspace headers in the incstk (smaller file; the
            # inclusion checker discards absolute/system paths anyway), but
            # forward every include line to ninja's deps=msvc parser below.
            hdr = line[len(_NOTE_PREFIX):].lstrip().rstrip('\r\n')
            if not os.path.isabs(hdr) or _in_workspace(hdr):
                f.write(line)
        elif _BARE_FILENAME_RE.match(line.strip()):
            continue  # echoed source/temp filename -- console noise, drop it
        sys.stderr.write(line)
        sys.stderr.flush()

ec = p.wait()

# Write-if-changed: keep mtime when the stack is unchanged, so ninja's
# restat can prune the inclusion check. See issue #1161.
try:
    with open(outfile + '.new', 'rb') as nf:
        new = nf.read()
    try:
        with open(outfile, 'rb') as of:
            old = of.read()
    except FileNotFoundError:
        old = None
    if new != old:
        os.replace(outfile + '.new', outfile)
    else:
        os.unlink(outfile + '.new')
except OSError:
    pass

sys.exit(ec)
'''


def _incs_list_to_string(incs):
    """Convert incs list to string.

    Example:
        ['thirdparty', 'include'] -> "-I thirdparty -I include"
    """
    return ' '.join(['-I ' + path for path in incs])


def protoc_import_path_option(incs):
    return ' '.join(['-I=%s' % inc for inc in incs])


class _NinjaFileHeaderGenerator:
    """Generate global declarations and definitions for build script.

    Specifically it may consist of global functions and variables,
    environment setup, predefined rules and builders, utilities
    for the underlying build system.
    """
    # pylint: disable=too-many-public-methods
    def __init__(self, command, options, build_dir, blade_path, build_toolchain, blade):
        self.command = command
        self.options = options
        self.build_dir = build_dir
        self.blade_path = blade_path
        self.build_toolchain = build_toolchain
        self.build_accelerator = blade.build_accelerator
        self.blade = blade

        self.rules_buf = []
        self.__all_rule_names = set()
        self.__inclusion_wrapper_path = None
        self.__msvc_wrapper_py_path = None

    def _inclusion_wrapper_script(self):
        """Path to the cc inclusion-stack splitter wrapper, written on first use.

        See `_INCLUSION_WRAPPER_SCRIPT`. Written into the build dir at ninja
        generation time; ninja runs from the workspace root, so the build-dir
        relative path resolves. The script is not a dependency of any edge, so
        rewriting it never triggers a rebuild.
        """
        if self.__inclusion_wrapper_path is None:
            path = os.path.join(self.build_dir, 'cc_wrapper.sh')
            util.write_if_changed(path, _INCLUSION_WRAPPER_SCRIPT)
            self.__inclusion_wrapper_path = path
        return self.__inclusion_wrapper_path

    def _msvc_tee_wrapper_py(self):
        """Path to the MSVC Python stderr-tee wrapper, written on first use."""
        if self.__msvc_wrapper_py_path is None:
            path = os.path.join(self.build_dir, 'cc_wrapper.py')
            util.write_if_changed(path, _MSVC_TEE_WRAPPER_PY)
            self.__msvc_wrapper_py_path = path
        return self.__msvc_wrapper_py_path

    def _add_line(self, rule):
        """Append one rule to buffer."""
        self.rules_buf.append('%s\n' % rule)

    def get_all_rule_names(self):
        return list(self.__all_rule_names)

    def generate_rule(self, name, command, description=None,
                      depfile=None, generator=False, pool=None,
                      restat=False, rspfile=None,
                      rspfile_content=None, deps=None):
        self.__all_rule_names.add(name)
        self._add_line('rule %s' % name)
        self._add_line('  command = %s' % command)
        if description:
            self._add_line('  description = %s' % console.colored(description, 'dimpurple'))
        if depfile:
            self._add_line('  depfile = %s' % depfile)
        if generator:
            self._add_line('  generator = 1')
        if pool:
            self._add_line('  pool = %s' % pool)
        if restat:
            self._add_line('  restat = 1')
        if rspfile:
            self._add_line('  rspfile = %s' % rspfile)
        if rspfile_content:
            self._add_line('  rspfile_content = %s' % rspfile_content)
        if deps:
            self._add_line('  deps = %s' % deps)
        self._add_line('')  # An empty line to improve readability

    def generate_file_header(self):
        self._add_line(textwrap.dedent('''\
                # build.ninja generated by blade
                ninja_required_version = 1.7
                builddir = %s
                ''') % self.build_dir)
        # No more than 1 heavy target at a time
        self._add_line(textwrap.dedent('''\
                pool heavy_pool
                  depth = 1
                '''))

    def generate_common_rules(self):
        if os.name == 'nt':
            copy_cmd = 'cmd /c copy /y ${in} ${out} > nul'
        else:
            copy_cmd = 'cp -f ${in} ${out}'
        self.generate_rule(name='copy',
                           command=copy_cmd,
                           description='COPY ${in} ${out}')

    def _get_intrinsic_cc_flags(self):
        """Get the common c/c++ flags."""
        global_config = config.get_section('global_config')
        cc_config = config.get_section('cc_config')

        cppflags = []
        linkflags = []
        if self.options.m:
            cppflags = ['-m%s' % self.options.m]
            linkflags = ['-m%s' % self.options.m]
        # Add -fno-omit-frame-pointer to optimize mode for easy debugging.
        cppflags += ['-pipe', '-fno-omit-frame-pointer']

        if cc_config["fission"]:
            cppflags += ['-gsplit-dwarf']
            linkflags += ['-Wl,--gdb-index']

        # Debugging information setting
        debug_info_level = global_config['debug_info_level']
        debug_info_options = cc_config['debug_info_levels'][debug_info_level]
        cppflags += debug_info_options

        # Option debugging flags
        if self.options.profile == 'debug':
            cppflags.append('-fstack-protector')
        elif self.options.profile == 'release':
            cppflags.append('-DNDEBUG')

        cppflags += [
            '-D_FILE_OFFSET_BITS=64',
            '-D__STDC_CONSTANT_MACROS',
            '-D__STDC_FORMAT_MACROS',
            '-D__STDC_LIMIT_MACROS',
        ]

        if getattr(self.options, 'gprof', False):
            cppflags.append('-pg')
            linkflags.append('-pg')

        if getattr(self.options, 'coverage', False):
            cppflags.append('--coverage')
            linkflags.append('--coverage')

        if hasattr(self.options, 'profile-generate') and getattr(self.options, 'profile-generate') is not None:
            pgo_gen_dir = getattr(self.options, 'profile-generate')
            if not pgo_gen_dir:
                cppflags.append('-fprofile-generate')
                linkflags.append('-fprofile-generate')
            else:
                cppflags.append('-fprofile-generate=' + pgo_gen_dir)
                linkflags.append('-fprofile-generate=' + pgo_gen_dir)
            cppflags.append('-DPROFILE_GUIDED_OPTIMIZATION')

        if hasattr(self.options, 'profile-use') and getattr(self.options, 'profile-use') is not None:
            pgo_use_dir = getattr(self.options, 'profile-use')
            if not pgo_use_dir:
                cppflags.append('-fprofile-use')
            else:
                cppflags.append('-fprofile-use=' + pgo_use_dir)
            cppflags.append('-fprofile-correction')
            cppflags.append('-Wno-error=coverage-mismatch')
            cppflags.append('-DPROFILE_GUIDED_OPTIMIZATION')

        cppflags = self.build_toolchain.filter_cc_flags(cppflags)
        return cppflags, linkflags

    def _get_warning_flags(self):
        """Get the warning flags."""
        cc_config = config.get_section('cc_config')
        cuda_config = config.get_section('cuda_config')
        cppflags = cc_config['warnings']
        cxxflags = cc_config['cxx_warnings']
        cflags = cc_config['c_warnings']
        cuflags = cuda_config['cu_warnings']

        filtered_cppflags = self.build_toolchain.filter_cc_flags(cppflags)
        filtered_cxxflags = self.build_toolchain.filter_cc_flags(cxxflags, 'c++')
        filtered_cflags = self.build_toolchain.filter_cc_flags(cflags, 'c')

        return filtered_cppflags, filtered_cxxflags, filtered_cflags, cuflags

    def generate_cc_rules(self):
        if self.build_toolchain.cc_is('msvc'):
            self._generate_windows_cc_rules()
        else:
            cc, cxx, ld = self.build_accelerator.get_cc_commands()
            cppflags, linkflags = self._get_intrinsic_cc_flags()
            self._generate_cc_compile_rules(cc, cxx, cppflags)
            self._generate_cc_inclusion_check_rule()
            self._generate_cc_ar_rules()
            self._generate_cc_link_rules(ld, linkflags)
            self.generate_rule(name='strip',
                               command='strip --strip-unneeded -o ${out} ${in}',
                               description='STRIP ${out}')

    def _generate_windows_cc_rules(self):
        """Generate Windows/MSVC-specific CC rules."""
        cc, cxx, ld = self.build_accelerator.get_cc_commands()
        self._generate_windows_cc_vars()
        self._generate_windows_cc_compile_rules(cc, cxx)
        self._generate_cc_inclusion_check_rule()
        self._generate_windows_ar_rules()
        self._generate_windows_link_rules()

    def _generate_windows_cc_vars(self):
        """Generate Windows-specific CC variables."""
        windows_config = config.get_section('msvc_config')
        cc_config = config.get_section('cc_config')
        # Combine windows_config warnings with filtered cc_config warnings
        c_warnings = (windows_config['warnings'] +
                      self.build_toolchain.filter_cc_flags(cc_config['c_warnings'], 'c'))
        cxx_warnings = (windows_config['warnings'] +
                        self.build_toolchain.filter_cc_flags(cc_config['cxx_warnings'], 'c++'))
        self._add_line(textwrap.dedent('''\
                c_warnings = %s
                cxx_warnings = %s
                ''') % (' '.join(c_warnings), ' '.join(cxx_warnings)))

    def _generate_windows_cc_compile_rules(self, cc, cxx):
        """Generate Windows CC compilation rules."""
        windows_config = config.get_section('msvc_config')
        cc_config = config.get_section('cc_config')

        # Combine windows_config flags with filtered cc_config flags.
        # cc_config flags (from BLADE_ROOT) typically use GCC syntax and get
        # mapped/filtered by the toolchain (e.g. -std=c++17 → /std:c++17).
        filtered_cc_cflags = self.build_toolchain.filter_cc_flags(cc_config['cflags'], 'c')
        filtered_cc_cxxflags = self.build_toolchain.filter_cc_flags(cc_config['cxxflags'], 'c++')
        filtered_cc_cppflags = self.build_toolchain.filter_cc_flags(cc_config['cppflags'])

        cppflags = windows_config['cppflags'] + filtered_cc_cppflags
        cflags = windows_config['cflags'] + filtered_cc_cflags
        cxxflags = windows_config['cxxflags'] + filtered_cc_cxxflags
        # System includes (MSVC + Windows SDK) discovered by the toolchain,
        # then user-specified extra_incs, then build directory.
        system_includes = self.build_toolchain.get_system_include_paths()
        includes = system_includes + cc_config['extra_incs'] + ['.', self.build_dir]
        # MSVC accepts /I"path with spaces" (quoted, no space after /I).
        # Use a helper that quotes paths containing spaces.
        def _quote_if_needed(p):
            return f'/I"{p}"' if ' ' in p else f'/I{p}'
        include_flags = ' '.join([_quote_if_needed(inc) for inc in includes])

        optimize_flags = windows_config['optimize']
        optimize = ' '.join(optimize_flags.get(self.options.profile, []))

        # The Python stderr-tee wrapper captures /showIncludes output and tees
        # it to both stderr (for Ninja's deps=msvc) and the inclusion stack
        # file (for inclusion checking).
        py = sys.executable
        wrapper = self._msvc_tee_wrapper_py()
        template = '"%s" -B %s ${inclusion_stack} -- ' % (py, wrapper)

        cc_command = template + ('"%s" /nologo /c /showIncludes %s %s %s %s /Fo${out} ${c_warnings} ${in}' % (
            cc, optimize, ' '.join(cppflags), ' '.join(cflags), include_flags))
        self.generate_rule(name='cc',
                           command=cc_command,
                           description='CC ${in}',
                           deps='msvc',
                           restat=True)

        cxx_command = template + ('"%s" /nologo /c /showIncludes %s %s %s %s /Fo${out} ${cxx_warnings} ${in}' % (
            cxx, optimize, ' '.join(cppflags), ' '.join(cxxflags), include_flags))
        self.generate_rule(name='cxx',
                           command=cxx_command,
                           description='CXX ${in}',
                           deps='msvc',
                           restat=True)

        # For cxxhdrs: use /showIncludes to generate inclusion info for header
        # files. /P preprocesses (like GCC -E), /Tp forces C++ treatment of .h.
        # The Python wrapper captures /showIncludes to ${out} (.incstk file);
        # /Fi writes the preprocessed body to ${out}.pre.
        hdrs_template = '"%s" -B %s ${out} -- ' % (py, wrapper)
        hdrs_command = hdrs_template + ('"%s" /nologo /P /Tp${in} /showIncludes %s %s %s %s /Fi${out}.pre' % (
            cxx, optimize, ' '.join(cppflags), ' '.join(cxxflags), include_flags))
        self.generate_rule(name='cxxhdrs',
                           command=hdrs_command,
                           description='CXX HDRS ${in}',
                           deps='msvc',
                           restat=True)

    def _generate_windows_ar_rules(self):
        """Generate Windows static library rules."""
        cc_lib = config.get_section('cc_library_config')
        deterministic = cc_lib.get('deterministic', False)
        thin = cc_lib.get('thin', False)
        if thin:
            console.warning('cc_library_config.thin=True has no effect on MSVC (lib.exe '
                            'does not support thin archives)')
        ar = self.build_accelerator.get_ar_command()
        brepro = ' /Brepro' if deterministic else ''
        self.generate_rule(name='ar',
                           command=f'{ar} /nologo{brepro} /out:${{out}} ${{in}}',
                           description='LIB ${out}')

    def _generate_windows_link_rules(self):
        """Generate Windows linking rules."""
        _, _, ld = self.build_accelerator.get_cc_commands()
        windows_config = config.get_section('msvc_config')
        cc_config = config.get_section('cc_config')
        # Combine windows_config linkflags with filtered cc_config linkflags
        linkflags = (windows_config['linkflags'] +
                     self.build_toolchain.filter_cc_flags(cc_config['linkflags']))

        # System library paths (MSVC + Windows SDK) discovered by the toolchain
        lib_paths = self.build_toolchain.get_system_lib_paths()
        def _libpath_flag(p):
            if ' ' in p:
                return '/LIBPATH:"%s"' % p
            return '/LIBPATH:%s' % p
        libpath_flags = ' '.join([_libpath_flag(p) for p in lib_paths])

        self._add_line('linkflags = %s\n' % ' '.join(linkflags))

        self.generate_rule(name='link',
                           command=f'{ld} /nologo /out:${{out}} ${{linkflags}} {libpath_flags} ${{target_linkflags}} ${{extra_linkflags}} ${{in}}',
                           description='LINK EXE ${out}')

        # ${dllflags} carries the per-target `/DEF:<def> /IMPLIB:<implib>` for a
        # cc_library DLL (empty for other solink edges, e.g. cc_plugin). The
        # `.def` (auto-export, COMDAT-filtered) makes the DLL export its symbols
        # without source annotations; the import library is what dependents link.
        self.generate_rule(name='solink',
                           command=f'{ld} /nologo /DLL ${{dllflags}} /out:${{out}} ${{linkflags}} {libpath_flags} ${{target_linkflags}} ${{extra_linkflags}} ${{in}}',
                           description='LINK DLL ${out}')

        # Synthesize the auto-export `.def` from the object files (see the
        # `cc_windef` builtin tool). Windows-only; nothing emits this edge
        # elsewhere.
        self.generate_rule(name='cc_windef',
                           command=self._builtin_command('cc_windef'),
                           description='CC WINDEF ${out}')

    def _generate_cc_vars(self):
        warnings, cxx_warnings, c_warnings, cu_warnings = self._get_warning_flags()
        c_warnings += warnings
        cxx_warnings += warnings
        cu_warnings += ['-Xcompiler %s' % warning for warning in cxx_warnings]
        # optimize_flags is need for `always_optimize`
        optimize_flags = config.get_item('cc_config', 'optimize')
        optimize = '$optimize_flags' if self.options.profile == 'release' else ''
        self._add_line(textwrap.dedent('''\
                c_warnings = %s
                cxx_warnings = %s
                cu_warnings = %s
                optimize_flags = %s
                optimize = %s
                ''') % (' '.join(c_warnings), ' '.join(cxx_warnings),
                        ' '.join(cu_warnings),
                        ' '.join(optimize_flags), optimize))

    def _generate_cc_compile_rules(self, cc, cxx, cppflags):
        self._generate_cc_vars()

        cc_config = config.get_section('cc_config')
        cflags, cxxflags = cc_config['cflags'], cc_config['cxxflags']
        cppflags = cc_config['cppflags'] + cppflags
        includes = cc_config['extra_incs']
        includes = includes + ['.', self.build_dir]
        includes = ' '.join(['-I%s' % inc for inc in includes])

        template = self._cc_compile_command_wrapper_template('${inclusion_stack}')

        cc_command = ('%s -o ${out} -MMD -MF ${out}.d -c -fPIC %s %s ${optimize} '
                      '${c_warnings} ${cppflags} %s ${includes} ${in}') % (
                              cc, ' '.join(cflags), ' '.join(cppflags), includes)
        self.generate_rule(name='cc',
                           command=template % cc_command,
                           description='CC ${in}',
                           depfile='${out}.d',
                           deps='gcc',
                           # restat lets ninja prune the inclusion check when the
                           # per-source `${inclusion_stack}` (`<src>.incstk`) is
                           # unchanged (written write-if-changed). See issue #1161.
                           restat=True)

        cxx_command = ('%s -o ${out} -MMD -MF ${out}.d -c -fPIC %s %s ${optimize} '
                       '${cxx_warnings} ${cppflags} %s ${includes} ${in}') % (
                               cxx, ' '.join(cxxflags), ' '.join(cppflags), includes)
        self.generate_rule(name='cxx',
                           command=template % cxx_command,
                           description='CXX ${in}',
                           depfile='${out}.d',
                           deps='gcc',
                           restat=True)  # see the cc rule / issue #1161

        self.generate_rule(name='secretcc',
                           command=template % (cc_config['secretcc'] + ' ' + cxx_command),
                           description='SECRET CC ${in}',
                           depfile='${out}.d',
                           restat=True)  # see the cc rule / issue #1161

        self._generate_cc_hdrs_rule(cc, cxx, cppflags, cflags, cxxflags, includes)

    def _generate_cc_hdrs_rule(self, cc, cxx, cppflags, cflags, cxxflags, includes):
        """
        Generate inclusion stack file for header file to check dependency missing.
        See the '-H' in https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html for details.
        """
        self.generate_rule(name='cxxhdrs',
                           command=self._hdrs_command(cxx, cxxflags, cppflags, includes),
                           depfile='${out}.d', deps='gcc',
                           # restat lets ninja prune the inclusion check when the
                           # header's inclusion stack is unchanged (the wrapper
                           # writes ${out} write-if-changed). See issue #1161.
                           restat=True,
                           description='CXX HDRS ${in}')

    def _hdrs_command(self, cc, flags, cppflags, includes):
        """Build the bare preprocess command for a header's inclusion file.

        Run by the `hdrs`-mode wrapper script (see `_INCLUSION_WRAPPER_SCRIPT`);
        `${out}` is the inclusion (`.incstk`) file. `-H` is what the wrapper's
        awk extracts -- without it the inclusion stack is never emitted and the
        `.incstk` ends up empty, silently breaking checks for header-only
        libraries. See issue #1169.
        """
        cmd = ('%s -o /dev/null -E -MMD -MF ${out}.d %s %s -w ${cppflags} %s ${includes} ${in} -H' % (
            cc, ' '.join(flags), ' '.join(cppflags), includes))
        return 'sh %s hdrs ${out} %s' % (self._inclusion_wrapper_script(), cmd)

    def _generate_cc_inclusion_check_rule(self):
        self.generate_rule(name='ccincchk',
                           command=self._builtin_command('cc_inclusion_check'),
                           description='CC INCLUSION CHECK ${in}')

    def _generate_cc_ar_rules(self):
        cc_lib = config.get_section('cc_library_config')
        deterministic = cc_lib.get('deterministic', False)
        thin = cc_lib.get('thin', False)
        target_os = self.build_toolchain.target_os

        if target_os == 'darwin':
            if thin:
                console.error('cc_library_config.thin=True is not supported on macOS '
                              '(Apple ar does not support thin archives)')
            if deterministic:
                command = 'rm -f $out; libtool -static -no_warning_for_no_symbols -o $out $in'
            else:
                ar = self.build_accelerator.get_ar_command()
                command = f'rm -f $out; {ar} rcs $out $in'
        elif target_os == 'linux':
            ar = self.build_accelerator.get_ar_command()
            extra = ''
            if deterministic:
                extra += 'D'
            if thin:
                extra += 'T'
            command = f'rm -f $out; {ar} rcs{extra} $out $in'
        else:
            arflags = ''.join(cc_lib.get('arflags', ['rcs']))
            ar = self.build_accelerator.get_ar_command()
            command = f'rm -f $out; {ar} {arflags} $out $in'

        self.generate_rule(name='ar', command=command, description='AR ${out}')

    def _generate_cc_link_rules(self, ld, linkflags):
        self._add_line('linkflags = %s' % ' '.join(config.get_item('cc_config', 'linkflags')))
        self._add_line('intrinsic_linkflags = %s\n' % ' '.join(linkflags))

        link_jobs = config.get_item('link_config', 'link_jobs')
        if link_jobs:
            link_jobs = min(link_jobs, self.blade.build_jobs_num())
            console.info('Adjust parallel link jobs number to %s' % link_jobs)
            pool = 'link_pool'
            self._add_line(textwrap.dedent('''\
                    pool %s
                      depth = %s''') % (pool, link_jobs))
        else:
            pool = None

        # Linking might have a lot of object files exceeding maximal length of a bash command line.
        # Using response file can resolve this problem.
        # Refer to: https://ninja-build.org/manual.html
        link_args = '-o ${out} ${intrinsic_linkflags} ${linkflags} @${out}.rsp ${extra_linkflags}'
        self.generate_rule(name='link',
                           command=ld + ' ' + link_args,
                           rspfile='${out}.rsp',
                           rspfile_content='${target_linkflags} ${in}',
                           description='LINK BINARY ${out}',
                           pool=pool)
        self.generate_rule(name='solink',
                           command=ld + ' -shared ' + link_args,
                           rspfile='${out}.rsp',
                           rspfile_content='${target_linkflags} ${in}',
                           description='LINK SHARED ${out}',
                           pool=pool)
        self.generate_rule(name='dwp',
                           command=self._builtin_command('dwp', '${out} @${out}.rsp'),
                           rspfile='${out}.rsp',
                           rspfile_content='${in}',
                           description='DWP ${out}',
                           pool=pool)

    def _cc_compile_command_wrapper_template(self, inclusion_stack_file, cuda=False):
        """Calculate the cc compile command wrapper template.

        Returns a template whose single `%s` is the raw compile command. The
        wrapper script runs it, then splits gcc's `-H` inclusion stack into
        *inclusion_stack_file* (see `_inclusion_wrapper_script`).
        """
        # When dumping compdb, a raw compile command without wrapper should be generated,
        # otherwise some tools can't handle it.
        if self.command == 'dump' and self.options.dump_compdb:
            return '%s'

        print_header_option = '-Xcompiler -H' if cuda else '-H'
        return 'sh %s compile %s %%s %s' % (
            self._inclusion_wrapper_script(), inclusion_stack_file, print_header_option)

    def generate_proto_rules(self):
        proto_config = config.get_section('proto_library_config')
        protoc = proto_config['protoc']
        protoc_java = protoc
        if proto_config['protoc_java']:
            protoc_java = proto_config['protoc_java']
        protobuf_incs = protoc_import_path_option(proto_config['protobuf_incs'])
        protobuf_java_incs = protobuf_incs
        if proto_config['protobuf_java_incs']:
            protobuf_java_incs = protoc_import_path_option(proto_config['protobuf_java_incs'])
        self._add_line(textwrap.dedent('''\
                protocflags =
                protoccpppluginflags =
                protocjavapluginflags =
                protocpythonpluginflags =
                '''))
        self.generate_rule(name='proto',
                           command='%s --proto_path=. %s -I=${srcdir} '
                                   '--cpp_out=%s ${protocflags} ${protoccpppluginflags} ${in}' % (
                                       protoc, protobuf_incs, self.build_dir),
                           description='PROTOC CPP ${in}')
        self.generate_rule(name='protojava',
                           command='%s --proto_path=. %s --java_out=%s/${srcdir} '
                                   '${protocjavapluginflags} ${in}' % (
                                       protoc_java, protobuf_java_incs, self.build_dir),
                           description='PROTOC JAVA ${in}')
        self.generate_rule(name='protopython',
                           command='%s --proto_path=. %s -I=${srcdir} '
                                   '--python_out=%s ${protocpythonpluginflags} ${in}' % (
                                       protoc, protobuf_incs, self.build_dir),
                           description='PROTOC PYTHON ${in}')
        self.generate_rule(name='protodescriptors',
                           command='%s --proto_path=. %s -I=${srcdir} '
                                   '--descriptor_set_out=${out} --include_imports '
                                   '--include_source_info ${in}' % (
                                       protoc, protobuf_incs),
                           description='PROTODESCRIPTORS ${in}')
        protoc_go_plugin = proto_config['protoc_go_plugin']
        if protoc_go_plugin:
            go_home = config.get_item('go_config', 'go_home')
            go_module_enabled = config.get_item('go_config', 'go_module_enabled')
            go_module_relpath = config.get_item('go_config', 'go_module_relpath')
            if not go_home:
                console.fatal('"go_config.go_home" is not configured')
            if go_module_enabled and not go_module_relpath:
                outdir = proto_config['protobuf_go_path']
            else:
                outdir = os.path.join(go_home, 'src')
            subplugins = proto_config['protoc_go_subplugins']
            if subplugins:
                go_out = 'plugins={}:{}'.format('+'.join(subplugins), outdir)
            else:
                go_out = outdir
            self.generate_rule(name='protogo',
                               command='%s --proto_path=. %s -I=${srcdir} '
                                       '--plugin=protoc-gen-go=%s --go_out=%s ${in}' % (
                                           protoc, protobuf_incs, protoc_go_plugin, go_out),
                               description='PROTOCGOLANG ${in}')

    def generate_resource_rules(self):
        self.generate_rule(name='resource_index',
                           command=self._builtin_command('resource_index',
                                                         '${name} ${path} ${out} ${in}'),
                           description='RESOURCE INDEX ${out}')
        self.generate_rule(name='resource',
                           command=self._builtin_command('resource', '${out} ${in}'),
                           description='RESOURCE ${in}')

    def get_java_command(self, java_config, cmd):
        java_home = java_config['java_home']
        if java_home:
            return os.path.join(java_home, 'bin', cmd)
        return cmd

    def get_jacocoagent(self):
        jacoco_home = config.get_item('java_test_config', 'jacoco_home')
        if jacoco_home:
            return os.path.join(jacoco_home, 'lib', 'jacocoagent.jar')
        return ''

    def generate_javac_rules(self, java_config):
        javac = self.get_java_command(java_config, 'javac')
        jar = self.get_java_command(java_config, 'jar')
        cmd = [javac]
        version = java_config['version']
        source_version = java_config.get('source_version', version)
        target_version = java_config.get('target_version', version)
        if source_version:
            cmd.append('-source %s' % source_version)
        if target_version:
            cmd.append('-target %s' % target_version)
        cmd += [
            '-encoding ${source_encoding}',
            '-d ${classes_dir}',
            '-classpath ${classpath}',
            '${javacflags}',
            '${in}',
        ]
        self._add_line(textwrap.dedent('''\
                source_encoding = UTF-8
                classpath = .
                javacflags =
                '''))
        jarflags = 'cf' + config.get_item('java_config', 'jar_compression_level')
        if os.name == 'nt':
            javac_opts = ''
            if source_version:
                javac_opts += f'-source {source_version} '
            if target_version:
                javac_opts += f'-target {target_version} '
            command = self._builtin_command('javac_compile',
                                            f'${{classes_dir}} ${{out}} ${{source_encoding}} '
                                            f'${{classpath}} {javac_opts}${{javacflags}} -- ${{in}}')
        else:
            command = ('rm -fr ${classes_dir} && mkdir -p ${classes_dir} && '
                       '%s && sleep 0.01 && '
                       '%s %s ${out} -C ${classes_dir} .' % (
                           ' '.join(cmd), jar, jarflags))
        self.generate_rule(name='javac',
                           command=command,
                           description='JAVAC ${out}',
                           restat=True)

    def generate_java_resource_rules(self):
        self.generate_rule(name='javaresource',
                           command=self._builtin_command('java_resource'),
                           description='JAVA RESOURCE ${resources_dir}')

    def generate_java_jar_rules(self, java_config):
        jar = self.get_java_command(java_config, 'jar')
        level = config.get_item('java_config', 'jar_compression_level')
        args = f'{jar} --compression_level={level} ${{out}} ${{in}}'
        self.generate_rule(name='javajar',
                           command=self._builtin_command('java_jar', args),
                           description='JAVA JAR ${out}',
                           restat=True)

    def generate_java_test_rules(self):
        jacocoagent = self.get_jacocoagent()
        args = ('--script=${out} --main_class=${mainclass} --jacocoagent=%s '
                '--packages_under_test=${packages_under_test} ${in}') % jacocoagent
        self.generate_rule(name='javatest',
                           command=self._builtin_command('java_test', args),
                           description='JAVA TEST ${out}',
                           restat=True)

    def generate_fatjar_rules(self, java_config):
        conflict_severity = java_config.get('fat_jar_conflict_severity', 'warning')
        compression_level = java_config.get('fat_jar_compression_level')
        args = f'--output=${{out}} --compression_level={compression_level} --conflict_severity={conflict_severity} ${{in}}'
        self.generate_rule(name='fatjar',
                           command=self._builtin_command('java_fatjar', args),
                           description='FAT JAR ${out}')

    def generate_java_binary_rules(self):
        bootjar = config.get_item('java_binary_config', 'one_jar_boot_jar')
        args = '--onejar=${out} --bootjar=%s --main_class=${mainclass} ${in}' % bootjar
        self.generate_rule(name='onejar',
                           command=self._builtin_command('java_onejar', args),
                           description='ONE JAR ${out}')
        self.generate_rule(name='javabinary',
                           command=self._builtin_command('java_binary'),
                           description='JAVA BINARY ${out}')

    def generate_scalac_rule(self, java_config):
        scalac = 'scalac'
        scala_home = config.get_item('scala_config', 'scala_home')
        if scala_home:
            scalac = os.path.join(scala_home, 'bin', scalac)
        java = self.get_java_command(java_config, 'java')
        self._add_line(textwrap.dedent('''\
                scalacflags = -nowarn
                '''))
        cmd = [
            'JAVACMD=%s' % java,
            scalac,
            '-encoding UTF8',
            '-d ${out}',
            '-classpath ${classpath}',
            '${scalacflags}',
            '${in}'
        ]
        self.generate_rule(name='scalac',
                           command=' '.join(cmd),
                           description='SCALAC ${out}')

    def generate_scalatest_rule(self, java_config):
        java = self.get_java_command(java_config, 'java')
        scala = 'scala'
        scala_home = config.get_item('scala_config', 'scala_home')
        if scala_home:
            scala = os.path.join(scala_home, 'bin', scala)
        jacocoagent = self.get_jacocoagent()
        args = ('--java=%s --scala=%s --jacocoagent=%s --packages_under_test=${packages_under_test} '
                '--script=${out} ${in}') % (java, scala, jacocoagent)
        self.generate_rule(name='scalatest', command=self._builtin_command('scala_test', args),
                           description='SCALA TEST ${out}')

    def generate_java_scala_rules(self):
        java_config = config.get_section('java_config')
        self.generate_javac_rules(java_config)
        self.generate_java_resource_rules()
        self.generate_java_jar_rules(java_config)
        self.generate_java_test_rules()
        self.generate_fatjar_rules(java_config)
        self.generate_java_binary_rules()
        self.generate_scalac_rule(java_config)
        self.generate_scalatest_rule(java_config)

    def generate_thrift_rules(self):
        thrift_config = config.get_section('thrift_config')
        incs = _incs_list_to_string(thrift_config['thrift_incs'])
        gen_params = thrift_config['thrift_gen_params']
        thrift = thrift_config['thrift']
        if thrift.startswith('//'):
            thrift = thrift.replace('//', self.build_dir + '/')
            thrift = thrift.replace(':', '/')
        self.generate_rule(name='thrift',
                           command='%s --gen %s '
                                   '-I . %s -I `dirname ${in}` '
                                   '-out %s/`dirname ${in}` ${in}' % (
                                       thrift, gen_params, incs, self.build_dir),
                           description='THRIFT ${in}')

    def generate_python_rules(self):
        args = '--basedir=${basedir} --pylib=${out} ${in}'
        self.generate_rule(name='pythonlibrary',
                           command=self._builtin_command('python_library', args),
                           description='PYTHON LIBRARY ${out}')
        args = ('--basedir=${basedir} --exclusions=${exclusions} --mainentry=${mainentry} '
                '--pybin=${out} ${in}')
        self.generate_rule(name='pythonbinary',
                           command=self._builtin_command('python_binary', args),
                           description='PYTHON BINARY ${out}')

    def generate_go_rules(self):
        go_home = config.get_item('go_config', 'go_home')
        go = config.get_item('go_config', 'go')
        go_module_enabled = config.get_item('go_config', 'go_module_enabled')
        go_module_relpath = config.get_item('go_config', 'go_module_relpath')
        if go_home and go:
            go_pool = 'golang_pool'
            self._add_line(textwrap.dedent('''\
                    pool %s
                      depth = 1
                    ''') % go_pool)
            go_path = os.path.normpath(os.path.abspath(go_home))
            out_relative = ""
            if go_module_enabled:
                prefix = go
                if go_module_relpath:
                    relative_prefix = os.path.relpath(prefix, go_module_relpath)
                    prefix = f"cd {go_module_relpath} && {relative_prefix}"
                    # add slash to the end of the relpath
                    out_relative = os.path.join(os.path.relpath("./", go_module_relpath), "")
            else:
                prefix = f'GOPATH={go_path} {go}'
            self.generate_rule(name='gopackage',
                               command='%s install ${extra_goflags} ${package}' % prefix,
                               description='GO INSTALL ${package}',
                               pool=go_pool)
            self.generate_rule(name='gocommand',
                               command=f'{prefix} build -o {out_relative}${{out}} ${{extra_goflags}} ${{package}}',
                               description='GO BUILD ${package}',
                               pool=go_pool)
            self.generate_rule(name='gotest',
                               command=f'{prefix} test -c -o {out_relative}${{out}} ${{extra_goflags}} ${{package}}',
                               description='GO TEST ${package}',
                               pool=go_pool)

    def generate_shell_rules(self):
        self.generate_rule(name='shelltest',
                           command=self._builtin_command('shell_test'),
                           description='SHELL TEST ${out}')
        args = '${out} ${in} ${testdata}'
        self.generate_rule(name='shelltestdata',
                           command=self._builtin_command('shell_testdata', args),
                           description='SHELL TEST DATA ${out}')

    def generate_lex_yacc_rules(self):
        if os.name == 'nt':
            lex_cmd = 'win_flex --wincompat'
            yacc_cmd = 'win_bison'
            # win_bison may be invoked via WinGet Links hardlink, which causes
            # bison to look for data/m4sugar/ next to the link instead of the
            # real install dir. Set BISON_PKGDATADIR to the actual data dir.
            bison_data_dir = self._find_win_bison_data_dir()
            if bison_data_dir:
                yacc_cmd = f'cmd /c set "BISON_PKGDATADIR={bison_data_dir}" && win_bison'
        else:
            lex_cmd = 'flex'
            yacc_cmd = 'bison'
        self.generate_rule(name='lex',
                           command=f'{lex_cmd} ${{lexflags}} -o ${{out}} ${{in}}',
                           description='LEX ${in}')
        self.generate_rule(name='yacc',
                           command=f'{yacc_cmd} ${{yaccflags}} -o ${{out}} ${{in}}',
                           description='YACC ${in}')

    @staticmethod
    def _find_win_bison_data_dir():
        for pattern in [
            os.path.join(os.path.dirname(shutil.which('win_bison') or ''), 'data'),
            os.path.join(os.environ.get('LOCALAPPDATA', ''),
                         'Microsoft', 'WinGet', 'Packages',
                         'WinFlexBison*', 'data'),
        ]:
            matches = glob.glob(pattern)
            if matches and os.path.isdir(matches[0]):
                return matches[0]
        return None

    def generate_package_rules(self):
        args = '${out} ${in} ${entries}'
        self.generate_rule(name='package',
                           command=self._builtin_command('package', args),
                           description='PACKAGE ${out}')
        self.generate_rule(name='package_tar',
                           command='tar -c -f ${out} ${tarflags} -C ${packageroot} ${entries}',
                           description='TAR ${out}')
        self.generate_rule(name='package_zip',
                           command='cd ${packageroot} && zip -q temp_archive.zip ${entries} && '
                                   'cd - && mv ${packageroot}/temp_archive.zip ${out}',
                           description='ZIP ${out}')

    def generate_version_rules(self):
        cc = self.build_toolchain.get_cc()
        cc_version = self.build_toolchain.get_cc_version()

        revision, url = util.load_scm(self.build_dir)
        args = '--scm=${out} --revision=${revision} --url=${url} --profile=${profile} --compiler="${compiler}"'
        self.generate_rule(name='scm',
                           command=self._builtin_command('scm', args),
                           description='SCM ${out}')
        scm = os.path.join(self.build_dir, 'scm.cc')
        self._add_line(textwrap.dedent('''\
                build %s: scm
                  revision = %s
                  url = %s
                  profile = %s
                  compiler = %s
                ''') % (scm, revision, url, self.options.profile, f'{cc} {cc_version}'))
        scm_obj = self.build_toolchain.object_file_of(scm)
        # The `cxx` rule routes through the inclusion wrapper, which needs an
        # `inclusion_stack` path (custom ninja vars cannot default at rule level).
        # scm.cc is not inclusion-checked, so point it at a throwaway file.
        self._add_line(textwrap.dedent('''\
                build %s: cxx %s
                  cppflags = -w -O2
                  cxx_warnings =
                  inclusion_stack = %s
                ''') % (scm_obj, scm, scm_obj + '.incstk'))

    def generate_cuda_rules(self):
        if self.build_toolchain.cc_is('msvc'):
            self._generate_msvc_cuda_rules()
        else:
            self._generate_gcc_cuda_rules()

    def _generate_gcc_cuda_rules(self):
        nvcc_cmd = '${cmd}'

        cc_config = config.get_section('cc_config')
        cuda_config = config.get_section('cuda_config')
        cxxflags = cc_config['cxxflags']
        cppflags, _ = self._get_intrinsic_cc_flags()
        cppflags = cc_config['cppflags'] + cppflags
        cxxflags = ['-Xcompiler %s' % flag for flag in cxxflags]
        cppflags = ['-Xcompiler %s' % flag for flag in cppflags]
        cuflags = cuda_config['cuflags']
        includes = cc_config['extra_incs']
        includes = includes + ['.', self.build_dir]
        includes = ' '.join(['-I%s' % inc for inc in includes])

        template = self._cc_compile_command_wrapper_template('${inclusion_stack}', cuda=True)

        _, cxx, _ = self.build_accelerator.get_cc_commands()
        cu_command = '%s -ccbin "%s" -o ${out} -MMD -MF ${out}.d ' \
            '-Xcompiler -fPIC %s %s %s ${optimize} ${cu_warnings} ' \
            '%s ${includes} ${cppflags} ${cuflags} -c ${in}' % (
                nvcc_cmd, cxx, ' '.join(cxxflags), ' '.join(cppflags),
                ' '.join(cuflags), includes)
        self.generate_rule(
            name='cudacc',
            command=template % cu_command,
            description='CUDA LIBRARY ${in}',
            depfile='${out}.d',
            deps='gcc',
        )

        # CUDA linking might have a lot of input files exceeding maximal length of a bash command line.
        # Using response file (nvcc --options-file) can resolve this problem.
        link_args = '-o ${out} ${includes} ${cppflags} --options-file ${out}.rsp ${extra_linkflags}'
        self.generate_rule(
            name='cudalink',
            command=nvcc_cmd + ' ' + link_args,
            rspfile='${out}.rsp',
            rspfile_content='${target_linkflags} ${in}',
            description='CUDA LINK BINARY ${out}')

        self.generate_rule(
            name='cudasolink',
            command=nvcc_cmd + ' -shared ' + link_args,
            rspfile='${out}.rsp',
            rspfile_content='${target_linkflags} ${in}',
            description='CUDA LINK SHARED ${out}')

    def _generate_msvc_cuda_rules(self):
        """Generate CUDA rules for MSVC host compiler on Windows.

        NVCC on Windows delegates host code to cl.exe.  Flags that pass
        through to the host compiler via -Xcompiler must be MSVC-compatible.
        """
        cc_config = config.get_section('cc_config')
        ms_config = config.get_section('msvc_config')
        cuda_config = config.get_section('cuda_config')

        # Build MSVC-compatible host compiler flags, filtered through the
        # toolchain so that GCC-isms from cc_config get mapped or dropped.
        filtered_cppflags = self.build_toolchain.filter_cc_flags(cc_config['cppflags'])
        filtered_cxxflags = self.build_toolchain.filter_cc_flags(cc_config['cxxflags'], 'c++')
        cppflags = ms_config['cppflags'] + filtered_cppflags
        cxxflags = ms_config['cxxflags'] + filtered_cxxflags

        # NVCC's cudafe++ (which preprocesses host code before MSVC) has a
        # limited C++ STL understanding.  /EHsc and /std:c++17 pull in STL
        # internal headers (e.g. xtr1common) that trigger an assertion in
        # cudafe++ — this is an NVCC limitation, not an MSVC version issue.
        cppflags = [f for f in cppflags if not f.startswith('/EH')]
        cxxflags = [f for f in cxxflags if not f.startswith('/EH')]
        cppflags = [f for f in cppflags if not f.startswith('/std:')]
        cxxflags = [f for f in cxxflags if not f.startswith('/std:')]

        # -Xcompiler passes flags to the host compiler (cl.exe); NVCC
        # itself understands -I / -D / etc. natively.
        host_cppflags = ' '.join('-Xcompiler %s' % f for f in cppflags)
        host_cxxflags = ' '.join('-Xcompiler %s' % f for f in cxxflags)

        cuflags = cuda_config['cuflags']
        system_includes = self.build_toolchain.get_system_include_paths()
        includes = system_includes + cc_config['extra_incs'] + ['.', self.build_dir]
        # NVCC uses -I natively, same across platforms.
        # Quote paths with spaces so nvcc parses them as a single argument.
        def _quote_if_needed(p):
            return '-I"%s"' % p if ' ' in p else '-I%s' % p
        include_flags = ' '.join(_quote_if_needed(inc) for inc in includes)

        # NVCC -Xcompiler /showIncludes lets Ninja deps=msvc track headers.
        # The Python wrapper tees /showIncludes to both stderr (for Ninja) and
        # the inclusion stack file.
        py = sys.executable
        wrapper = self._msvc_tee_wrapper_py()
        template = '"%s" -B %s ${inclusion_stack} -- ' % (py, wrapper)

        _, cxx, _ = self.build_accelerator.get_cc_commands()
        cu_command = template + ('"${cmd}" -ccbin "%s" -o ${out} -c '
                                 '-Xcompiler /nologo -Xcompiler /showIncludes '
                                 '%s %s %s '
                                 '%s ${includes} %s ${cu_warnings} ${in}' % (
                                     cxx,
                                     host_cppflags, host_cxxflags,
                                     ' '.join(cuflags),
                                     include_flags, '${cppflags}'))
        self.generate_rule(
            name='cudacc',
            command=cu_command,
            description='CUDA LIBRARY ${in}',
            deps='msvc',
            restat=True,
        )

        # NVCC linking delegates to the host linker automatically.
        # Include -ccbin so nvcc can find cl.exe even without a VS dev shell.
        link_args = ('-o ${out} %s ${cppflags} '
                     '--options-file ${out}.rsp ${extra_linkflags}' % include_flags)
        self.generate_rule(
            name='cudalink',
            command='"${cmd}" -ccbin "%s" ' % cxx + link_args,
            rspfile='${out}.rsp',
            rspfile_content='${target_linkflags} ${in}',
            description='CUDA LINK BINARY ${out}')

        self.generate_rule(
            name='cudasolink',
            command='"${cmd}" -ccbin "%s" -shared ' % cxx + link_args,
            rspfile='${out}.rsp',
            rspfile_content='${target_linkflags} ${in}',
            description='CUDA LINK SHARED ${out}')

    def _builtin_command(self, builder, args=''):
        python = os.environ.get('BLADE_PYTHON_INTERPRETER') or sys.executable
        if os.name == 'nt':
            # On Windows, PYTHONPATH uses ';' and cmd.exe must be explicit
            python_cmd = f'set PYTHONPATH={self.blade_path};%PYTHONPATH% && {python} -m blade.builtin_tools {builder}'
            cmd = ['cmd /c', python_cmd]
        else:
            cmd = ['PYTHONPATH=%s:$$PYTHONPATH' % self.blade_path]
            cmd.append(f'{python} -m blade.builtin_tools {builder}')
        if args:
            cmd.append(args)
        else:
            cmd.append('${out} ${in}')
        return ' '.join(cmd)

    def generate(self):
        """Generate ninja rules."""
        self.generate_file_header()
        self.generate_common_rules()
        self.generate_cc_rules()
        self.generate_proto_rules()
        self.generate_resource_rules()
        self.generate_java_scala_rules()
        self.generate_thrift_rules()
        self.generate_python_rules()
        self.generate_go_rules()
        self.generate_shell_rules()
        self.generate_lex_yacc_rules()
        self.generate_package_rules()
        self.generate_version_rules()
        self.generate_cuda_rules()
        return self.rules_buf


class NinjaFileGenerator:
    """Generate ninja rules to build.ninja."""

    def __init__(self, ninja_path, blade_path, blade):
        self.script_path = ninja_path
        self.blade_path = blade_path
        self.blade = blade
        self.build_toolchain = blade.get_build_toolchain()
        self.build_dir = blade.get_build_dir()
        self.__all_rule_names = []

    def get_all_rule_names(self):
        return self.__all_rule_names

    def generate_build_code(self):
        """Generate ninja code to build.ninja."""
        ninja_script_header_generator = _NinjaFileHeaderGenerator(
            self.blade.get_command(),
            self.blade.get_options(),
            self.build_dir,
            self.blade_path,
            self.build_toolchain,
            self.blade)
        code = ninja_script_header_generator.generate()
        code += self.blade.generate_targets_build_code()
        self.__all_rule_names = ninja_script_header_generator.get_all_rule_names()
        return code

    def generate_build_script(self):
        """Generate build script for underlying build system."""
        code = self.generate_build_code()
        with open(self.script_path, 'w', encoding='utf-8') as script:
            script.writelines(code)
