# Copyright (c) 2017 Tencent Inc.
# All rights reserved.
#
# Author: Li Wenting <wentingli@tencent.com>
# Date:   October 27, 2017

"""
This module defines various build functions for building
targets from sources and custom parameters.

Performance note: this module is the entry point of the
``python -m blade.builtin_tools`` subprocess, spawned once per build action
(the hot one being ``cc_inclusion_check``, run per cc target). To keep that
startup cheap, heavier stdlib modules used only by cold tools (``fnmatch``,
``getpass``, ``socket``, ``subprocess``, ``tarfile``, ``zipfile``) are imported
lazily inside the functions that use them, each marked
``pylint: disable=import-outside-toplevel``. See issue #1159.
"""


import os
import pickle
import shutil
import sys
import textwrap
import traceback
import time

from blade import console
from blade import util


# These following helper functions is designed to centralize error handling


_outputs = []


def _declare_outputs(*outputs):
    """Declare output files, which can be verified after ran and cleanup on error."""
    _outputs[:] = outputs


def _verify_outputs():
    """Verify whether the declared output files were correctly generated."""
    missing = [o for o in _outputs if not os.path.exists(o)]
    if missing:
        raise FileNotFoundError('"%s" is not generated' % missing)


def _cleanup_outputs():
    """Cleanup declared output files on error."""
    console.debug('Cleanup:%s' % _outputs)
    for output in _outputs:
        try:
            os.remove(output)
        except OSError:
            pass


# The build functions are defined as follows form:
#
#    def build_function_name(kwargs..., args):
#        pass
#
#    Args:
#        * kwargs...: name=value pairs as parameters in command line
#        * args: any other non-kw args
#
#    Return:
#        Return None(include implicit return) or 0 on success, otherwise return
#        a positive int (e.g. 1) or raise an exception to indicate failure.
#
#    When call this from the command line, all arguments which match the
#    `--name=value` pattern will be converted into kwargs, any other arguments
#    are merged into the `args` argument. So any `name` must be a valid python
#    identifier.


def generate_scm(scm, revision, url, profile, compiler, args):
    """Generate `scm.c` file"""
    import getpass  # pylint: disable=import-outside-toplevel
    import socket  # pylint: disable=import-outside-toplevel

    _declare_outputs(scm)

    def _escape_c_str(s):
        return s.replace('\\', '\\\\')

    version = f'{url}@{revision}'
    with open(scm, 'w') as f:
        f.write(textwrap.dedent(r'''\
                /* This file was generated by blade */
                extern "C" {
                namespace binary_version {
                extern const int kSvnInfoCount = 1;
                extern const char* const kSvnInfo[] = {"%s\n"};
                extern const int kScmInfoCount = 1;
                extern const char* const kScmInfo[] = {"%s\n"};
                extern const char kBuildType[] = "%s";
                extern const char kBuildTime[] = "%s";
                extern const char kBuilderName[] = "%s";
                extern const char kHostName[] = "%s";
                extern const char kCompiler[] = "%s";
                }}''') % (_escape_c_str(version),
                          _escape_c_str(version),
                          profile,
                          time.asctime(),
                          getpass.getuser(),
                          socket.gethostname(),
                          _escape_c_str(compiler)))


def generate_cc_inclusion_check(args):
    # Import from function to avoid affecting the performance of other tools.
    from blade import inclusion_check  # pylint: disable=import-outside-toplevel
    result_file = args[0]
    info_file = args[1]
    _declare_outputs(result_file)
    console.set_log_file('%s.log' % info_file)
    console.enable_color(True)
    ok, details = inclusion_check.check(info_file)
    with open(info_file + '.details', 'wb') as f:
        pickle.dump(details, f)
    if not ok:
        return 1
    with open(result_file, 'w') as f:
        f.write('OK')
    return None


# --- Windows DLL auto-export: synthesize a .def from object files ----------
#
# To make a Windows DLL export its symbols without `__declspec(dllexport)`
# annotations, we parse the COFF object files directly (pure stdlib `struct`,
# the same approach as CMake's bindexplib / Bazel's def_parser) and emit a
# `.def`. Unlike those tools, we *filter out the dedup COMDAT symbols* —
# template instantiations, inline functions, string/float constants, vtables,
# RTTI — which the consumer always instantiates itself from headers and never
# needs to import. That keeps the export table small (the naive "export all"
# is what makes WINDOWS_EXPORT_ALL_SYMBOLS blow the 64k export limit on
# template-heavy C++).
#
# The discriminator is the COMDAT *selection*, not merely "is COMDAT": under
# /Gy (on at /O2) even ordinary functions become COMDAT, but with selection
# NODUPLICATES (a unique definition) — those we keep. The dedup selections
# (ANY / SAME_SIZE / EXACT_MATCH / LARGEST) are the header-provided copies we
# drop. See blade-build/blade-build#1181.

_IMAGE_SYM_CLASS_EXTERNAL = 2
_IMAGE_SYM_CLASS_STATIC = 3
_IMAGE_SYM_DTYPE_FUNCTION = 0x20  # Type high nibble == FUNCTION
# COMDAT selection values that mean "duplicates are expected and folded" — the
# symbol is provided by every TU that uses it, so the DLL needn't export it.
_COMDAT_DEDUP_SELECTIONS = frozenset((2, 3, 4, 6))


def _select_dll_exports(symbols, section_selection):
    """Pick the symbols a DLL should export, from parsed COFF symbol records.

    ``symbols`` is a list of ``(name, storage_class, section_number, coff_type)``
    and ``section_selection`` maps a section number to its COMDAT selection
    (0 / absent = not COMDAT). Returns an ordered, de-duplicated list of
    ``(name, is_data)``.

    A symbol is exported when it is **external** and **defined here**
    (``section_number > 0``) and its section is not a *dedup* COMDAT. Functions
    (COFF type FUNCTION) are exported plain; everything else is data and gets
    the ``DATA`` keyword in the `.def`.
    """
    seen = {}
    for name, storage_class, section_number, coff_type in symbols:
        if storage_class != _IMAGE_SYM_CLASS_EXTERNAL or section_number <= 0:
            continue
        if section_selection.get(section_number, 0) in _COMDAT_DEDUP_SELECTIONS:
            continue
        if not name:
            continue
        is_data = coff_type != _IMAGE_SYM_DTYPE_FUNCTION
        seen.setdefault(name, is_data)  # first definition wins
    return list(seen.items())


# --- export_map (GNU-ld version script) filtering on MSVC ------------------
#
# `export_map` is a GNU-ld `--version-script`; MSVC has no equivalent. To honor
# it on Windows we filter the auto-`.def` (above) through the map: keep only
# symbols matched by a `global:` pattern (and not hidden by `local:`).
#
# Version-script patterns are written against Itanium-demangled names; MSVC
# symbols are decorated differently, so we demangle each candidate with
# `UnDecorateSymbolName(UNDNAME_NAME_ONLY)`, which yields just the qualified
# name (e.g. `mylib::Api::Greet`). That matches `extern "C++"` globs like
# `mylib::Api::*` well, but it drops the signature -- so overloads collapse to
# one name and quoted signature patterns (`"mylib::Create()"`) are matched by
# their name part only. See blade-build#1194.

_UNDNAME_NAME_ONLY = 0x1000
_undname_fn = None


def _undecorate_name_only(symbol):
    """Return the MSVC symbol's demangled qualified name (no signature).

    Windows-only (uses dbghelp). For a non-decorated name (e.g. an `extern "C"`
    symbol) UnDecorateSymbolName returns it unchanged. Falls back to the raw
    symbol if demangling is unavailable or fails.
    """
    global _undname_fn  # pylint: disable=global-statement
    if _undname_fn is None:
        import ctypes  # pylint: disable=import-outside-toplevel
        from ctypes import wintypes  # pylint: disable=import-outside-toplevel
        fn = ctypes.WinDLL('dbghelp').UnDecorateSymbolName
        fn.argtypes = [wintypes.LPCSTR, wintypes.LPSTR, wintypes.DWORD, wintypes.DWORD]
        fn.restype = wintypes.DWORD
        _undname_fn = fn
    import ctypes  # pylint: disable=import-outside-toplevel
    buf = ctypes.create_string_buffer(4096)
    n = _undname_fn(symbol.encode('ascii', 'replace'), buf, 4096, _UNDNAME_NAME_ONLY)
    return buf.value.decode('ascii', 'replace') if n else symbol


def _parse_export_map(path):
    """Parse a GNU-ld version script into (global_patterns, local_patterns).

    Each pattern is ``(text, is_cpp, is_quoted)``: ``is_cpp`` marks patterns
    inside an ``extern "C++"`` block (matched against the demangled name);
    ``is_quoted`` marks a quoted literal (no wildcards). Comments (``#``,
    ``//``, ``/* */``), version-node names and ``extern "C"`` blocks are
    handled; named version tags are flattened (their global/local patterns are
    unioned -- on PE there is no symbol versioning, only export filtering).
    """
    import re  # pylint: disable=import-outside-toplevel
    with open(path, encoding='utf-8') as f:
        text = f.read()
    text = re.sub(r'/\*.*?\*/', ' ', text, flags=re.S)
    text = re.sub(r'(?:#|//).*', ' ', text)
    tokens = re.findall(r'"[^"]*"|[{};]|(?:global|local)\s*:|extern|[^\s{};]+', text)

    globals_, locals_ = [], []
    section = None
    cpp_stack = [False]
    pending_extern = False
    pending_lang = None
    for tok in tokens:
        if tok in ('{', '}'):
            if tok == '{':
                cpp = (pending_lang == 'C++') if pending_extern else cpp_stack[-1]
                cpp_stack.append(cpp)
            else:  # '}'
                if len(cpp_stack) > 1:
                    cpp_stack.pop()
                if len(cpp_stack) == 1:
                    # Closed a version node: the next token (a named-version tag
                    # like `VER_2`, or a `} VER_1;` dependency) must not be read
                    # as a pattern under the previous node's section.
                    section = None
            pending_extern, pending_lang = False, None
        elif tok == ';':
            continue
        elif tok.rstrip().rstrip(':') in ('global', 'local') and tok.endswith(':'):
            section = tok.rstrip().rstrip(':')
        elif tok == 'extern':
            pending_extern = True
        elif pending_extern and tok.startswith('"'):
            pending_lang = tok.strip('"')
        else:
            quoted = tok.startswith('"')
            pat = tok.strip('"') if quoted else tok
            if not pat:
                continue
            entry = (pat, cpp_stack[-1], quoted)
            if section == 'global':
                globals_.append(entry)
            elif section == 'local':
                locals_.append(entry)
    return globals_, locals_


def _export_map_match(patterns, name, dname):
    """True if `name` (raw) / `dname` (demangled name-only) matches a pattern."""
    import fnmatch  # pylint: disable=import-outside-toplevel
    for pat, is_cpp, quoted in patterns:
        target = dname if is_cpp else name
        if quoted:
            # Name-only demangling drops the signature, so match the pattern's
            # name part (everything before '(') exactly. Overloads collapse.
            if target == pat.split('(', 1)[0]:
                return True
        elif fnmatch.fnmatchcase(target, pat):
            return True
    return False


def _export_map_keeps(name, dname, globals_, locals_):
    """Version-script export decision: keep iff `global`, else drop if `local`.

    A symbol matched by a `global:` pattern is exported (a specific global wins
    over a wildcard `local: *`). Otherwise it is hidden when any `local:`
    pattern matches it -- which includes the usual `local: *;` catch-all. With
    no `local:` section the map does not restrict exports.
    """
    if _export_map_match(globals_, name, dname):
        return True
    return not _export_map_match(locals_, name, dname)


def _filter_exports_by_map(seen, export_map):
    """Filter the auto-export `seen` dict through an export_map version script."""
    globals_, locals_ = _parse_export_map(export_map)
    if any(quoted for _, _, quoted in globals_ + locals_):
        console.warning(
            'cc_windef: %s: quoted signature patterns are matched by name only '
            'on MSVC (UnDecorateSymbolName has no Itanium signature); overloads '
            'are not distinguished.' % export_map)
    kept = {}
    for name, is_data in seen.items():
        dname = _undecorate_name_only(name)
        if _export_map_keeps(name, dname, globals_, locals_):
            kept[name] = is_data
    return kept


def _parse_coff(data):
    """Parse a COFF object file's symbol table (pure stdlib `struct`).

    Returns ``(symbols, section_selection)`` as consumed by
    :func:`_select_dll_exports`. Raises ``NotImplementedError`` for the
    "bigobj" variant (used only by objects with > 65279 sections), which the
    caller should surface as an actionable error.
    """
    import struct  # pylint: disable=import-outside-toplevel
    machine, = struct.unpack_from('<H', data, 0)
    sig2, = struct.unpack_from('<H', data, 2)
    if machine == 0 and sig2 == 0xFFFF:
        raise NotImplementedError('bigobj COFF object is not supported')
    # IMAGE_FILE_HEADER: skip to symbol-table pointer / count.
    _num_sections, _ts, sym_off, num_syms = struct.unpack_from('<HIII', data, 2)
    strtab_off = sym_off + num_syms * 18

    def read_name(name8):
        if name8[:4] == b'\x00\x00\x00\x00':
            off, = struct.unpack('<I', name8[4:8])
            end = data.index(b'\x00', strtab_off + off)
            return data[strtab_off + off:end].decode('latin-1')
        return name8.rstrip(b'\x00').decode('latin-1')

    symbols = []
    section_selection = {}
    i = 0
    while i < num_syms:
        rec = sym_off + i * 18
        name8 = data[rec:rec + 8]
        value, secnum, ctype, sclass, naux = struct.unpack_from('<IhHBB', data, rec + 8)
        # A section-definition symbol (Static, type NULL, value 0, one aux)
        # carries the COMDAT selection of its section in that aux record.
        if (sclass == _IMAGE_SYM_CLASS_STATIC and ctype == 0 and value == 0
                and naux >= 1 and secnum > 0):
            selection, = struct.unpack_from('<B', data, rec + 18 + 14)
            section_selection[secnum] = selection
        elif sclass == _IMAGE_SYM_CLASS_EXTERNAL:
            symbols.append((read_name(name8), sclass, secnum, ctype))
        i += 1 + naux
    return symbols, section_selection


def generate_cc_windef(args, export_map=None):
    """Generate a `.def` exporting the symbols of the given objects (Windows).

    Invoked as ``cc_windef [--export_map=<file>] <output.def> <obj>...``. Parses
    each object's COFF symbol table directly and writes the filtered export
    list. When ``--export_map`` is given, the auto-export set is further
    filtered through that GNU-ld version script (matched by demangled name).
    """
    output = args[0]
    objs = args[1:]
    _declare_outputs(output)
    seen = {}
    for obj in objs:
        with open(obj, 'rb') as f:
            data = f.read()
        try:
            symbols, section_selection = _parse_coff(data)
        except NotImplementedError as e:
            console.error('cc_windef: %s: %s. Use an export_map or '
                          'generate_dynamic=False for this target.' % (obj, e))
            return 1
        for name, is_data in _select_dll_exports(symbols, section_selection):
            seen.setdefault(name, is_data)
    if export_map:
        seen = _filter_exports_by_map(seen, export_map)
    with open(output, 'w', encoding='utf-8') as f:
        f.write('EXPORTS\n')
        for name, is_data in seen.items():
            f.write('    %s%s\n' % (name, ' DATA' if is_data else ''))
    return None


_PACKAGE_MANIFEST = 'MANIFEST.TXT'


def archive_package_sources(package, sources, destinations):
    """Content of the `MANIFEST.TXT` file in the target zip file"""
    manifest = []
    for i, s in enumerate(sources):
        package(s, destinations[i])
        manifest.append(f'{util.md5sum_file(s)} {destinations[i]}')
    return manifest


def generate_zip_package(path, sources, destinations):
    import zipfile  # pylint: disable=import-outside-toplevel
    zip = zipfile.ZipFile(path, 'w', zipfile.ZIP_DEFLATED, allowZip64=True)
    manifest = archive_package_sources(zip.write, sources, destinations)
    zip.writestr(_PACKAGE_MANIFEST, '\n'.join(manifest) + '\n')
    zip.close()


def generate_tar_package(path, sources, destinations, mode):
    import tarfile  # pylint: disable=import-outside-toplevel
    tar = tarfile.open(path, mode, dereference=True)
    manifest = archive_package_sources(tar.add, sources, destinations)
    manifest_path = '%s.MANIFEST' % path
    with open(manifest_path, 'w') as m:
        m.write('\n'.join(manifest) + '\n\n')
    tar.add(manifest_path, _PACKAGE_MANIFEST)
    tar.close()


_TAR_WRITE_MODES = {
    'tar': 'w',
    'tar.gz': 'w:gz',
    'tgz': 'w:gz',
    'tar.bz2': 'w:bz2',
    'tbz': 'w:bz2',
}


def _tar_write_mode(path):
    """Get the tar write mode from extname of path"""
    for ext, mode in _TAR_WRITE_MODES.items():
        if path.endswith(ext):
            return mode
    return ''


def generate_package(args):
    path = args[0]
    manifest = args[1:]
    _declare_outputs(path)
    assert len(manifest) % 2 == 0
    middle = len(manifest) // 2
    sources = manifest[:middle]
    destinations = manifest[middle:]
    if path.endswith('.zip'):
        generate_zip_package(path, sources, destinations)
    else:
        mode = _tar_write_mode(path)
        generate_tar_package(path, sources, destinations, mode)


def _generate_resource_index(targets, sources, name, path):
    """Generate resource index description file for a cc resource library"""
    header, source = targets
    # Normalize to forward slashes for use in C code (identifiers, strings, includes)
    header_fwd = util.to_unix_path(header)
    with open(header, 'w') as h, open(source, 'w') as c:
        full_name = util.regular_variable_name(os.path.join(path, name))
        guard_name = 'BLADE_RESOURCE_%s_H_' % full_name.upper()
        index_name = 'RESOURCE_INDEX_%s' % full_name

        h.write(textwrap.dedent('''\
                // This file was automatically generated by blade
                #ifndef {0}
                #define {0}

                #ifdef __cplusplus
                extern "C" {{
                #endif

                #ifndef BLADE_RESOURCE_TYPE_DEFINED
                #define BLADE_RESOURCE_TYPE_DEFINED
                struct BladeResourceEntry {{
                    const char* name;
                    const char* data;
                    unsigned int size;
                }};
                #endif''').format(guard_name))
        c.write(textwrap.dedent('''\
                // This file was automatically generated by blade
                #include "{0}"

                const struct BladeResourceEntry {1}[] = {{''').format(header_fwd, index_name))

        for s in sources:
            entry_var = util.regular_variable_name(s)
            entry_name = util.to_unix_path(os.path.relpath(s, path))
            entry_size = os.path.getsize(s)
            h.write('// %s\n' % entry_name)
            h.write('extern const char RESOURCE_%s[%d];\n' % (entry_var, entry_size))
            h.write('extern const unsigned RESOURCE_%s_len;\n' % entry_var)
            c.write(f'    {{ "{entry_name}", RESOURCE_{entry_var}, {entry_size} }},\n')

        c.write(textwrap.dedent('''\
                }};
                const unsigned {0}_len = {1};''').format(index_name, len(sources)))
        h.write(textwrap.dedent('''\
                // Resource index
                extern const struct BladeResourceEntry {0}[];
                extern const unsigned {0}_len;

                #ifdef __cplusplus
                }}  // extern "C"
                #endif

                #endif  // {1}''').format(index_name, guard_name))


def generate_resource_index(args):
    name, path = args[0], args[1]
    targets = args[2], args[3]
    sources = args[4:]
    _declare_outputs(*targets)
    return _generate_resource_index(targets, sources, name, path)


def generate_resource(args):
    """Convert a file to a C byte array (replaces xxd -i | sed)."""
    output = args[0]
    inputs = args[1:]
    _declare_outputs(output)
    return _generate_c_resource(inputs, output)


def _generate_c_resource(inputs, output):
    """Generate a C source file from binary resource files.

    Emits ``const char RESOURCE_<name>[]`` with hex byte data and
    ``const unsigned int RESOURCE_<name>_len`` for each input file.
    """
    parts = []
    for input_file in inputs:
        with open(input_file, 'rb') as f:
            data = f.read()
        var_name = util.regular_variable_name(input_file)
        parts.append(f'const char RESOURCE_{var_name}[] = {{')
        for i in range(0, len(data), 12):
            chunk = data[i:i + 12]
            hex_bytes = ', '.join(f'0x{b:02x}' for b in chunk)
            parts.append(f'  {hex_bytes}{"," if i + 12 < len(data) else ""}')
        parts.append('};')
        parts.append(f'const unsigned int RESOURCE_{var_name}_len = {len(data)};')
        parts.append('')
    with open(output, 'w') as f:
        f.write('\n'.join(parts))
        f.write('\n')


def generate_javac_compile(args):
    """Compile Java sources and create a jar file.

    Arguments are positional:
        classes_dir  output_jar  source_encoding  classpath  [javacflags...] -- [sources...]

    The ``--`` sentinel separates javac flags from source files so that
    multi-word Ninja variables (``${javacflags}``, ``${in}``) can be
    unpacked unambiguously.
    """
    import subprocess  # pylint: disable=import-outside-toplevel
    sep = args.index('--')
    classes_dir = args[0]
    output = args[1]
    source_encoding = args[2]
    classpath = args[3]
    javacflags = args[4:sep]
    sources = args[sep + 1:]

    _declare_outputs(output)
    shutil.rmtree(classes_dir, ignore_errors=True)
    os.makedirs(classes_dir, exist_ok=True)

    cmd = ['javac', '-encoding', source_encoding, '-d', classes_dir,
           '-classpath', classpath] + javacflags + sources
    subprocess.check_call(cmd)
    subprocess.check_call(['jar', 'cf', output, '-C', classes_dir, '.'])


def generate_java_jar(compression_level, args):
    jar, target = args[0], args[1]
    _declare_outputs(target)
    resources_dir = target.replace('.jar', '.resources')
    arg = args[2]
    if arg.endswith('__classes__.jar'):
        classes_jar = arg
        resources = args[3:]
    else:
        classes_jar = ''
        resources = args[2:]

    def archive_resources(resources_dir, resources, new=True):
        options = ('c' if new else 'u') + 'f' + compression_level
        cmd = [f'{jar} {options} {target}']
        for resource in resources:
            cmd.append(f"-C '{resources_dir}' '{os.path.relpath(resource, resources_dir)}'")
        return util.shell(cmd)

    if classes_jar:
        shutil.copy2(classes_jar, target)
        if resources:
            return archive_resources(resources_dir, resources, False)
    else:
        return archive_resources(resources_dir, resources, True)


def generate_java_resource(args):
    assert len(args) % 2 == 0
    middle = len(args) // 2
    targets = args[:middle]
    sources = args[middle:]
    _declare_outputs(*targets)
    for i in range(middle):
        shutil.copy(sources[i], targets[i])


def _get_all_test_class_names_in_jar(jar):
    """Returns a list of test class names in the jar file."""
    import zipfile  # pylint: disable=import-outside-toplevel
    test_class_names = []
    zip_file = zipfile.ZipFile(jar, 'r')
    name_list = zip_file.namelist()
    for name in name_list:
        basename = os.path.basename(name)
        # Exclude inner class and Test.class
        if (basename.endswith('Test.class') and
                len(basename) > len('Test.class') and '$' not in basename):
            class_name = name.replace('/', '.')[:-6]  # Remove .class suffix
            test_class_names.append(class_name)
    zip_file.close()
    return test_class_names


def _jacoco_test_coverage_flag(jacocoagent, packages_under_test):
    if packages_under_test and jacocoagent:
        jacocoagent = os.path.abspath(jacocoagent)
        packages = packages_under_test.split(':')
        options = [
            'includes=%s' % ':'.join([p + '.*' for p in packages if p]),
            'output=file',
        ]
        return '-javaagent:{}={}'.format(jacocoagent, ','.join(options))
    return ''


def generate_java_test(script, main_class, jacocoagent, packages_under_test, args):
    _declare_outputs(script)
    jars = args
    test_jar = jars[0]
    test_classes = ' '.join(_get_all_test_class_names_in_jar(test_jar))
    if os.name == 'nt':
        _generate_java_test_bat(script, main_class, jacocoagent, packages_under_test, jars, test_classes)
    else:
        _generate_java_test_sh(script, main_class, jacocoagent, packages_under_test, jars, test_classes)


def _generate_java_test_sh(script, main_class, jacocoagent, packages_under_test, jars, test_classes):
    coverage_flags = _jacoco_test_coverage_flag(jacocoagent, packages_under_test)
    abs_jars = [os.path.abspath(j) for j in jars]
    content = textwrap.dedent('''\
            #!/bin/sh
            # Auto generated wrapper shell script by blade

            if [ -n "$BLADE_COVERAGE" ]; then
                coverage_options="%s"
            fi

            exec java $coverage_options -classpath %s %s %s $@''') % (
            coverage_flags, ':'.join(abs_jars), main_class, test_classes)
    util.write_if_changed(script, content)
    os.chmod(script, 0o755)


def _generate_java_test_bat(script, main_class, jacocoagent, packages_under_test, jars, test_classes):
    coverage_flags = _jacoco_test_coverage_flag(jacocoagent, packages_under_test)
    abs_jars = [os.path.abspath(j) for j in jars]
    lines = [
        '@echo off\r\n',
        'rem Auto generated wrapper batch script by blade\r\n',
        '\r\n',
        'setlocal\r\n',
        'set "coverage_options="\r\n',
        'if defined BLADE_COVERAGE set "coverage_options=%s"\r\n' % coverage_flags,
        'java %%coverage_options%% -classpath %s %s %s %%*\r\n' % (
            ';'.join(abs_jars), main_class, test_classes),
        'endlocal\r\n',
    ]
    content = ''.join(lines)
    util.write_if_changed(script, content)


def generate_fat_jar(output, **kwargs):
    # Import from function to avoid affecting the performance of other tools.
    from blade import fatjar  # pylint: disable=import-outside-toplevel
    _declare_outputs(output)
    console.set_log_file('%s.log' % output.replace('.fat.jar', '__fatjar__'))
    console.enable_color(True)
    fatjar.generate_fat_jar(output=output, **kwargs)


def generate_one_jar(onejar, main_class, bootjar, args):
    import zipfile  # pylint: disable=import-outside-toplevel
    _declare_outputs(onejar)
    # Assume the first jar is the main jar, others jars are dependencies.
    main_jar = args[0]
    jars = args[1:]
    path = onejar
    onejar = zipfile.ZipFile(path, 'w', allowZip64=True)
    jar_path_set = set()
    # Copy files from one-jar-boot.jar to the target jar
    zip_file = zipfile.ZipFile(bootjar, 'r')
    name_list = zip_file.namelist()
    for name in name_list:
        if not name.lower().endswith('manifest.mf'):  # Exclude manifest
            onejar.writestr(name, zip_file.read(name))
            jar_path_set.add(name)
    zip_file.close()

    # Main jar and dependencies
    onejar.write(main_jar, os.path.join('main',
                                        os.path.basename(main_jar)))
    for dep in jars:
        dep_name = os.path.basename(dep)
        onejar.write(dep, os.path.join('lib', dep_name))

    # Copy resources to the root of target onejar
    for jar in [main_jar] + jars:
        jar = zipfile.ZipFile(jar, 'r')
        jar_name_list = jar.namelist()
        for name in jar_name_list:
            if name.endswith('.class') or name.upper().startswith('META-INF'):
                continue
            if name not in jar_path_set:
                jar_path_set.add(name)
                onejar.writestr(name, jar.read(name))
        jar.close()

    # Manifest
    # Note that the manifest file must end with a new line or carriage return
    onejar.writestr(os.path.join('META-INF', 'MANIFEST.MF'),
                    textwrap.dedent('''\
                            Manifest-Version: 1.0
                            Main-Class: com.simontuffs.onejar.Boot
                            One-Jar-Main-Class: %s

                            ''') % main_class)
    onejar.close()


def generate_java_binary(args):
    script, onejar = args
    _declare_outputs(script)
    basename = os.path.basename(onejar)
    fullpath = os.path.abspath(onejar)
    content = textwrap.dedent('''\
            #!/bin/sh
            # Auto generated wrapper shell script by blade

            jar=`dirname "$0"`/"%s"
            if [ ! -f "$jar" ]; then
              jar="%s"
            fi

            exec java -jar "$jar" $@
            ''') % (basename, fullpath)
    util.write_if_changed(script, content)
    os.chmod(script, 0o755)


def generate_scala_test(script, java, scala, jacocoagent, packages_under_test, args):
    _declare_outputs(script)
    jars = args
    test_jar = jars[0]
    test_class_names = _get_all_test_class_names_in_jar(test_jar)
    scala, java = os.path.abspath(scala), os.path.abspath(java)
    abs_jars = [os.path.abspath(j) for j in jars]
    java_args = ''
    coverage_flags = _jacoco_test_coverage_flag(jacocoagent, packages_under_test)
    if coverage_flags:
        java_args = '-J%s' % coverage_flags
    run_args = 'org.scalatest.run ' + ' '.join(test_class_names)
    with open(script, 'w') as f:
        text = textwrap.dedent('''\
                #!/bin/sh
                # Auto generated wrapper shell script by blade

                if [ -n "$BLADE_COVERAGE" ]; then
                    coverage_options="%s"
                fi

                JAVACMD=%s exec %s "$coverage_options" -classpath %s %s $@
                ''') % (java_args, java, scala, ':'.join(abs_jars), run_args)
        f.write(text)
    os.chmod(script, 0o755)


def generate_shell_test(args):
    wrapper = args[0]
    scripts = args[1:]
    _declare_outputs(wrapper)
    with open(wrapper, 'w') as f:
        f.write(textwrap.dedent("""\
                #!/bin/sh
                # Auto generated wrapper shell script by blade

                set -e

                %s

                """) % '\n'.join(['. %s' % os.path.abspath(s) for s in scripts]))
    os.chmod(wrapper, 0o755)


def generate_shell_testdata(args):
    path = args[0]
    testdata = args[1:]
    _declare_outputs(path)
    assert len(testdata) % 2 == 0
    middle = len(testdata) // 2
    sources = testdata[:middle]
    destinations = testdata[middle:]
    with open(path, 'w') as f:
        for i in range(middle):
            f.write(f'{os.path.abspath(sources[i])} {destinations[i]}\n')


def generate_python_library(pylib, basedir, args):
    _declare_outputs(pylib)
    sources = []
    for py in args:
        digest = util.md5sum_file(py)
        sources.append((py, digest))
    with open(pylib, 'w') as f:
        print(str({
            'base_dir': basedir,
            'srcs': sources
        }), file=f)


def _is_python_excluded_path(filename, exclusions):
    import fnmatch  # pylint: disable=import-outside-toplevel
    for exclusion in exclusions:
        if fnmatch.fnmatch(filename, exclusion):
            return True
    return False


def _update_init_py_dirs(arcname, dirs, dirs_with_init_py):
    dir = os.path.dirname(arcname)
    if os.path.basename(arcname) == '__init__.py':
        dirs_with_init_py.add(dir)
    while dir:
        dirs.add(dir)
        dir = os.path.dirname(dir)


def _pybin_add_pylib(pybin, libname, exclusions, dirs, dirs_with_init_py):
    with open(libname) as pylib:
        data = eval(pylib.read())  # pylint: disable=eval-used
        pylib_base_dir = data['base_dir']
        for libsrc, digest in data['srcs']:
            arcname = os.path.relpath(libsrc, pylib_base_dir)
            if not _is_python_excluded_path(arcname, exclusions):
                _update_init_py_dirs(arcname, dirs, dirs_with_init_py)
                pybin.write(libsrc, arcname)


def _pybin_add_zip(pybin, libname, filter, exclusions, dirs, dirs_with_init_py):
    import zipfile  # pylint: disable=import-outside-toplevel
    with zipfile.ZipFile(libname, 'r') as lib:
        name_list = lib.namelist()
        for name in name_list:
            if filter(name) and not _is_python_excluded_path(name, exclusions):
                if dirs is not None and dirs_with_init_py is not None:
                    _update_init_py_dirs(name, dirs, dirs_with_init_py)
                pybin.writestr(name, lib.read(name))


def _pybin_add_egg(pybin, libname, exclusions):
    def filter(name):
        if name.startswith('EGG-INFO'):
            return False
        if name.endswith('.pyc'):
            return False
        return True

    _pybin_add_zip(pybin, libname, filter, exclusions, None, None)


def _pybin_add_whl(pybin, libname, exclusions, dirs, dirs_with_init_py):
    def filter(name):
        if '.dist-info/' in name:
            return False
        return True

    _pybin_add_zip(pybin, libname, filter, exclusions, dirs, dirs_with_init_py)


def generate_python_binary(pybin, basedir, exclusions, mainentry, args):
    # pybin is the wrapper script.  The zip always goes to
    # <pybin_without_extension>.zip, identical on all platforms.
    import zipfile  # pylint: disable=import-outside-toplevel
    base, _ = os.path.splitext(pybin)
    zip_path = base + '.zip'
    _declare_outputs(pybin, zip_path)

    # Generate the pure zip file — identical on all platforms.
    pybin_zip = zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED, allowZip64=True)
    exclusions = exclusions.split(',')
    dirs, dirs_with_init_py = set(), set()
    for arg in args:
        if arg.endswith('.pylib'):
            _pybin_add_pylib(pybin_zip, arg, exclusions, dirs, dirs_with_init_py)
        elif arg.endswith('.egg'):
            _pybin_add_egg(pybin_zip, arg, exclusions)
        elif arg.endswith('.whl'):
            _pybin_add_whl(pybin_zip, arg, exclusions, dirs, dirs_with_init_py)
        else:
            assert False, 'Unknown file type "%s" to build python_binary' % arg

    # Insert __init__.py into each dir if missing
    dirs_missing_init_py = dirs - dirs_with_init_py
    for dir in sorted(dirs_missing_init_py):
        pybin_zip.writestr(os.path.join(dir, '__init__.py'), '')
    pybin_zip.writestr('__init__.py', '')
    pybin_zip.close()

    if os.name == 'nt':
        content = '@echo off\r\n'
        content += 'set "PYTHONPATH=%~dp0%~n0.zip;%PYTHONPATH%"\r\n'
        content += f'python -m {mainentry} %*\r\n'
        util.write_if_changed(pybin, content)
        return

    content = '#!/bin/sh\n'
    content += 'ZIP="$(dirname "$0")/$(basename "$0").zip"\n'
    content += ('PYTHONPATH="$ZIP:$PYTHONPATH" '
                'exec "${BLADE_PYTHON_INTERPRETER:-python3}" '
                f'-m {mainentry} "$@"\n')
    util.write_if_changed(pybin, content)
    os.chmod(pybin, 0o755)


def generate_dwp(args):
    """Generate dwp file for debugging."""
    # Import from function to avoid affecting the performance of other tools.
    from blade import dwp_wrapper  # pylint: disable=import-outside-toplevel

    output_file = args[0]
    input_files = args[1:]

    _declare_outputs(output_file)

    # Expand response files in inputs
    expanded_inputs = dwp_wrapper.expand_response_files(input_files)

    dwo_files = dwp_wrapper.collect_dwo_files(expanded_inputs)

    # Run dwp tool
    dwp_wrapper.run_dwp(output_file, dwo_files)


_BUILTIN_TOOLS = {
    'scm': generate_scm,
    'package': generate_package,
    'javac_compile': generate_javac_compile,
    'cc_inclusion_check': generate_cc_inclusion_check,
    'cc_windef': generate_cc_windef,
    'resource': generate_resource,
    'resource_index': generate_resource_index,
    'java_jar': generate_java_jar,
    'java_resource': generate_java_resource,
    'java_test': generate_java_test,
    'java_fatjar': generate_fat_jar,
    'java_onejar': generate_one_jar,
    'java_binary': generate_java_binary,
    'scala_test': generate_scala_test,
    'shell_test': generate_shell_test,
    'shell_testdata': generate_shell_testdata,
    'python_library': generate_python_library,
    'python_binary': generate_python_binary,
    'dwp': generate_dwp,
}


def main():
    name = sys.argv[1]
    exit_code = 0
    try:
        options, args = util.parse_command_line(sys.argv[2:])
        exit_code = _BUILTIN_TOOLS[name](args=args, **options)
        if not exit_code:
            _verify_outputs()
    except Exception as e:  # pylint: disable=broad-except
        console.error(f'Blade build tool {name} error: {e!s} {traceback.format_exc()}')
        exit_code = 1
    finally:
        if exit_code:
            _cleanup_outputs()
        sys.exit(exit_code or 0)


if __name__ == '__main__':
    main()
