# Copyright (c) 2017 Tencent Inc.
# All rights reserved.
#
# Author: Li Wenting <wentingli@tencent.com>
# Date:   October 27, 2017

"""
This module defines various build functions for building
targets from sources and custom parameters.

Performance note: this module is the entry point of the
``python -m blade.builtin_tools`` subprocess, spawned once per build action
(the hot one being ``cc_inclusion_check``, run per cc target). To keep that
startup cheap, heavier stdlib modules used only by cold tools (``fnmatch``,
``getpass``, ``socket``, ``subprocess``, ``tarfile``, ``zipfile``) are imported
lazily inside the functions that use them, each marked
``pylint: disable=import-outside-toplevel``. See issue #1159.
"""


import os
import pickle
import shutil
import subprocess
import sys
import textwrap
import traceback
import time

from blade import console
from blade import util


# These following helper functions is designed to centralize error handling


_outputs = []


def _declare_outputs(*outputs):
    """Declare output files, which can be verified after ran and cleanup on error."""
    _outputs[:] = outputs


def _verify_outputs():
    """Verify whether the declared output files were correctly generated."""
    missing = [o for o in _outputs if not os.path.exists(o)]
    if missing:
        raise FileNotFoundError('"%s" is not generated' % missing)


def _cleanup_outputs():
    """Cleanup declared output files on error."""
    console.debug('Cleanup:%s' % _outputs)
    for output in _outputs:
        try:
            os.remove(output)
        except OSError:
            pass


# The build functions are defined as follows form:
#
#    def build_function_name(kwargs..., args):
#        pass
#
#    Args:
#        * kwargs...: name=value pairs as parameters in command line
#        * args: any other non-kw args
#
#    Return:
#        Return None(include implicit return) or 0 on success, otherwise return
#        a positive int (e.g. 1) or raise an exception to indicate failure.
#
#    When call this from the command line, all arguments which match the
#    `--name=value` pattern will be converted into kwargs, any other arguments
#    are merged into the `args` argument. So any `name` must be a valid python
#    identifier.


def generate_scm(scm, revision, url, profile, compiler, args):
    """Generate `scm.c` file"""
    import getpass  # pylint: disable=import-outside-toplevel
    import socket  # pylint: disable=import-outside-toplevel

    _declare_outputs(scm)

    def _escape_c_str(s):
        return s.replace('\\', '\\\\')

    version = f'{url}@{revision}'
    with open(scm, 'w') as f:
        f.write(textwrap.dedent(r'''\
                /* This file was generated by blade */
                extern "C" {
                namespace binary_version {
                extern const int kSvnInfoCount = 1;
                extern const char* const kSvnInfo[] = {"%s\n"};
                extern const int kScmInfoCount = 1;
                extern const char* const kScmInfo[] = {"%s\n"};
                extern const char kBuildType[] = "%s";
                extern const char kBuildTime[] = "%s";
                extern const char kBuilderName[] = "%s";
                extern const char kHostName[] = "%s";
                extern const char kCompiler[] = "%s";
                }}''') % (_escape_c_str(version),
                          _escape_c_str(version),
                          profile,
                          time.asctime(),
                          getpass.getuser(),
                          socket.gethostname(),
                          _escape_c_str(compiler)))


def generate_cc_inclusion_check(args):
    # Import from function to avoid affecting the performance of other tools.
    from blade import inclusion_check  # pylint: disable=import-outside-toplevel
    result_file = args[0]
    info_file = args[1]
    _declare_outputs(result_file)
    console.set_log_file('%s.log' % info_file)
    console.enable_color(True)
    ok, details = inclusion_check.check(info_file)
    with open(info_file + '.details', 'wb') as f:
        pickle.dump(details, f)
    if not ok:
        return 1
    with open(result_file, 'w') as f:
        f.write('OK')
    return None


# --- cc_check_undefined: validate dep completeness without a shared link ---
#
# Implements the static counterpart of `-Wl,--no-undefined`. For a cc_library:
#   undefined externals from its .o files
#     - defined externals from the same .a (intra-archive)
#     - defined externals from each transitive cc_library dep's .a
#     - symbols defined by the toolchain's default-linked system libs and any
#       `#alias` system lib the target's transitive deps declare (read from
#       pre-generated .syms cache files; see blade.system_symbols)
#     - a tiny residue of compiler-injected / runtime-startup names not found
#       in any system library (e.g. the C++ Itanium guard variables emitted
#       by the compiler itself, or the macOS dyld TLV bootstrap stubs)
#     - user allow_undefined regex patterns
#   = unresolved set; non-empty -> error with suggestions.
#
# Cheap: one `nm -P -g` per archive, set arithmetic, regex fullmatch. No link.
# See issue #1225.

# Residual baseline: a tiny set of compiler-/linker-injected names that are
# NOT exported by any system library and would otherwise need user allowlist
# entries on every project. Everything else (libc, libm, libstdc++, libsystem,
# libpthread, libdl, dyld runtime, Objective-C runtime, ...) is enumerated
# from the actual installed libraries by blade.system_symbols and arrives
# at the check tool as ``.syms`` files alongside the dep archives.
_CHECK_UNDEFINED_RESIDUAL_BASELINE = (
    # ---- C++ Itanium ABI "string" symbols (typeinfo / vtable / VTT /
    # construction-vtable / guard variable / reference temporary / TLS-init).
    # These are emitted by the compiler against types that may live entirely
    # in user code, so they do NOT appear in libstdc++/libc++ exports.
    # _ZTI = typeinfo,  _ZTS = typeinfo name,  _ZTV = vtable,  _ZTT = VTT,
    # _ZTC = construction-vtable,  _ZTW/_ZTH = TLS init wrappers,
    # _ZGV = guard variable,  _ZGR/_ZGr = reference temporary.
    r'_?_ZT[ISVTCWH]\w*',
    r'_?_ZG[VRr]\w*',
    # ---- Mangled `operator new` / `operator delete` and array variants.
    # Provided by libstdc++/libc++ on shared platforms; on macOS the
    # libc++ stub list misses them and they're synthesized by the linker
    # from libc++abi. Keep them in the baseline so neither codepath needs
    # an explicit allowlist entry.
    r'_?_Z(?:nw|na|dl|da)[a-zA-Z0-9_]*',
    # ---- Compiler / linker injected names not exported by any lib ----
    r'_?__dso_handle',
    r'_?__cxx_global_(?:array|var)_init\w*',
    # ELF position-independent code: each PIC object references the GOT
    # via this magic symbol, which the static linker fills in per-binary
    # (it lives in no library's export table).
    r'_GLOBAL_OFFSET_TABLE_',
    # macOS Mach-O thread-local-variable bootstrap stubs (emitted into
    # objects but resolved by dyld at load time)
    r'_?_tlv_\w+',
    r'_?__tlv_\w+',
    # Linux ELF: the TLS general-dynamic / local-dynamic models emit calls
    # to ``__tls_get_addr`` (x86_64/arm64/...) or ``__tls_get_offset``
    # (s390x). These live in ``ld-linux*.so`` (the dynamic linker), not in
    # libc/libpthread, so blade.system_symbols does not enumerate them --
    # ``ld-linux`` is not a `-l<alias>` user code can spell. Always linked
    # implicitly because every dynamic executable runs through ld-linux.
    r'__tls_get_addr',
    r'__tls_get_offset',
)


def _check_undefined_compile_baseline():
    import re as _re
    return [_re.compile(p) for p in _CHECK_UNDEFINED_RESIDUAL_BASELINE]


def _dumpbin_extract_externals(dumpbin, archive):
    """Return (undefined, defined) external symbol sets for an MSVC ``.lib``.

    The MSVC analog of ``nm -P -g``. ``dumpbin /symbols`` prints one row per
    COFF symbol; the storage-class column reads ``External`` for externals and
    the section column is ``UNDEF`` for undefined references, anything else
    (``SECTn``, ``ABS``) for definitions. The raw (decorated) symbol name is the
    token right after ``|`` -- the trailing ``(demangled)`` comment is dropped,
    so names match what ``dumpbin /linkermember`` reports for the system libs.
    """
    try:
        out = subprocess.check_output([dumpbin, '/nologo', '/symbols', archive],
                                      stderr=subprocess.STDOUT)
    except subprocess.CalledProcessError as e:
        console.warning('dumpbin failed on %s (%s); treating as no symbols' % (archive, e))
        return set(), set()
    except OSError:  # FileNotFoundError ⊂ OSError
        console.error('cc_check_undefined: dumpbin not found')
        return set(), set()

    undefined, defined = set(), set()
    text = out.decode('utf-8', errors='replace')
    for raw in text.splitlines():
        if '|' not in raw:
            continue
        left, _, right = raw.partition('|')
        cols = left.split()
        # External symbol rows end the COFF columns with the storage class
        # 'External'; e.g. "008 00000000 UNDEF notype () External | name".
        if not cols or cols[-1] != 'External':
            continue
        name = right.strip().split(None, 1)[0] if right.strip() else ''
        if not name:
            continue
        section = cols[2] if len(cols) >= 3 else ''
        if section == 'UNDEF':
            undefined.add(name)
        else:
            defined.add(name)
    return undefined, defined


def _nm_extract_externals(archive, dumpbin=None):
    """Return (undefined_external, defined_external) sets for an archive.

    With ``dumpbin`` set (MSVC), defer to :func:`_dumpbin_extract_externals`
    since ``nm`` is unavailable and the inputs are COFF ``.lib`` archives.

    Runs `nm -P -g <archive>` once. -P selects POSIX format
    (`name type [value [size]]`), -g restricts to external symbols. Type
    letter encodes section: uppercase = defined external, U = undefined,
    w/v = weak undefined (treated as ambient -- linker allowed to leave
    them unresolved). The uppercase weak-defined variants (V/W) are real
    definitions emitted with vague linkage -- typically template static
    data (e.g. fmt's ``basic_data<void>::left_padding_shifts``) -- and
    must be counted as defined, or downstream cc_libraries that pull
    them in transitively will fail the undefined-symbol check.
    """
    if dumpbin:
        return _dumpbin_extract_externals(dumpbin, archive)
    try:
        out = subprocess.check_output(['nm', '-P', '-g', archive], stderr=subprocess.STDOUT)
    except subprocess.CalledProcessError as e:
        # nm exits non-zero when a static archive has no symbol table (e.g.
        # foreign_cc archives) — treat as empty. Same for missing files.
        console.warning('nm failed on %s (%s); treating as having no symbols' % (archive, e))
        return set(), set()
    except FileNotFoundError:
        console.error('cc_check_undefined: nm not found on PATH')
        return set(), set()

    undefined, defined = set(), set()
    text = out.decode('utf-8', errors='replace')
    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) < 2:
            continue
        name, ty = parts[0], parts[1]
        # GNU nm with -P also accepts an "<archive>[<member>]:" header line
        # (single column). Skip those.
        if ty.endswith(':'):
            continue
        if ty == 'U':
            undefined.add(name)
        elif ty in ('w', 'v'):
            # Lowercase 'w'/'v' = weak UNDEFINED -- linker is allowed to
            # leave them unresolved (resolved to 0 at runtime). Treat as
            # ambient. Note: uppercase 'V' / 'W' are weak DEFINED and fall
            # through to the isupper() / 'u' branches below.
            continue
        elif ty == 'u':
            # GNU extension: lowercase 'u' = unique global symbol. Despite
            # being lowercase (which usually means local in nm), 'u' is the
            # asymmetric counterpart of 'U' (undefined) -- it is GLOBAL and
            # DEFINED, used by C++ to guarantee one instance of template
            # static data across TUs. fmt's basic_data<void> members
            # (left_padding_shifts etc.) are emitted as 'u' on gcc/Linux.
            defined.add(name)
        elif ty.isupper():
            # Any other uppercase letter: defined external symbol.
            defined.add(name)
        # Remaining lowercase letters are local, ignore.
    return undefined, defined


def _read_allow_undefined_file(path):
    if not path:
        return []
    patterns = []
    with open(path, encoding='utf-8') as f:
        for raw in f:
            line = raw.strip()
            if line and not line.startswith('#'):
                patterns.append(line)
    return patterns


def _read_syms_cache(path):
    """Read defined symbols from a system-symbols cache file written by
    blade.system_symbols. Header lines (``#``-prefixed) are skipped.

    Kept for the system-symbols path, where the cache is defined-only.
    For archive .syms files (which carry both undefined and defined sets),
    use :func:`_read_archive_syms`.
    """
    try:
        with open(path, encoding='utf-8') as f:
            return {line.rstrip() for line in f
                    if line.strip() and not line.startswith('#')}
    except OSError:
        return set()


def _read_archive_syms(path):
    """Parse a per-archive .syms file written by :func:`generate_cc_emit_syms`.

    Format: ``#`` header lines (metadata), then a ``#U`` section listing the
    archive's undefined externals, then a ``#D`` section listing its defined
    externals. Returns ``(undefined_set, defined_set)``.

    Backwards compatible: if no ``#U`` section is present (e.g. a legacy
    system-symbols cache) every symbol line is treated as defined.
    """
    undefined: set[str] = set()
    defined: set[str] = set()
    section = defined  # default: legacy "defined-only" caches
    try:
        with open(path, encoding='utf-8') as f:
            for raw in f:
                line = raw.rstrip()
                if not line:
                    continue
                if line == '#U':
                    section = undefined
                    continue
                if line == '#D':
                    section = defined
                    continue
                if line.startswith('#'):
                    continue
                section.add(line)
    except OSError:
        pass
    return undefined, defined


def generate_cc_emit_syms(args, dumpbin=None, **_opts):
    """Run ``nm`` on a static archive once and emit its symbol-set cache.

    Args:
        args: ``[<output.syms>, <input.a>]``
        dumpbin: path to ``dumpbin.exe`` (passed as ``--dumpbin=<path>`` by the
            ``ccsyms`` rule on MSVC); when set, symbols are read with dumpbin
            instead of ``nm`` (the archives are COFF ``.lib`` files).

    Writes ``output.syms`` with two sections: ``#U`` (undefined externals)
    and ``#D`` (defined externals). This collapses what the check tool used
    to do per-(target × dep) into a per-archive O(N) precompute -- each
    archive is nm'd exactly once, regardless of how many cc_libraries
    depend on it. See issue #1225.
    """
    out_path = args[0]
    archive = args[1]
    _declare_outputs(out_path)
    undef, defd = _nm_extract_externals(archive, dumpbin=dumpbin)
    tmp = out_path + '.tmp'
    os.makedirs(os.path.dirname(tmp), exist_ok=True)
    with open(tmp, 'w', encoding='utf-8') as f:
        f.write('# blade archive-symbols cache v1\n')
        f.write('# archive: %s\n' % archive)
        f.write('#U\n')
        for s in sorted(undef):
            f.write(s); f.write('\n')
        f.write('#D\n')
        for s in sorted(defd):
            f.write(s); f.write('\n')
    os.replace(tmp, out_path)
    return None


def generate_cc_check_undefined(args, **opts):
    """Check that a cc_library's deps cover all its undefined symbols.

    Args:
        args: ``[<result_file>, <target.a.syms>, <dep.syms>...]``
              The first input is the target's own archive .syms (carrying
              both undefined and defined sets). Each subsequent input is
              another .syms cache: either a transitive cc_library dep's
              archive .syms (also dual-section), or a system-library
              symbols cache (defined-only). :func:`_read_archive_syms`
              handles both shapes transparently.
        opts: --allow-file=<path>  one regex pattern per line (target + global)
              --target-label=<label>  for nicer error messages

    Exits non-zero with a diagnostic listing unresolved symbols when missing
    deps are found. Writes a one-line marker to result_file on success so
    ninja can use it as a downstream dependency.

    This step is purely file reads + set arithmetic + regex match -- the
    actual ``nm`` work for each archive happens once at archive build time
    (see :func:`generate_cc_emit_syms`) and is reused across every
    cc_library that depends on it. The earlier implementation re-ran ``nm``
    on every dep for every check, which was O(N²) in the dep graph.
    """
    import re as _re  # pylint: disable=import-outside-toplevel
    result_file = args[0]
    target_syms = args[1]
    rest = args[2:]
    _declare_outputs(result_file)

    allow_file = opts.get('allow-file', '')
    target_label = opts.get('target-label', target_syms)

    user_patterns = _read_allow_undefined_file(allow_file)
    compiled = _check_undefined_compile_baseline()
    for p in user_patterns:
        try:
            compiled.append(_re.compile(p))
        except _re.error as e:
            console.error('cc_check_undefined(%s): invalid allow_undefined regex %r: %s'
                          % (target_label, p, e))
            return 1

    undef, defd = _read_archive_syms(target_syms)
    unresolved = undef - defd  # intra-archive resolved subtracted

    # Subtract symbols defined by each dep .syms file. Order doesn't matter
    # for correctness; we break early once the unresolved set is empty.
    for cache in rest:
        _, dep_defined = _read_archive_syms(cache)
        unresolved -= dep_defined
        if not unresolved:
            break

    if unresolved:
        # Apply residual baseline + user allowlist regex last.
        unresolved = {s for s in unresolved
                      if not any(p.fullmatch(s) for p in compiled)}

    if unresolved:
        console.error('cc_check_undefined: %s has %d undefined symbol(s) not covered '
                      'by declared deps:' % (target_label, len(unresolved)))
        # Show at most the first 50 so the log stays readable.
        for s in sorted(unresolved)[:50]:
            console.error('  %s' % s)
        if len(unresolved) > 50:
            console.error('  ... and %d more' % (len(unresolved) - 50))
        console.error('Add the providing cc_library (or #syslib) to deps, or '
                      'whitelist with allow_undefined=[regex] / cc_library_config.allow_undefined.')
        return 1

    with open(result_file, 'w', encoding='utf-8') as f:
        f.write('OK\n')
    return None


def generate_cc_check_undefined_batch(args, severity='error', **_opts):
    """Project-wide variant of :func:`generate_cc_check_undefined`.

    Runs the static undefined-symbol check for every cc_library in the
    project in a single Python process. The previous per-target ninja
    rule paid one Python-interpreter startup per cc_library (each
    spawning ``python -m blade.builtin_tools cc_check_undefined ...``);
    on a real codebase that was the dominant cost of the check phase.
    Collapsing into one batch eliminates ~N interpreter startups in
    exchange for losing per-target ninja parallelism -- a win on real
    workloads because the check is a sidecar (no ninja node depends on
    each per-target result) and individual checks are tiny once the
    .syms cache is populated.

    Args:
        args: ``[<batch_stamp>, <manifest.json>]``
        severity: ``'warning'`` (project default while the check is
            experimental) logs findings via console.warning and still
            writes the stamp so the build keeps going. ``'error'`` fails
            the build on any finding. Anything else falls back to
            ``'error'`` (defensive: an unknown severity is closer to "be
            strict" than "be silent").

    On severity=``'error'``, exits non-zero (and writes nothing) when any
    spec fails. The stamp is always written on the warning path so a
    later incremental invocation can short-circuit if no inputs changed.
    """
    import json as _json  # pylint: disable=import-outside-toplevel
    import re as _re  # pylint: disable=import-outside-toplevel
    stamp_file = args[0]
    manifest_path = args[1]
    _declare_outputs(stamp_file)

    with open(manifest_path, encoding='utf-8') as f:
        specs = _json.load(f)

    # Cache nm output across the whole batch: a typical archive (e.g.
    # libcommon.a) is a dep of dozens of targets, so reading its .syms
    # file once and reusing the parsed sets saves substantial work.
    syms_cache: dict[str, tuple[set[str], set[str]]] = {}

    def _syms(path):
        cached = syms_cache.get(path)
        if cached is not None:
            return cached
        cached = _read_archive_syms(path)
        syms_cache[path] = cached
        return cached

    allow_cache: dict[str, list] = {}

    def _allow(path):
        compiled = allow_cache.get(path)
        if compiled is not None:
            return compiled
        compiled = _check_undefined_compile_baseline()
        for p in _read_allow_undefined_file(path):
            try:
                compiled.append(_re.compile(p))
            except _re.error as e:
                console.error('cc_check_undefined: invalid allow_undefined regex %r in %s: %s'
                              % (p, path, e))
                # Don't fail the whole batch on one bad regex; just
                # skip the offending pattern.
        allow_cache[path] = compiled
        return compiled

    # `severity` is the project-global diagnostic level. We resolve it once to
    # the matching console.{warning,error} bound method so the per-target loop
    # below doesn't keep re-branching.
    log = console.warning if severity == 'warning' else console.error
    failed = 0
    for spec in specs:
        target_label = spec['target_label']
        compiled = _allow(spec['allow_file'])
        undef, defd = _syms(spec['target_syms'])
        unresolved = undef - defd
        for cache in spec['dep_syms']:
            _, dep_defined = _syms(cache)
            unresolved -= dep_defined
            if not unresolved:
                break
        if unresolved:
            for cache in spec['sys_caches']:
                _, dep_defined = _syms(cache)
                unresolved -= dep_defined
                if not unresolved:
                    break
        if unresolved:
            unresolved = {s for s in unresolved
                          if not any(p.fullmatch(s) for p in compiled)}
        if unresolved:
            failed += 1
            log('cc_check_undefined: %s has %d undefined symbol(s) not covered '
                'by declared deps:' % (target_label, len(unresolved)))
            for s in sorted(unresolved)[:50]:
                log('  %s' % s)
            if len(unresolved) > 50:
                log('  ... and %d more' % (len(unresolved) - 50))

    if failed:
        log('cc_check_undefined: %d target(s) failed; add the providing '
            'cc_library (or #syslib) to deps, or whitelist with '
            'allow_undefined=[regex] / cc_library_config.allow_undefined.'
            % failed)
        if severity != 'warning':
            return 1

    os.makedirs(os.path.dirname(stamp_file), exist_ok=True)
    with open(stamp_file, 'w', encoding='utf-8') as f:
        f.write('OK\n')
    return None


# --- Windows DLL auto-export: synthesize a .def from object files ----------
#
# To make a Windows DLL export its symbols without `__declspec(dllexport)`
# annotations, we parse the COFF object files directly (pure stdlib `struct`,
# the same approach as CMake's bindexplib / Bazel's def_parser) and emit a
# `.def`. Unlike those tools, we *filter out the dedup COMDAT symbols* —
# template instantiations, inline functions, string/float constants, vtables,
# RTTI — which the consumer always instantiates itself from headers and never
# needs to import. That keeps the export table small (the naive "export all"
# is what makes WINDOWS_EXPORT_ALL_SYMBOLS blow the 64k export limit on
# template-heavy C++).
#
# The discriminator is the COMDAT *selection*, not merely "is COMDAT": under
# /Gy (on at /O2) even ordinary functions become COMDAT, but with selection
# NODUPLICATES (a unique definition) — those we keep. The dedup selections
# (ANY / SAME_SIZE / EXACT_MATCH / LARGEST) are the header-provided copies we
# drop. See blade-build/blade-build#1181.

_IMAGE_SYM_CLASS_EXTERNAL = 2
_IMAGE_SYM_CLASS_STATIC = 3
_IMAGE_SYM_DTYPE_FUNCTION = 0x20  # Type high nibble == FUNCTION
# COMDAT selection values that mean "duplicates are expected and folded" — the
# symbol is provided by every TU that uses it, so the DLL needn't export it.
_COMDAT_DEDUP_SELECTIONS = frozenset((2, 3, 4, 6))


def _select_dll_exports(symbols, section_selection):
    """Pick the symbols a DLL should export, from parsed COFF symbol records.

    ``symbols`` is a list of ``(name, storage_class, section_number, coff_type)``
    and ``section_selection`` maps a section number to its COMDAT selection
    (0 / absent = not COMDAT). Returns an ordered, de-duplicated list of
    ``(name, is_data)``.

    A symbol is exported when it is **external** and **defined here**
    (``section_number > 0``) and its section is not a *dedup* COMDAT. Functions
    (COFF type FUNCTION) are exported plain; everything else is data and gets
    the ``DATA`` keyword in the `.def`.
    """
    seen = {}
    for name, storage_class, section_number, coff_type in symbols:
        if storage_class != _IMAGE_SYM_CLASS_EXTERNAL or section_number <= 0:
            continue
        if section_selection.get(section_number, 0) in _COMDAT_DEDUP_SELECTIONS:
            continue
        if not name:
            continue
        is_data = coff_type != _IMAGE_SYM_DTYPE_FUNCTION
        seen.setdefault(name, is_data)  # first definition wins
    return list(seen.items())


# --- export_map (GNU-ld version script) filtering on MSVC ------------------
#
# `export_map` is a GNU-ld `--version-script`; MSVC has no equivalent. To honor
# it on Windows we filter the auto-`.def` (above) through the map: keep only
# symbols matched by a `global:` pattern (and not hidden by `local:`).
#
# Version-script patterns are written against Itanium-demangled names; MSVC
# symbols are decorated differently, so we demangle each candidate with
# `UnDecorateSymbolName(UNDNAME_NAME_ONLY)`, which yields just the qualified
# name (e.g. `mylib::Api::Greet`). That matches `extern "C++"` globs like
# `mylib::Api::*` well, but it drops the signature -- so overloads collapse to
# one name and quoted signature patterns (`"mylib::Create()"`) are matched by
# their name part only. See blade-build#1194.

_UNDNAME_NAME_ONLY = 0x1000
_undname_fn = None


def _undecorate_name_only(symbol):
    """Return the MSVC symbol's demangled qualified name (no signature).

    Windows-only (uses dbghelp). For a non-decorated name (e.g. an `extern "C"`
    symbol) UnDecorateSymbolName returns it unchanged. Falls back to the raw
    symbol if demangling is unavailable or fails.
    """
    global _undname_fn  # pylint: disable=global-statement
    if _undname_fn is None:
        import ctypes  # pylint: disable=import-outside-toplevel
        from ctypes import wintypes  # pylint: disable=import-outside-toplevel
        fn = ctypes.WinDLL('dbghelp').UnDecorateSymbolName
        fn.argtypes = [wintypes.LPCSTR, wintypes.LPSTR, wintypes.DWORD, wintypes.DWORD]
        fn.restype = wintypes.DWORD
        _undname_fn = fn
    import ctypes  # pylint: disable=import-outside-toplevel
    buf = ctypes.create_string_buffer(4096)
    n = _undname_fn(symbol.encode('ascii', 'replace'), buf, 4096, _UNDNAME_NAME_ONLY)
    return buf.value.decode('ascii', 'replace') if n else symbol


def _parse_export_map(path):
    """Parse a GNU-ld version script into (global_patterns, local_patterns).

    Each pattern is ``(text, is_cpp, is_quoted)``: ``is_cpp`` marks patterns
    inside an ``extern "C++"`` block (matched against the demangled name);
    ``is_quoted`` marks a quoted literal (no wildcards). Comments (``#``,
    ``//``, ``/* */``), version-node names and ``extern "C"`` blocks are
    handled; named version tags are flattened (their global/local patterns are
    unioned -- on PE there is no symbol versioning, only export filtering).
    """
    import re  # pylint: disable=import-outside-toplevel
    with open(path, encoding='utf-8') as f:
        text = f.read()
    text = re.sub(r'/\*.*?\*/', ' ', text, flags=re.S)
    text = re.sub(r'(?:#|//).*', ' ', text)
    tokens = re.findall(r'"[^"]*"|[{};]|(?:global|local)\s*:|extern|[^\s{};]+', text)

    globals_, locals_ = [], []
    section = None
    cpp_stack = [False]
    pending_extern = False
    pending_lang = None
    for tok in tokens:
        if tok in ('{', '}'):
            if tok == '{':
                cpp = (pending_lang == 'C++') if pending_extern else cpp_stack[-1]
                cpp_stack.append(cpp)
            else:  # '}'
                if len(cpp_stack) > 1:
                    cpp_stack.pop()
                if len(cpp_stack) == 1:
                    # Closed a version node: the next token (a named-version tag
                    # like `VER_2`, or a `} VER_1;` dependency) must not be read
                    # as a pattern under the previous node's section.
                    section = None
            pending_extern, pending_lang = False, None
        elif tok == ';':
            continue
        elif tok.rstrip().rstrip(':') in ('global', 'local') and tok.endswith(':'):
            section = tok.rstrip().rstrip(':')
        elif tok == 'extern':
            pending_extern = True
        elif pending_extern and tok.startswith('"'):
            pending_lang = tok.strip('"')
        else:
            quoted = tok.startswith('"')
            pat = tok.strip('"') if quoted else tok
            if not pat:
                continue
            entry = (pat, cpp_stack[-1], quoted)
            if section == 'global':
                globals_.append(entry)
            elif section == 'local':
                locals_.append(entry)
    return globals_, locals_


def _export_map_match(patterns, name, dname):
    """True if `name` (raw) / `dname` (demangled name-only) matches a pattern."""
    import fnmatch  # pylint: disable=import-outside-toplevel
    for pat, is_cpp, quoted in patterns:
        target = dname if is_cpp else name
        if quoted:
            # Name-only demangling drops the signature, so match the pattern's
            # name part (everything before '(') exactly. Overloads collapse.
            if target == pat.split('(', 1)[0]:
                return True
        elif fnmatch.fnmatchcase(target, pat):
            return True
    return False


def _export_map_keeps(name, dname, globals_, locals_):
    """Version-script export decision: keep iff `global`, else drop if `local`.

    A symbol matched by a `global:` pattern is exported (a specific global wins
    over a wildcard `local: *`). Otherwise it is hidden when any `local:`
    pattern matches it -- which includes the usual `local: *;` catch-all. With
    no `local:` section the map does not restrict exports.
    """
    if _export_map_match(globals_, name, dname):
        return True
    return not _export_map_match(locals_, name, dname)


def _filter_exports_by_map(seen, export_map):
    """Filter the auto-export `seen` dict through an export_map version script."""
    globals_, locals_ = _parse_export_map(export_map)
    if any(quoted for _, _, quoted in globals_ + locals_):
        console.warning(
            'cc_windef: %s: quoted signature patterns are matched by name only '
            'on MSVC (UnDecorateSymbolName has no Itanium signature); overloads '
            'are not distinguished.' % export_map)
    kept = {}
    for name, is_data in seen.items():
        dname = _undecorate_name_only(name)
        if _export_map_keeps(name, dname, globals_, locals_):
            kept[name] = is_data
    return kept


# --- export_map (GNU-ld version script) filtering on macOS ----------------
#
# Apple's ld64 understands neither `--version-script` nor a syntactically
# equivalent option; its native `-exported_symbols_list` takes a plain list
# of mangled symbol names (one per line, with the Mach-O leading underscore
# preserved). Translation: enumerate each .o's defined+external symbols via
# `nm -gU -P`, demangle each via libc++abi's `__cxa_demangle`, match the
# script's globals/locals against the demangled name-only form (everything
# before the first `(` -- mirrors the MSVC path's name-only matching), then
# emit the matching MANGLED symbol names back out.
#
# Same limitations as the MSVC path:
# * Overloads collapse (name-only matching cannot distinguish them).
# * Quoted signature patterns (`"f(int)"`) match by their name part only;
#   a one-time warning is emitted when such patterns are present.

# Split into "probed?" + "result of probing" so the function-pointer slot
# only ever holds None or the loaded callable -- pyright can then narrow it
# correctly after the `is None` check below.
_macos_cxa_demangle_fn = None
_macos_cxa_demangle_probed = False


def _macos_cxa_demangle(symbol):
    """Demangle an Itanium C++ symbol via libc++abi. Returns None if not C++."""
    global _macos_cxa_demangle_fn, _macos_cxa_demangle_probed  # pylint: disable=global-statement
    if not _macos_cxa_demangle_probed:
        import ctypes  # pylint: disable=import-outside-toplevel
        # libc++abi is part of every macOS install since 10.7. Try the
        # canonical name first; fall back through likely aliases. If none
        # are loadable, leave _fn as None and degrade to raw symbols.
        for libname in ('libc++abi.dylib', 'libc++.1.dylib'):
            try:
                lib = ctypes.CDLL(libname)
                fn = lib.__cxa_demangle  # type: ignore[attr-defined]
            except (OSError, AttributeError):
                continue
            fn.argtypes = [ctypes.c_char_p, ctypes.c_void_p,
                           ctypes.POINTER(ctypes.c_size_t),
                           ctypes.POINTER(ctypes.c_int)]
            fn.restype = ctypes.c_void_p
            _macos_cxa_demangle_fn = fn
            break
        _macos_cxa_demangle_probed = True
    if _macos_cxa_demangle_fn is None:
        return None

    import ctypes  # pylint: disable=import-outside-toplevel
    status = ctypes.c_int(0)
    length = ctypes.c_size_t(0)
    result_ptr = _macos_cxa_demangle_fn(
        symbol.encode('ascii', 'replace'),
        None, ctypes.byref(length), ctypes.byref(status))
    if status.value != 0 or not result_ptr:
        return None
    try:
        return ctypes.string_at(result_ptr).decode('utf-8', 'replace')
    finally:
        # __cxa_demangle returns a malloc'd buffer; the caller must free it.
        libc = ctypes.CDLL(None)
        libc.free.argtypes = [ctypes.c_void_p]
        libc.free(result_ptr)


def _macos_demangle_name_only(stripped_symbol):
    """Demangle and drop the parameter signature.

    Mirrors MSVC's ``UnDecorateSymbolName(UNDNAME_NAME_ONLY)``: for
    ``mylib::Greet(int)`` returns ``mylib::Greet`` -- the form that
    ``ns::class::method`` patterns in the export_map are written against.
    """
    dname = _macos_cxa_demangle(stripped_symbol)
    if dname is None:
        return stripped_symbol  # Not a C++ mangled name; treat as extern "C".
    return dname.split('(', 1)[0]


def _macos_obj_global_symbols(obj_path):
    """List defined+external symbols of a Mach-O object via ``nm -gU -P``.

    Output format: ``<name> <type> <value> <size>``. ``-g`` filters to
    globals, ``-U`` drops undefined imports. We keep only data/text/bss/
    rodata types -- the things a linker would actually consider exporting.
    """
    import subprocess  # pylint: disable=import-outside-toplevel
    out = subprocess.check_output(['nm', '-gU', '-P', obj_path], text=True)
    syms = []
    for line in out.splitlines():
        parts = line.split()
        # `-P` lines look like "<name> <type>"; some BSD nm builds may emit
        # a single-column form when the symbol has no value -- skip those.
        if len(parts) >= 2 and parts[1] in ('T', 'D', 'S', 'B', 'R'):
            syms.append(parts[0])
    return syms


def _write_if_changed(path, content):
    """Write ``content`` to ``path`` only when it differs from the on-disk
    bytes; preserves mtime for unchanged outputs so ninja's ``restat`` can
    prune dependent edges (here, the actual link)."""
    try:
        with open(path, 'rb') as f:
            if f.read() == content:
                return
    except FileNotFoundError:
        pass
    with open(path, 'wb') as f:
        f.write(content)


def generate_macos_exports(args):
    """Generate an ld64 ``-exported_symbols_list`` from .o + export_map.

    Invoked as ``cc_macos_exports <output> <export_map> <obj>...``. Writes a
    file with one mangled symbol per line (including the Mach-O ``_`` prefix).
    A symbol is kept iff it matches the export_map's ``global:`` set (and is
    not hidden by ``local:`` -- e.g. the usual ``local: *;`` catch-all).
    """
    output, export_map_path = args[0], args[1]
    objs = args[2:]
    _declare_outputs(output)
    globals_, locals_ = _parse_export_map(export_map_path)
    if any(quoted for _, _, quoted in globals_ + locals_):
        console.warning(
            'cc_macos_exports: %s: quoted signature patterns are matched by '
            'name only on macOS (Itanium __cxa_demangle output is split at '
            'the first "("); overloads collapse.' % export_map_path)

    kept = set()
    for obj in objs:
        for raw in _macos_obj_global_symbols(obj):
            # Mach-O symbols start with `_`; strip for demangling, keep the
            # original for output (ld64 -exported_symbols_list expects the
            # underscore form).
            stripped = raw[1:] if raw.startswith('_') else raw
            dname = _macos_demangle_name_only(stripped)
            if _export_map_keeps(stripped, dname, globals_, locals_):
                kept.add(raw)

    lines = ['# Generated by Blade from %s\n' % os.path.basename(export_map_path)]
    for sym in sorted(kept):
        lines.append(sym + '\n')
    _write_if_changed(output, ''.join(lines).encode('utf-8'))


def _parse_coff(data):
    """Parse a COFF object file's symbol table (pure stdlib `struct`).

    Returns ``(symbols, section_selection)`` as consumed by
    :func:`_select_dll_exports`. Raises ``NotImplementedError`` for the
    "bigobj" variant (used only by objects with > 65279 sections), which the
    caller should surface as an actionable error.
    """
    import struct  # pylint: disable=import-outside-toplevel
    machine, = struct.unpack_from('<H', data, 0)
    sig2, = struct.unpack_from('<H', data, 2)
    if machine == 0 and sig2 == 0xFFFF:
        raise NotImplementedError('bigobj COFF object is not supported')
    # IMAGE_FILE_HEADER: skip to symbol-table pointer / count.
    _num_sections, _ts, sym_off, num_syms = struct.unpack_from('<HIII', data, 2)
    strtab_off = sym_off + num_syms * 18

    def read_name(name8):
        if name8[:4] == b'\x00\x00\x00\x00':
            off, = struct.unpack('<I', name8[4:8])
            end = data.index(b'\x00', strtab_off + off)
            return data[strtab_off + off:end].decode('latin-1')
        return name8.rstrip(b'\x00').decode('latin-1')

    symbols = []
    section_selection = {}
    i = 0
    while i < num_syms:
        rec = sym_off + i * 18
        name8 = data[rec:rec + 8]
        value, secnum, ctype, sclass, naux = struct.unpack_from('<IhHBB', data, rec + 8)
        # A section-definition symbol (Static, type NULL, value 0, one aux)
        # carries the COMDAT selection of its section in that aux record.
        if (sclass == _IMAGE_SYM_CLASS_STATIC and ctype == 0 and value == 0
                and naux >= 1 and secnum > 0):
            selection, = struct.unpack_from('<B', data, rec + 18 + 14)
            section_selection[secnum] = selection
        elif sclass == _IMAGE_SYM_CLASS_EXTERNAL:
            symbols.append((read_name(name8), sclass, secnum, ctype))
        i += 1 + naux
    return symbols, section_selection


def generate_cc_windef(args, export_map=None):
    """Generate a `.def` exporting the symbols of the given objects (Windows).

    Invoked as ``cc_windef [--export_map=<file>] <output.def> <obj>...``. Parses
    each object's COFF symbol table directly and writes the filtered export
    list. When ``--export_map`` is given, the auto-export set is further
    filtered through that GNU-ld version script (matched by demangled name).
    """
    output = args[0]
    objs = args[1:]
    _declare_outputs(output)
    seen = {}
    for obj in objs:
        with open(obj, 'rb') as f:
            data = f.read()
        try:
            symbols, section_selection = _parse_coff(data)
        except NotImplementedError as e:
            console.error('cc_windef: %s: %s. Use an export_map or '
                          'generate_dynamic=False for this target.' % (obj, e))
            return 1
        for name, is_data in _select_dll_exports(symbols, section_selection):
            seen.setdefault(name, is_data)
    if export_map:
        seen = _filter_exports_by_map(seen, export_map)
    lines = ['EXPORTS']
    lines += ['    %s%s' % (name, ' DATA' if is_data else '') for name, is_data in seen.items()]
    # Write-if-changed: keep the .def's mtime when the export set is unchanged.
    # Otherwise every build rewrites it, making it newer than the import library
    # (which link.exe does NOT rewrite when exports are unchanged), so `solink`
    # would relink the DLL on every build. Paired with restat on the cc_windef /
    # solink rules. See the incremental-build fix.
    util.write_if_changed(output, '\n'.join(lines) + '\n')
    return None


_PACKAGE_MANIFEST = 'MANIFEST.TXT'


def archive_package_sources(package, sources, destinations):
    """Content of the `MANIFEST.TXT` file in the target zip file"""
    manifest = []
    for i, s in enumerate(sources):
        package(s, destinations[i])
        manifest.append(f'{util.md5sum_file(s)} {destinations[i]}')
    return manifest


def generate_zip_package(path, sources, destinations):
    import zipfile  # pylint: disable=import-outside-toplevel
    zip = zipfile.ZipFile(path, 'w', zipfile.ZIP_DEFLATED, allowZip64=True)
    manifest = archive_package_sources(zip.write, sources, destinations)
    zip.writestr(_PACKAGE_MANIFEST, '\n'.join(manifest) + '\n')
    zip.close()


def generate_tar_package(path, sources, destinations, mode):
    import tarfile  # pylint: disable=import-outside-toplevel
    tar = tarfile.open(path, mode, dereference=True)
    manifest = archive_package_sources(tar.add, sources, destinations)
    manifest_path = '%s.MANIFEST' % path
    with open(manifest_path, 'w') as m:
        m.write('\n'.join(manifest) + '\n\n')
    tar.add(manifest_path, _PACKAGE_MANIFEST)
    tar.close()


_TAR_WRITE_MODES = {
    'tar': 'w',
    'tar.gz': 'w:gz',
    'tgz': 'w:gz',
    'tar.bz2': 'w:bz2',
    'tbz': 'w:bz2',
}


def _tar_write_mode(path):
    """Get the tar write mode from extname of path"""
    for ext, mode in _TAR_WRITE_MODES.items():
        if path.endswith(ext):
            return mode
    return ''


def generate_package(args):
    path = args[0]
    manifest = args[1:]
    _declare_outputs(path)
    assert len(manifest) % 2 == 0
    middle = len(manifest) // 2
    sources = manifest[:middle]
    destinations = manifest[middle:]
    if path.endswith('.zip'):
        generate_zip_package(path, sources, destinations)
    else:
        mode = _tar_write_mode(path)
        generate_tar_package(path, sources, destinations, mode)


def _generate_resource_index(targets, sources, name, path):
    """Generate resource index description file for a cc resource library"""
    header, source = targets
    # Normalize to forward slashes for use in C code (identifiers, strings, includes)
    header_fwd = util.to_unix_path(header)
    with open(header, 'w') as h, open(source, 'w') as c:
        full_name = util.regular_variable_name(os.path.join(path, name))
        guard_name = 'BLADE_RESOURCE_%s_H_' % full_name.upper()
        index_name = 'RESOURCE_INDEX_%s' % full_name

        h.write(textwrap.dedent('''\
                // This file was automatically generated by blade
                #ifndef {0}
                #define {0}

                #ifdef __cplusplus
                extern "C" {{
                #endif

                #ifndef BLADE_RESOURCE_TYPE_DEFINED
                #define BLADE_RESOURCE_TYPE_DEFINED
                struct BladeResourceEntry {{
                    const char* name;
                    const char* data;
                    unsigned int size;
                }};
                #endif''').format(guard_name))
        # `retain` (GCC 11+ / Clang 13+) keeps the section under `--gc-sections`
        # even when consumers reach the index only via a string lookup that the
        # linker can't see. `used` is the older compiler-side fallback (prevents
        # the symbol from being dropped at codegen but doesn't bind the linker).
        # Older compilers silently accept neither, so the combined annotation is
        # safe to emit unconditionally behind feature detection.
        #
        # Note: does NOT solve the static-archive pull-in problem (the linker
        # won't pull an unreferenced archive member regardless). For that,
        # consumers still need to reference the index header textually or
        # build the resource library with `link_all_symbols = True`.
        c.write(textwrap.dedent('''\
                // This file was automatically generated by blade
                #include "{0}"

                #ifdef __has_attribute
                #  if __has_attribute(retain)
                #    define BLADE_RESOURCE_KEEP __attribute__((retain, used))
                #  elif __has_attribute(used)
                #    define BLADE_RESOURCE_KEEP __attribute__((used))
                #  else
                #    define BLADE_RESOURCE_KEEP
                #  endif
                #else
                #  define BLADE_RESOURCE_KEEP
                #endif

                BLADE_RESOURCE_KEEP
                const struct BladeResourceEntry {1}[] = {{''').format(header_fwd, index_name))

        for s in sources:
            entry_var = util.regular_variable_name(s)
            entry_name = util.to_unix_path(os.path.relpath(s, path))
            entry_size = os.path.getsize(s)
            h.write('// %s\n' % entry_name)
            h.write('extern const char RESOURCE_%s[%d];\n' % (entry_var, entry_size))
            h.write('extern const unsigned RESOURCE_%s_len;\n' % entry_var)
            c.write(f'    {{ "{entry_name}", RESOURCE_{entry_var}, {entry_size} }},\n')

        c.write(textwrap.dedent('''\
                }};
                BLADE_RESOURCE_KEEP
                const unsigned {0}_len = {1};''').format(index_name, len(sources)))
        # MSVC analogue of GCC's `retain` -- and strictly stronger, because it
        # also forces static-archive pull-in. The `#pragma comment(linker,
        # "/INCLUDE:foo")` directive is embedded into every consumer .obj that
        # includes this header; the linker then requires `foo` to be defined,
        # so an unreferenced archive member that defines it gets pulled in.
        # `retain` on GCC operates after archive selection, so the GCC fallback
        # for that case is still `link_all_symbols = True`.
        #
        # Symbol decoration: C symbols carry a leading underscore on x86
        # (`__cdecl`); x86_64 / arm64 keep the bare name. The x86 branch is
        # rarely used these days but is essentially free to retain.
        h.write(textwrap.dedent('''\
                // Resource index
                extern const struct BladeResourceEntry {0}[];
                extern const unsigned {0}_len;

                #ifdef _MSC_VER
                #  ifdef _M_IX86
                #    pragma comment(linker, "/INCLUDE:_{0}")
                #    pragma comment(linker, "/INCLUDE:_{0}_len")
                #  else
                #    pragma comment(linker, "/INCLUDE:{0}")
                #    pragma comment(linker, "/INCLUDE:{0}_len")
                #  endif
                #endif

                #ifdef __cplusplus
                }}  // extern "C"
                #endif

                #endif  // {1}''').format(index_name, guard_name))


def generate_resource_index(args):
    name, path = args[0], args[1]
    targets = args[2], args[3]
    sources = args[4:]
    _declare_outputs(*targets)
    return _generate_resource_index(targets, sources, name, path)


def generate_resource(args):
    """Convert a file to a C byte array (replaces xxd -i | sed)."""
    output = args[0]
    inputs = args[1:]
    _declare_outputs(output)
    return _generate_c_resource(inputs, output)


def _generate_c_resource(inputs, output):
    """Generate a C source file from binary resource files.

    Emits ``const char RESOURCE_<name>[]`` with hex byte data and
    ``const unsigned int RESOURCE_<name>_len`` for each input file.
    """
    parts = []
    for input_file in inputs:
        with open(input_file, 'rb') as f:
            data = f.read()
        var_name = util.regular_variable_name(input_file)
        parts.append(f'const char RESOURCE_{var_name}[] = {{')
        for i in range(0, len(data), 12):
            chunk = data[i:i + 12]
            hex_bytes = ', '.join(f'0x{b:02x}' for b in chunk)
            parts.append(f'  {hex_bytes}{"," if i + 12 < len(data) else ""}')
        parts.append('};')
        parts.append(f'const unsigned int RESOURCE_{var_name}_len = {len(data)};')
        parts.append('')
    with open(output, 'w') as f:
        f.write('\n'.join(parts))
        f.write('\n')


def generate_javac_compile(args):
    """Compile Java sources and create a jar file.

    Arguments are positional:
        classes_dir  output_jar  source_encoding  classpath  [javacflags...] -- [sources...]

    The ``--`` sentinel separates javac flags from source files so that
    multi-word Ninja variables (``${javacflags}``, ``${in}``) can be
    unpacked unambiguously.
    """
    import subprocess  # pylint: disable=import-outside-toplevel
    sep = args.index('--')
    classes_dir = args[0]
    output = args[1]
    source_encoding = args[2]
    classpath = args[3]
    javacflags = args[4:sep]
    sources = args[sep + 1:]

    _declare_outputs(output)
    shutil.rmtree(classes_dir, ignore_errors=True)
    os.makedirs(classes_dir, exist_ok=True)

    # A source input may be a `.srcjar` (a jar of generated `.java`, e.g. from
    # proto_library) rather than a plain `.java` file. javac can't compile a
    # srcjar directly, so extract its `.java` and compile those. This is how
    # we support an unpredictable generated-source set (e.g. proto
    # `java_multiple_files`). See issue #1054.
    sources = _expand_java_srcjars(sources, classes_dir + '.srcs')

    cmd = ['javac', '-encoding', source_encoding, '-d', classes_dir,
           '-classpath', classpath] + javacflags + sources
    subprocess.check_call(cmd)
    subprocess.check_call(['jar', 'cf', output, '-C', classes_dir, '.'])


def _expand_java_srcjars(sources, extract_dir):
    """Replace any `.srcjar`/`.jar` entry in `sources` with the `.java` files it
    contains (extracted under `extract_dir`); plain sources pass through."""
    import zipfile  # pylint: disable=import-outside-toplevel
    if not any(s.endswith(('.srcjar', '.jar')) for s in sources):
        return sources
    shutil.rmtree(extract_dir, ignore_errors=True)
    os.makedirs(extract_dir, exist_ok=True)
    expanded = []
    for s in sources:
        if s.endswith(('.srcjar', '.jar')):
            with zipfile.ZipFile(s) as z:
                for name in z.namelist():
                    if name.endswith('.java'):
                        z.extract(name, extract_dir)
                        expanded.append(os.path.join(extract_dir, name))
        else:
            expanded.append(s)
    return expanded


def generate_proto_java_srcjar(args):
    """Run protoc to generate Java, then zip the result into a `.srcjar`.

    Invoked as: ``proto_java_srcjar <out.srcjar> <gendir> -- <protoc cmd...>``.

    protoc emits an unpredictable set of `.java` files (one outer class, or --
    with ``option java_multiple_files = true;`` -- one per top-level type), so
    instead of predicting filenames we collect everything protoc wrote under
    ``gendir`` into a single srcjar. See issue #1054.
    """
    import subprocess  # pylint: disable=import-outside-toplevel
    import zipfile  # pylint: disable=import-outside-toplevel
    srcjar = args[0]
    gendir = args[1]
    assert args[2] == '--', 'proto_java_srcjar: expected "--" before the protoc command'
    cmd = args[3:]
    _declare_outputs(srcjar)
    shutil.rmtree(gendir, ignore_errors=True)
    os.makedirs(gendir, exist_ok=True)
    subprocess.check_call(cmd)
    with zipfile.ZipFile(srcjar, 'w', zipfile.ZIP_DEFLATED) as z:
        for root, _, files in os.walk(gendir):
            for name in sorted(files):
                if name.endswith('.java'):
                    full = os.path.join(root, name)
                    # Jar entries always use '/' (Windows relpath yields '\').
                    arcname = os.path.relpath(full, gendir).replace(os.sep, '/')
                    z.write(full, arcname)


def generate_java_jar(compression_level, args):
    jar, target = args[0], args[1]
    _declare_outputs(target)
    resources_dir = target.replace('.jar', '.resources')
    arg = args[2]
    if arg.endswith('__classes__.jar'):
        classes_jar = arg
        resources = args[3:]
    else:
        classes_jar = ''
        resources = args[2:]

    def archive_resources(resources_dir, resources, new=True):
        options = ('c' if new else 'u') + 'f' + compression_level
        cmd = [f'{jar} {options} {target}']
        for resource in resources:
            cmd.append(f"-C '{resources_dir}' '{os.path.relpath(resource, resources_dir)}'")
        return util.shell(cmd)

    if classes_jar:
        shutil.copy2(classes_jar, target)
        if resources:
            return archive_resources(resources_dir, resources, False)
    else:
        return archive_resources(resources_dir, resources, True)


def generate_java_resource(args):
    assert len(args) % 2 == 0
    middle = len(args) // 2
    targets = args[:middle]
    sources = args[middle:]
    _declare_outputs(*targets)
    for i in range(middle):
        shutil.copy(sources[i], targets[i])


def _get_all_test_class_names_in_jar(jar):
    """Returns a list of test class names in the jar file."""
    import zipfile  # pylint: disable=import-outside-toplevel
    test_class_names = []
    zip_file = zipfile.ZipFile(jar, 'r')
    name_list = zip_file.namelist()
    for name in name_list:
        basename = os.path.basename(name)
        # Exclude inner class and Test.class
        if (basename.endswith('Test.class') and
                len(basename) > len('Test.class') and '$' not in basename):
            class_name = name.replace('/', '.')[:-6]  # Remove .class suffix
            test_class_names.append(class_name)
    zip_file.close()
    return test_class_names


def _jacoco_test_coverage_flag(jacocoagent, packages_under_test):
    if packages_under_test and jacocoagent:
        jacocoagent = os.path.abspath(jacocoagent)
        packages = packages_under_test.split(':')
        options = [
            'includes=%s' % ':'.join([p + '.*' for p in packages if p]),
            'output=file',
        ]
        return '-javaagent:{}={}'.format(jacocoagent, ','.join(options))
    return ''


def generate_java_test(script, main_class, jacocoagent, packages_under_test, args):
    _declare_outputs(script)
    jars = args
    test_jar = jars[0]
    test_classes = ' '.join(_get_all_test_class_names_in_jar(test_jar))
    if os.name == 'nt':
        _generate_java_test_bat(script, main_class, jacocoagent, packages_under_test, jars, test_classes)
    else:
        _generate_java_test_sh(script, main_class, jacocoagent, packages_under_test, jars, test_classes)


def _generate_java_test_sh(script, main_class, jacocoagent, packages_under_test, jars, test_classes):
    coverage_flags = _jacoco_test_coverage_flag(jacocoagent, packages_under_test)
    abs_jars = [os.path.abspath(j) for j in jars]
    content = textwrap.dedent('''\
            #!/bin/sh
            # Auto generated wrapper shell script by blade

            if [ -n "$BLADE_COVERAGE" ]; then
                coverage_options="%s"
            fi

            exec java $coverage_options -classpath %s %s %s $@''') % (
            coverage_flags, ':'.join(abs_jars), main_class, test_classes)
    util.write_if_changed(script, content)
    os.chmod(script, 0o755)


def _generate_java_test_bat(script, main_class, jacocoagent, packages_under_test, jars, test_classes):
    coverage_flags = _jacoco_test_coverage_flag(jacocoagent, packages_under_test)
    abs_jars = [os.path.abspath(j) for j in jars]
    lines = [
        '@echo off\r\n',
        'rem Auto generated wrapper batch script by blade\r\n',
        '\r\n',
        'setlocal\r\n',
        'set "coverage_options="\r\n',
        'if defined BLADE_COVERAGE set "coverage_options=%s"\r\n' % coverage_flags,
        'java %%coverage_options%% -classpath %s %s %s %%*\r\n' % (
            ';'.join(abs_jars), main_class, test_classes),
        'endlocal\r\n',
    ]
    content = ''.join(lines)
    util.write_if_changed(script, content)


def generate_fat_jar(output, **kwargs):
    # Import from function to avoid affecting the performance of other tools.
    from blade import fatjar  # pylint: disable=import-outside-toplevel
    _declare_outputs(output)
    console.set_log_file('%s.log' % output.replace('.fat.jar', '__fatjar__'))
    console.enable_color(True)
    fatjar.generate_fat_jar(output=output, **kwargs)


def generate_one_jar(onejar, main_class, bootjar, args):
    import zipfile  # pylint: disable=import-outside-toplevel
    _declare_outputs(onejar)
    # Assume the first jar is the main jar, others jars are dependencies.
    main_jar = args[0]
    jars = args[1:]
    path = onejar
    onejar = zipfile.ZipFile(path, 'w', allowZip64=True)
    jar_path_set = set()
    # Copy files from one-jar-boot.jar to the target jar
    zip_file = zipfile.ZipFile(bootjar, 'r')
    name_list = zip_file.namelist()
    for name in name_list:
        if not name.lower().endswith('manifest.mf'):  # Exclude manifest
            onejar.writestr(name, zip_file.read(name))
            jar_path_set.add(name)
    zip_file.close()

    # Main jar and dependencies
    onejar.write(main_jar, os.path.join('main',
                                        os.path.basename(main_jar)))
    for dep in jars:
        dep_name = os.path.basename(dep)
        onejar.write(dep, os.path.join('lib', dep_name))

    # Copy resources to the root of target onejar
    for jar in [main_jar] + jars:
        jar = zipfile.ZipFile(jar, 'r')
        jar_name_list = jar.namelist()
        for name in jar_name_list:
            if name.endswith('.class') or name.upper().startswith('META-INF'):
                continue
            if name not in jar_path_set:
                jar_path_set.add(name)
                onejar.writestr(name, jar.read(name))
        jar.close()

    # Manifest
    # Note that the manifest file must end with a new line or carriage return
    onejar.writestr(os.path.join('META-INF', 'MANIFEST.MF'),
                    textwrap.dedent('''\
                            Manifest-Version: 1.0
                            Main-Class: com.simontuffs.onejar.Boot
                            One-Jar-Main-Class: %s

                            ''') % main_class)
    onejar.close()


def generate_java_binary(args):
    script, onejar = args
    _declare_outputs(script)
    basename = os.path.basename(onejar)
    fullpath = os.path.abspath(onejar)
    content = textwrap.dedent('''\
            #!/bin/sh
            # Auto generated wrapper shell script by blade

            jar=`dirname "$0"`/"%s"
            if [ ! -f "$jar" ]; then
              jar="%s"
            fi

            exec java -jar "$jar" $@
            ''') % (basename, fullpath)
    util.write_if_changed(script, content)
    os.chmod(script, 0o755)


def generate_scala_test(script, java, scala, jacocoagent, packages_under_test, args):
    _declare_outputs(script)
    jars = args
    test_jar = jars[0]
    test_class_names = _get_all_test_class_names_in_jar(test_jar)
    scala, java = os.path.abspath(scala), os.path.abspath(java)
    abs_jars = [os.path.abspath(j) for j in jars]
    java_args = ''
    coverage_flags = _jacoco_test_coverage_flag(jacocoagent, packages_under_test)
    if coverage_flags:
        java_args = '-J%s' % coverage_flags
    run_args = 'org.scalatest.run ' + ' '.join(test_class_names)
    with open(script, 'w') as f:
        text = textwrap.dedent('''\
                #!/bin/sh
                # Auto generated wrapper shell script by blade

                if [ -n "$BLADE_COVERAGE" ]; then
                    coverage_options="%s"
                fi

                JAVACMD=%s exec %s "$coverage_options" -classpath %s %s $@
                ''') % (java_args, java, scala, ':'.join(abs_jars), run_args)
        f.write(text)
    os.chmod(script, 0o755)


def generate_shell_test(args):
    wrapper = args[0]
    scripts = args[1:]
    _declare_outputs(wrapper)
    with open(wrapper, 'w') as f:
        f.write(textwrap.dedent("""\
                #!/bin/sh
                # Auto generated wrapper shell script by blade

                set -e

                %s

                """) % '\n'.join(['. %s' % os.path.abspath(s) for s in scripts]))
    os.chmod(wrapper, 0o755)


def generate_shell_testdata(args):
    path = args[0]
    testdata = args[1:]
    _declare_outputs(path)
    assert len(testdata) % 2 == 0
    middle = len(testdata) // 2
    sources = testdata[:middle]
    destinations = testdata[middle:]
    with open(path, 'w') as f:
        for i in range(middle):
            f.write(f'{os.path.abspath(sources[i])} {destinations[i]}\n')


def generate_python_library(pylib, basedir, args):
    _declare_outputs(pylib)
    sources = []
    for py in args:
        digest = util.md5sum_file(py)
        sources.append((py, digest))
    with open(pylib, 'w') as f:
        print(str({
            'base_dir': basedir,
            'srcs': sources
        }), file=f)


def _is_python_excluded_path(filename, exclusions):
    import fnmatch  # pylint: disable=import-outside-toplevel
    for exclusion in exclusions:
        if fnmatch.fnmatch(filename, exclusion):
            return True
    return False


def _update_init_py_dirs(arcname, dirs, dirs_with_init_py):
    dir = os.path.dirname(arcname)
    if os.path.basename(arcname) == '__init__.py':
        dirs_with_init_py.add(dir)
    while dir:
        dirs.add(dir)
        dir = os.path.dirname(dir)


def _pybin_add_pylib(pybin, libname, exclusions, dirs, dirs_with_init_py):
    with open(libname) as pylib:
        data = eval(pylib.read())  # pylint: disable=eval-used
        pylib_base_dir = data['base_dir']
        for libsrc, digest in data['srcs']:
            arcname = os.path.relpath(libsrc, pylib_base_dir)
            if not _is_python_excluded_path(arcname, exclusions):
                _update_init_py_dirs(arcname, dirs, dirs_with_init_py)
                pybin.write(libsrc, arcname)


def _pybin_add_zip(pybin, libname, filter, exclusions, dirs, dirs_with_init_py):
    import zipfile  # pylint: disable=import-outside-toplevel
    with zipfile.ZipFile(libname, 'r') as lib:
        name_list = lib.namelist()
        for name in name_list:
            if filter(name) and not _is_python_excluded_path(name, exclusions):
                if dirs is not None and dirs_with_init_py is not None:
                    _update_init_py_dirs(name, dirs, dirs_with_init_py)
                pybin.writestr(name, lib.read(name))


def _pybin_add_egg(pybin, libname, exclusions):
    def filter(name):
        if name.startswith('EGG-INFO'):
            return False
        if name.endswith('.pyc'):
            return False
        return True

    _pybin_add_zip(pybin, libname, filter, exclusions, None, None)


def _pybin_add_whl(pybin, libname, exclusions, dirs, dirs_with_init_py):
    def filter(name):
        if '.dist-info/' in name:
            return False
        return True

    _pybin_add_zip(pybin, libname, filter, exclusions, dirs, dirs_with_init_py)


def generate_python_binary(pybin, basedir, exclusions, mainentry, args):
    # pybin is the wrapper script.  The zip always goes to
    # <pybin_without_extension>.zip, identical on all platforms.
    import zipfile  # pylint: disable=import-outside-toplevel
    base, _ = os.path.splitext(pybin)
    zip_path = base + '.zip'
    _declare_outputs(pybin, zip_path)

    # Generate the pure zip file — identical on all platforms.
    pybin_zip = zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED, allowZip64=True)
    exclusions = exclusions.split(',')
    dirs, dirs_with_init_py = set(), set()
    for arg in args:
        if arg.endswith('.pylib'):
            _pybin_add_pylib(pybin_zip, arg, exclusions, dirs, dirs_with_init_py)
        elif arg.endswith('.egg'):
            _pybin_add_egg(pybin_zip, arg, exclusions)
        elif arg.endswith('.whl'):
            _pybin_add_whl(pybin_zip, arg, exclusions, dirs, dirs_with_init_py)
        else:
            assert False, 'Unknown file type "%s" to build python_binary' % arg

    # Insert __init__.py into each dir if missing
    dirs_missing_init_py = dirs - dirs_with_init_py
    for dir in sorted(dirs_missing_init_py):
        pybin_zip.writestr(os.path.join(dir, '__init__.py'), '')
    pybin_zip.writestr('__init__.py', '')
    pybin_zip.close()

    if os.name == 'nt':
        content = '@echo off\r\n'
        content += 'set "PYTHONPATH=%~dp0%~n0.zip;%PYTHONPATH%"\r\n'
        content += f'python -m {mainentry} %*\r\n'
        util.write_if_changed(pybin, content)
        return

    content = '#!/bin/sh\n'
    content += 'ZIP="$(dirname "$0")/$(basename "$0").zip"\n'
    content += ('PYTHONPATH="$ZIP:$PYTHONPATH" '
                'exec "${BLADE_PYTHON_INTERPRETER:-python3}" '
                f'-m {mainentry} "$@"\n')
    util.write_if_changed(pybin, content)
    os.chmod(pybin, 0o755)


def generate_dwp(args):
    """Generate dwp file for debugging."""
    # Import from function to avoid affecting the performance of other tools.
    from blade import dwp_wrapper  # pylint: disable=import-outside-toplevel

    output_file = args[0]
    input_files = args[1:]

    _declare_outputs(output_file)

    # Expand response files in inputs
    expanded_inputs = dwp_wrapper.expand_response_files(input_files)

    dwo_files = dwp_wrapper.collect_dwo_files(expanded_inputs)

    # Run dwp tool
    dwp_wrapper.run_dwp(output_file, dwo_files)


_BUILTIN_TOOLS = {
    'scm': generate_scm,
    'package': generate_package,
    'javac_compile': generate_javac_compile,
    'proto_java_srcjar': generate_proto_java_srcjar,
    'cc_inclusion_check': generate_cc_inclusion_check,
    'cc_check_undefined': generate_cc_check_undefined,
    'cc_check_undefined_batch': generate_cc_check_undefined_batch,
    'cc_emit_syms': generate_cc_emit_syms,
    'cc_macos_exports': generate_macos_exports,
    'cc_windef': generate_cc_windef,
    'resource': generate_resource,
    'resource_index': generate_resource_index,
    'java_jar': generate_java_jar,
    'java_resource': generate_java_resource,
    'java_test': generate_java_test,
    'java_fatjar': generate_fat_jar,
    'java_onejar': generate_one_jar,
    'java_binary': generate_java_binary,
    'scala_test': generate_scala_test,
    'shell_test': generate_shell_test,
    'shell_testdata': generate_shell_testdata,
    'python_library': generate_python_library,
    'python_binary': generate_python_binary,
    'dwp': generate_dwp,
}


def main():
    name = sys.argv[1]
    exit_code = 0
    try:
        options, args = util.parse_command_line(sys.argv[2:])
        exit_code = _BUILTIN_TOOLS[name](args=args, **options)
        if not exit_code:
            _verify_outputs()
    except Exception as e:  # pylint: disable=broad-except
        console.error(f'Blade build tool {name} error: {e!s} {traceback.format_exc()}')
        exit_code = 1
    finally:
        if exit_code:
            _cleanup_outputs()
        sys.exit(exit_code or 0)


if __name__ == '__main__':
    main()
