# Copyright (c) 2026 The Blade Authors.
# All rights reserved.

"""
cc / cuda ninja rule generation, extracted from backend.py (M2 of #1264).

``CcRuleGenerator`` is fed a :class:`~blade.rule_context.RuleContext` and emits
the cc-family rules. The original method bodies are kept verbatim; the thin
adapter below re-exposes the handful of ``self.*`` members those bodies use
(``generate_rule``, ``_add_line``, ``_builtin_command`` and the
toolchain/accelerator/options/build_dir/command/blade state) by delegating to
the RuleContext. ``_builtin_command`` is cross-language and stays in backend;
everything here is cc/cuda-specific.
"""

import os
import sys
import textwrap

from blade import config
from blade import console
from blade import sanitizer
from blade import util
from blade.ninja_rule import NinjaRule


# To verify whether a header is included without depending on the library it
# belongs to, we use gcc's `-H` option to print the inclusion stack
# (https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html). That goes to
# stderr, mixed with diagnostics, so this awk program separates them: lines of
# the inclusion stack (leading dots) go to stdout (-> the `.incstk` file),
# everything else is forwarded to stderr.
#
# `多个防止重包含可能对其有用：` is the Chinese of `Multiple include guards...`;
# after that marker the trailing file list is noise, but later lines (e.g. a
# cuda error) may still matter, so we don't `exit` early.
_INCLUSION_SPLITTER_AWK = r'''
/Multiple include guards may be useful for:|多个防止重包含可能对其有用：/ { stop = 1 }
/^\.+ [^\/]/ && !end { started = 1; print $0 }       # an inclusion-stack line
!/^\.+ / && started { end = 1 }                      # first line after the stack
!/^\.+ / && (!stop || (!/Multiple include guards may be useful for:|多个防止重包含可能对其有用：/ && !/^[a-zA-Z0-9\.\/\+_-]+$/)) { print $0 > "/dev/stderr" }
'''

_INCLUSION_WRAPPER_SCRIPT = '''\
#!/bin/sh
# Generated by blade; do not edit. See backend.py (_inclusion_wrapper_script).
mode=$1
out=$2
shift 2
err=$out.err
export LC_ALL=C
if [ "$mode" = hdrs ]; then
    # -fdirectives-only speeds up preprocessing but breaks on some edge cases
    # (e.g. __COUNTER__ tricks); retry without it, discarding the first
    # attempt's diagnostics.
    "$@" -fdirectives-only 2> "$err" || "$@" 2> "$err"
else
    "$@" 2> "$err"
fi
ec=$?
awk '%s' "$err" > "$out.new"
# write-if-changed: keep $out's mtime when the inclusion stack is unchanged, so
# ninja's `restat` can prune the inclusion check on recompiles that don't alter
# the set of included headers. See issue #1161.
if [ -f "$out" ] && cmp -s "$out.new" "$out"; then
    rm -f "$out.new"
else
    mv "$out.new" "$out"
fi
rm -f "$err"
exit $ec
''' % _INCLUSION_SPLITTER_AWK

_MSVC_TEE_WRAPPER_PY = r'''
import os, re, subprocess, sys, tempfile

outfile = sys.argv[1]
# sys.argv[2] is "--"
cmd = sys.argv[3:]

_NOTE_PREFIX = 'Note: including file:'
_cwd = os.getcwd()

# Compilers echo the basename of the file they process.  Ninja's
# CLParser::FilterInputFilename strips it for source files (.c/.cc/.cxx/.cpp/
# .c++) but NOT for headers, so the cxxhdrs rule (/P on a .h) leaks a bare
# "foo.h" onto the build console; nvcc additionally echoes its source (.cu)
# and a zoo of intermediate temp names (tmpxft_*.cpp1.ii, *.cudafe1.cpp, ...).
# Enumerating extensions is hopeless, so match any lone filename token: no
# whitespace, no path separator, at least one dot, only filename-safe chars.
# Real diagnostics always carry spaces/colons/parens and never match.
_BARE_FILENAME_RE = re.compile(r'^[\w.+\-]+\.[\w.+\-]+$')

def _in_workspace(hdr):
    try:
        return os.path.commonpath([_cwd, hdr]) == _cwd
    except ValueError:  # different drive -> outside the workspace
        return False

# nvcc writes its intermediates (tmpxft_*.cudafe1.stub.c, *.fatbin.c, ...) into
# a temp dir and lists them in /showIncludes. They are deleted after the build,
# so recording them as deps makes ninja rebuild the CUDA object every time (the
# dep targets are perpetually "missing"). They are never real source deps ->
# drop such include lines entirely (neither incstk nor forwarded to ninja).
#
# All nvcc intermediates are named `tmpxft_*`, which is the reliable signal --
# independent of *where* nvcc puts them. Also catch anything under the temp dir
# as a backstop (normcase so the Windows case-insensitive match works; the temp
# dir nvcc uses may differ from this process's, so the name check is primary).
_TEMP_DIR = os.path.normcase(os.path.realpath(tempfile.gettempdir()))

def _in_temp(hdr):
    if os.path.basename(hdr).startswith('tmpxft_'):
        return True
    try:
        p = os.path.normcase(os.path.realpath(hdr))
        return p == _TEMP_DIR or p.startswith(_TEMP_DIR + os.sep)
    except (ValueError, OSError):  # bad path -> not in temp
        return False

# Force the English "Note: including file:" prefix. cl.exe (and nvcc's cl)
# localize /showIncludes on a non-English Visual Studio, which would silently
# break both the inclusion stack written below and Ninja's deps=msvc header
# tracking (the prefix _NOTE_PREFIX above and Ninja's msvc_deps_prefix are both
# the English string). VSLANG=1033 is the en-US LCID; set it on the child only,
# not the whole build, so nothing else is affected. See issue #1154.
env = dict(os.environ)
env['VSLANG'] = '1033'

# Merge stdout+stderr into one pipe (like Ninja).  Reading only stderr risks
# a pipe deadlock: if cl.exe writes enough to stdout (even with /nologo a
# leftover copyright banner fills the 4 KiB buffer), the process blocks and
# never drains its stderr output through the unread stdout pipe.
p = subprocess.Popen(cmd, env=env, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                     universal_newlines=True, encoding='utf-8', errors='replace')
with open(outfile + '.new', 'w', newline='', encoding='utf-8') as f:
    for line in p.stdout:
        if line.startswith(_NOTE_PREFIX):
            hdr = line[len(_NOTE_PREFIX):].lstrip().rstrip('\r\n')
            if os.path.isabs(hdr) and _in_temp(hdr):
                # nvcc intermediate in the temp dir -- not a real dependency;
                # drop entirely so ninja doesn't record it and rebuild forever.
                continue
            # Record only workspace headers in the incstk (smaller file; the
            # inclusion checker discards absolute/system paths anyway), but
            # forward every include line to ninja's deps=msvc parser below.
            if not os.path.isabs(hdr) or _in_workspace(hdr):
                f.write(line)
        elif _BARE_FILENAME_RE.match(line.strip()):
            continue  # echoed source/temp filename -- console noise, drop it
        sys.stderr.write(line)
        sys.stderr.flush()

ec = p.wait()

# Write-if-changed: keep mtime when the stack is unchanged, so ninja's
# restat can prune the inclusion check. See issue #1161.
try:
    with open(outfile + '.new', 'rb') as nf:
        new = nf.read()
    try:
        with open(outfile, 'rb') as of:
            old = of.read()
    except FileNotFoundError:
        old = None
    if new != old:
        os.replace(outfile + '.new', outfile)
    else:
        os.unlink(outfile + '.new')
except OSError:
    pass

sys.exit(ec)
'''

_MSVC_LINK_WRAPPER_PY = r'''
import os, re, subprocess, sys

# A lone filename token (no spaces/path, at least one dot) -- same shape the cc
# wrapper drops. Real diagnostics carry spaces/colons and never match.
_BARE_FILENAME_RE = re.compile(r'^[\w.+\-]+\.[\w.+\-]+$')

sep = sys.argv.index('--')
args = sys.argv[1:sep]
cmd = sys.argv[sep + 1:]
env = dict(os.environ)
env['VSLANG'] = '1033'  # force English so the filter below matches
# Prepend the MSVC + Windows SDK bin dirs so link.exe can find the helper
# tools it spawns by name -- notably mt.exe (in the SDK bin, a different dir
# from link.exe) for /MANIFEST:EMBED. blade invokes link by absolute path, but
# tools link itself spawns are resolved via PATH. See cc_rule_support.
if '--prepend-path' in args:
    _dirs = args[args.index('--prepend-path') + 1]
    if _dirs:
        env['PATH'] = _dirs + os.pathsep + env.get('PATH', '')

p = subprocess.Popen(cmd, env=env, stdout=subprocess.PIPE,
                     stderr=subprocess.STDOUT, universal_newlines=True,
                     encoding='utf-8', errors='replace')
for line in p.stdout:
    s = line.strip()
    if s.startswith('Creating library ') and ' and object ' in s:
        continue  # link.exe import-library notice (redundant with "LINK ...")
    if _BARE_FILENAME_RE.match(s):
        continue  # nvcc's echoed object/source name (e.g. test.cu.obj)
    sys.stdout.write(line)
    sys.stdout.flush()
sys.exit(p.wait())
'''


# A tiny shell wrapper for the macOS archive step. Apple's libtool/ranlib warns
# "... the table of contents is empty (no object file members in the library
# define global symbols)" for a symbol-less static library (an all-inline/
# template lib whose stub `.cc` compiles to no global symbols). Such an `.a`
# links fine as a header carrier, the warning is pure noise, and unlike "has no
# symbols" it has no suppression flag (`-no_warning_for_no_symbols` does not
# cover it). So drop just that one line from stderr while preserving stdout,
# every other diagnostic, and the archive command's exit code.
#
# Process substitution streams stderr through `grep` live (no temp file), and
# `exec` replaces the shell with the archive command so the only process beyond
# the unavoidable `grep` is gone -- and the exit code is naturally the command's.
# This needs bash, not `/bin/sh`: macOS's `/bin/sh` is bash in POSIX mode, which
# rejects `>( )` as a syntax error. A shell wrapper (not a `builtin_tools` Python
# helper) keeps the per-archive cost to a `/bin/bash` spawn instead of a Python
# interpreter + `blade` package import on every `cc_library`. darwin-only --
# Linux `ar` never emits this warning, so the rule wraps the command on macOS
# alone.
_DARWIN_AR_WRAPPER_SH = r'''#!/bin/bash
exec "$@" 2> >(grep -v 'table of contents is empty' >&2)
'''

# `--gprof` runs the cc flag computation per target; only complain once.
_gprof_unsupported_warned = False


def _warn_gprof_unsupported(target_os):
    global _gprof_unsupported_warned
    if _gprof_unsupported_warned:
        return
    _gprof_unsupported_warned = True
    console.warning(
        '--gprof is not supported on %s (gprof/-pg instrumentation only works '
        'on Linux); the flag is ignored. Use --coverage, or a native profiler '
        '(Instruments/sample on macOS).' % target_os)


# --- PGO (profile-guided optimization) ---------------------------------------
#
# PGO is invocation-driven (a global build mode), per the design in #1366:
# `--profile-generate` instruments, the user runs a representative workload,
# then `--profile-use` rebuilds with the collected profile. gcc and clang share
# the `-fprofile-*` spelling but diverge in the use phase:
#   * gcc reads the `.gcda` files directly and wants `-fprofile-correction`
#     to tolerate the count skew a multithreaded program produces.
#   * clang REJECTS `-fprofile-correction`; its instrumented run emits
#     `.profraw`, which must be `llvm-profdata merge`'d into a `.profdata` that
#     `-fprofile-use=` then points at (a file, not a directory).
# Native MSVC is a different flag family (/GL + /LTCG:PG*) and is implemented in
# the Windows compile/lib/link rules below (see the `_pgo_msvc_*` helpers); the
# gcc/clang `-fprofile-*` path here never runs for MSVC.


def _pgo_option(options, name):
    """Value of a PGO option ('' = enabled with no path), or None if absent."""
    return getattr(options, name, None) if hasattr(options, name) else None


def _find_llvm_profdata(toolchain):
    """Locate ``llvm-profdata`` for a clang toolchain: next to the compiler,
    then PATH, then ``xcrun`` on macOS. Returns a command list or ``None``."""
    import shutil
    cc = getattr(toolchain, 'cc', '') or ''
    bindir = os.path.dirname(cc)
    if bindir:
        cand = os.path.join(bindir, 'llvm-profdata')
        if os.path.isfile(cand):
            return [cand]
    found = shutil.which('llvm-profdata')
    if found:
        return [found]
    if toolchain.target_os == 'darwin' and shutil.which('xcrun'):
        rc, out, _ = util.run_command(['xcrun', '--find', 'llvm-profdata'])
        if rc == 0 and out.strip():
            return [out.strip()]
    return None


# Merge runs at most once per build (the flag computation is invoked several
# times); cache the resolved profdata path keyed by the source path.
_clang_profdata_cache = {}


def _resolve_clang_profdata(toolchain, path):
    """Return a ``.profdata`` path for clang ``-fprofile-use=``.

    - empty -> ``None`` (bare ``-fprofile-use``; clang reads ``default.profdata``)
    - a ``.profdata`` file -> used as-is
    - a directory (or raw ``.profraw``) -> merged once via ``llvm-profdata
      merge`` into ``<dir>/blade-merged.profdata``.
    On any failure, warn once and fall back to the original path so the build
    surfaces a clear error rather than silently dropping PGO.
    """
    if not path:
        return None
    if os.path.isfile(path) and path.endswith('.profdata'):
        return path
    if path in _clang_profdata_cache:
        return _clang_profdata_cache[path]

    import glob
    if os.path.isdir(path):
        raws = glob.glob(os.path.join(path, '**', '*.profraw'), recursive=True)
        out_dir = path
    else:  # a glob/raw path
        raws = glob.glob(path)
        out_dir = os.path.dirname(path) or '.'
    profdata = os.path.join(out_dir, 'blade-merged.profdata')

    tool = _find_llvm_profdata(toolchain)
    if not tool or not raws:
        console.warning(
            'PGO profile-use: clang needs a merged .profdata but could not '
            'produce one from "%s" (llvm-profdata %s, %d .profraw found). Pass '
            'an already-merged .profdata to --profile-use, or run: '
            'llvm-profdata merge -o out.profdata %s/*.profraw' % (
                path, 'not found' if not tool else 'found', len(raws), path))
        _clang_profdata_cache[path] = path
        return path

    rc, _, err = util.run_command(tool + ['merge', '-output=' + profdata] + raws)
    if rc != 0:
        console.warning('PGO profile-use: llvm-profdata merge failed: %s' % err)
        _clang_profdata_cache[path] = path
        return path
    console.info('PGO: merged %d .profraw into %s' % (len(raws), profdata))
    _clang_profdata_cache[path] = profdata
    return profdata


# --- MSVC PGO (#1366 Phase 2) ------------------------------------------------
#
# MSVC PGO is a different flag family from gcc/clang's `-fprofile-*`: it is
# whole-program (LTCG) instrumentation. Verified end to end on VS:
#   instrument: compile `/GL`, link `/LTCG /GENPROFILE` -> binary + `<name>.pgd`
#   run:        the binary writes `<name>!N.pgc` next to the `.pgd`
#   optimize:   link `/LTCG /USEPROFILE` -- auto-merges the `.pgc` into the
#               `.pgd` and rebuilds optimized (no separate `pgomgr` step)
# The `.pgd` is keyed to the output name, so the instrument and optimize builds
# share one `build_*_pgo` dir (the same dir gcc needs for `.gcda` lookup).

def _pgo_msvc_active(options):
    return (_pgo_option(options, 'profile-generate') is not None
            or _pgo_option(options, 'profile-use') is not None)


def _pgo_msvc_compile_flags(options):
    """MSVC compile flags for an active PGO mode: `/GL` (whole-program info LTCG
    PGO needs; same flag for the instrument and the optimize build). The
    `BLADE_PGO_GENERATE` define is added on the instrument build only -- it lets
    source flush profile data (`PgoAutoSweep`) in long-running servers."""
    if not _pgo_msvc_active(options):
        return []
    flags = ['/GL']
    if _pgo_option(options, 'profile-generate') is not None:
        flags.append('/DBLADE_PGO_GENERATE')
    return flags


def _pgo_msvc_lib_flags(options):
    """`lib.exe` needs `/LTCG` to archive the `/GL` objects a PGO build emits."""
    return ['/LTCG'] if _pgo_msvc_active(options) else []


def _pgo_msvc_link_flags(options):
    """MSVC PGO link flags: `/LTCG /GENPROFILE` to instrument, `/LTCG /USEPROFILE`
    to optimize (the latter auto-merges the run's `.pgc` into the `.pgd`)."""
    if _pgo_option(options, 'profile-generate') is not None:
        return ['/LTCG', '/GENPROFILE']
    if _pgo_option(options, 'profile-use') is not None:
        return ['/LTCG', '/USEPROFILE']
    return []


# --- AutoFDO (sample-based PGO, #1372) ---------------------------------------
#
# AutoFDO needs NO instrumentation: you build a normal optimized binary (with
# debug info so samples map to source), sample it, and rebuild with the profile.
# The --autofdo-* flags drive all three toolchains (sample PGO is cross-platform):
#   * clang -> `-fprofile-sample-use=<profile>`; collection adds
#     `-fdebug-info-for-profiling -funique-internal-linkage-names`. (perf+LBR)
#   * gcc   -> `-fauto-profile=<profile>`; collection needs only the `-g` blade
#     already emits (the clang debug flags are clang-only). (perf+LBR)
#   * native MSVC -> SPGO (`/spgo` collect, `/LTCG /spdin:` use); see the "MSVC
#     SPGO" section below. (xperf, no perf needed)
# For gcc/clang, blade applies the flags; converting `perf.data` -> a sample
# profile is the user's step because the converter (llvm-profgen / create_gcov)
# needs the *collected binary*, which blade doesn't have at flag-computation
# time. So `--autofdo-use` takes an already-converted profile; a raw perf.data
# is detected and rejected with the exact conversion command. (MSVC likewise
# takes an already-sampled `.spd` via /spdin.)

_PERF_DATA_MAGIC = b'PERFILE2'


def _autofdo_active(options):
    return (getattr(options, 'autofdo-generate', False)
            or bool(getattr(options, 'autofdo-use', None)))


def _has_line_table_debug(debug_info_options):
    """Whether the configured debug-info flags carry source line tables -- any
    `-g<level>` except the off level / the split-dwarf modifier."""
    for f in debug_info_options:
        if f in ('-g0', '-gsplit-dwarf'):
            continue
        if f.startswith('-g'):
            return True
    return False


def _has_msvc_debug_info(debug_info_options):
    """Whether the MSVC debug-info flags emit symbols (CodeView/PDB)."""
    return any(f in ('/Z7', '/Zi', '/ZI') for f in debug_info_options)


# Notify once when blade bumps debug info for collection (it overrides an
# explicit debug_info_level=no); benign, so notice not warning.
_autofdo_debug_noticed = False


def _notice_autofdo_debug_added(flag):
    global _autofdo_debug_noticed
    if _autofdo_debug_noticed:
        return
    _autofdo_debug_noticed = True
    console.notice(
        'AutoFDO/SPGO collection needs line-table debug info to map samples '
        'back to source, but debug_info_level emits none; blade added %s for '
        'this collection build (small size cost).' % flag)


def _resolve_autofdo_profile(path):
    """Return a sample-profile path for `-fprofile-sample-use`/`-fauto-profile`.

    `path` must be an already-converted profile. If it is a raw `perf.data`
    (detected by the ``PERFILE2`` magic), warn with the conversion command and
    return ``None`` so the build proceeds without AutoFDO rather than handing
    the compiler a file it can't read.
    """
    try:
        with open(path, 'rb') as f:
            head = f.read(8)
    except OSError:
        head = b''
    if head == _PERF_DATA_MAGIC:
        console.warning(
            '--autofdo-use was given a raw perf.data ("%s"); convert it to a '
            'sample profile first (it needs the collected binary, which blade '
            "doesn't have): clang -> `llvm-profgen --perfdata=%s --binary=<exe> "
            '--output=out.prof`; gcc -> `create_gcov --binary=<exe> '
            '--profile=%s --gcov=out.afdo`. Skipping AutoFDO.'
            % (path, path, path))
        return None
    return path


_autofdo_clang_cl_warned = False


def _warn_autofdo_clang_cl():
    """clang-cl can't do sample PGO on Windows: SPGO is a cl.exe/link feature,
    and LLVM AutoFDO needs `perf`, which Windows lacks."""
    global _autofdo_clang_cl_warned
    if _autofdo_clang_cl_warned:
        return
    _autofdo_clang_cl_warned = True
    console.warning(
        'AutoFDO is not available for clang-cl: MSVC SPGO is a cl.exe feature '
        '(blade drives it on native cl.exe), and LLVM AutoFDO needs perf, which '
        'Windows lacks. Build with native cl.exe for SPGO, or use instrumentation '
        'PGO (--profile-generate/--profile-use). Skipping.')


# --- MSVC SPGO (Sample Profile Guided Optimization, #1372) --------------------
#
# MSVC's sample PGO, driven by blade's --autofdo-* on native cl.exe (VS 2022 /
# 2026, MSVC 14.51+). It's the cl.exe counterpart of LLVM AutoFDO:
#   collect: compile `/GL`, link `/spgo` -> the binary + a `.spd` static
#            description. Sample it with `xperf` (IP or LBR), then `SPDConvert`
#            correlates the samples into the `.spd` profile (the user's step).
#   use:     compile `/GL`, link `/LTCG /spdin:<app.spd>`.
# Same /GL whole-program requirement as the instrumentation /GENPROFILE path,
# and the same shared `build_*_autofdo` dir for both phases.

def _spgo_msvc_active(options):
    return _autofdo_active(options)


def _spgo_msvc_compile_flags(options):
    """`/GL` on compile for an active SPGO mode (whole-program info SPGO needs);
    no profile-flush define -- SPGO samples a normal binary (like AutoFDO)."""
    return ['/GL'] if _spgo_msvc_active(options) else []


def _spgo_msvc_lib_flags(options):
    """`lib.exe` needs `/LTCG` to archive the `/GL` objects an SPGO build emits."""
    return ['/LTCG'] if _spgo_msvc_active(options) else []


def _spgo_msvc_link_flags(options):
    """SPGO link flags: `/spdin:<spd>` consumes the sampled profile (optimize),
    `/spgo` emits a fresh `.spd` for the next round (collect). The two compose
    -- passing both --autofdo-generate and --autofdo-use gives a single
    steady-state build that optimizes with last cycle's profile *and* is
    collectable for the next (verified legal on MSVC 14.51, x64 + ARM64), the
    same one-build cadence gcc/clang get. /LTCG is needed whenever a profile is
    consumed."""
    use = getattr(options, 'autofdo-use', None)
    flags = ['/LTCG', '/spdin:' + use] if use else []
    if getattr(options, 'autofdo-generate', False):
        flags.append('/spgo')
    return flags


# --- clang-cl instrumentation (coverage / PGO) -------------------------------
#
# clang-cl keeps cl-style flags for normal compilation (so it reports
# cc_is('msvc') True and rides the Windows rules), but for *instrumentation* it
# takes the LLVM mechanism, not cl.exe's /GL+/LTCG family. The toolchain's
# is_clang_cl() predicate routes it here. See issue #1369. clang-cl is not on
# the CI box, so this path is unit-test-validated + best-effort (the link side
# in particular -- blade links via lld-link directly, not the clang-cl driver).

_clang_cl_profile_runtime_warned = False


def _warn_clang_cl_profile_runtime_missing():
    global _clang_cl_profile_runtime_warned
    if _clang_cl_profile_runtime_warned:
        return
    _clang_cl_profile_runtime_warned = True
    console.warning(
        "clang-cl's profile runtime (clang_rt.profile-*) was not found; "
        'coverage / --profile-generate links may fail to resolve __llvm_profile* '
        'symbols. It ships under <clang>/lib/clang/<ver>/lib/windows.')


def _instrument_clang_cl_compile_flags(toolchain, options):
    """LLVM instrumentation *compile* flags for clang-cl (coverage + PGO).

    Mirrors the gcc/clang path in _get_intrinsic_cc_flags, but emitted into the
    Windows compile rules because clang-cl is cc_is('msvc'). Coverage uses
    gcov-style `--coverage` (so the existing gcovr/llvm-cov flow applies); PGO
    uses `-fprofile-generate` / `-fprofile-use=<merged.profdata>`. See #1369.
    """
    flags = []
    if getattr(options, 'coverage', False):
        flags.append('--coverage')
    gen = _pgo_option(options, 'profile-generate')
    if gen is not None:
        flags.append('-fprofile-generate' + ('=' + gen if gen else ''))
        flags.append('-DBLADE_PGO_GENERATE')
    use = _pgo_option(options, 'profile-use')
    if use is not None:
        profdata = _resolve_clang_profdata(toolchain, use)
        flags.append('-fprofile-use=' + profdata if profdata else '-fprofile-use')
        # Tolerate stale/partial profiles as warnings, not errors.
        flags.append('-Wno-error=profile-instr-out-of-date')
        flags.append('-Wno-error=profile-instr-unprofiled')
    return flags


def _instrument_clang_cl_link_flags(toolchain, options):
    """LLVM instrumentation *link* flags for clang-cl (coverage / PGO-generate).

    Driver flags (`--coverage`, `-fprofile-generate`) don't reach lld-link --
    blade links directly, not through the clang-cl driver. But instrumented
    objects autolink the profile runtime via a `/DEFAULTLIB:clang_rt.profile-*`
    directive, so all lld-link needs is that runtime directory on `/LIBPATH`.
    `--profile-use` reads the profile at compile time and needs nothing here.
    Best-effort: warns once if the runtime dir can't be located. See #1369.
    """
    active = (getattr(options, 'coverage', False)
              or _pgo_option(options, 'profile-generate') is not None)
    if not active:
        return []
    libdir = toolchain.profile_runtime_libdir()
    if not libdir:
        _warn_clang_cl_profile_runtime_missing()
        return []
    return ['/LIBPATH:"%s"' % libdir if ' ' in libdir else '/LIBPATH:%s' % libdir]


class CcRuleGenerator:
    """Generate cc/cuda ninja rules from a RuleContext (see module docstring)."""

    def __init__(self, ctx):
        self._ctx = ctx
        self.build_toolchain = ctx.toolchain
        self.build_accelerator = ctx.accelerator
        self.options = ctx.options
        self.build_dir = ctx.build_dir
        self.command = ctx.command
        self.blade = ctx.blade
        self.__inclusion_wrapper_path = None
        self.__msvc_wrapper_py_path = None
        self.__msvc_link_wrapper_py_path = None
        self.__darwin_ar_wrapper_path = None

    def _add_line(self, line):
        self._ctx.add_line(line)

    def _builtin_command(self, builder, args=''):
        return self._ctx.builtin_command(builder, args)

    def generate_rule(self, name, command, description=None, depfile=None,
                      generator=False, pool=None, restat=False, rspfile=None,
                      rspfile_content=None, deps=None):
        self._ctx.emit_rule(NinjaRule(
            name=name, command=command, description=description, depfile=depfile,
            generator=generator, pool=pool, restat=restat, rspfile=rspfile,
            rspfile_content=rspfile_content, deps=deps))

    def _inclusion_wrapper_script(self):
        """Path to the cc inclusion-stack splitter wrapper, written on first use.

        See `_INCLUSION_WRAPPER_SCRIPT`. Written into the build dir at ninja
        generation time; ninja runs from the workspace root, so the build-dir
        relative path resolves. The script is not a dependency of any edge, so
        rewriting it never triggers a rebuild.
        """
        if self.__inclusion_wrapper_path is None:
            path = os.path.join(self.build_dir, 'cc_wrapper.sh')
            util.write_if_changed(path, _INCLUSION_WRAPPER_SCRIPT)
            self.__inclusion_wrapper_path = path
        return self.__inclusion_wrapper_path

    def _msvc_tee_wrapper_py(self):
        """Path to the MSVC Python stderr-tee wrapper, written on first use."""
        if self.__msvc_wrapper_py_path is None:
            path = os.path.join(self.build_dir, 'cc_wrapper.py')
            util.write_if_changed(path, _MSVC_TEE_WRAPPER_PY)
            self.__msvc_wrapper_py_path = path
        return self.__msvc_wrapper_py_path

    def _msvc_link_wrapper_py(self):
        """Path to the MSVC link-output filter wrapper, written on first use."""
        if self.__msvc_link_wrapper_py_path is None:
            path = os.path.join(self.build_dir, 'link_wrapper.py')
            util.write_if_changed(path, _MSVC_LINK_WRAPPER_PY)
            self.__msvc_link_wrapper_py_path = path
        return self.__msvc_link_wrapper_py_path

    def _darwin_ar_wrapper_sh(self):
        """Path to the macOS archive-output filter wrapper, written on first use."""
        if self.__darwin_ar_wrapper_path is None:
            path = os.path.join(self.build_dir, 'ar_wrapper.sh')
            util.write_if_changed(path, _DARWIN_AR_WRAPPER_SH)
            self.__darwin_ar_wrapper_path = path
        return self.__darwin_ar_wrapper_path

    def _get_intrinsic_cc_flags(self):
        """Get the common c/c++ flags."""
        global_config = config.get_section('global_config')
        cc_config = config.get_section('cc_config')

        cppflags = []
        linkflags = []
        if self.options.m:
            cppflags = ['-m%s' % self.options.m]
            linkflags = ['-m%s' % self.options.m]
        # Add -fno-omit-frame-pointer to optimize mode for easy debugging.
        cppflags += ['-pipe', '-fno-omit-frame-pointer']

        if cc_config["fission"]:
            cppflags += ['-gsplit-dwarf']
            linkflags += ['-Wl,--gdb-index']

        # Debugging information setting
        debug_info_level = global_config['debug_info_level']
        debug_info_options = cc_config['debug_info_levels'][debug_info_level]
        cppflags += debug_info_options

        # Option debugging flags
        if self.options.profile == 'debug':
            cppflags.append('-fstack-protector')
        elif self.options.profile == 'release':
            cppflags.append('-DNDEBUG')

        cppflags += [
            '-D_FILE_OFFSET_BITS=64',
            '-D__STDC_CONSTANT_MACROS',
            '-D__STDC_FORMAT_MACROS',
            '-D__STDC_LIMIT_MACROS',
        ]

        if getattr(self.options, 'gprof', False):
            # gprof's `-pg` instrumentation is only functional on Linux. Darwin
            # clang accepts `-pg` but ignores it (spraying "argument unused"
            # warnings, and there is no gprof tool / gmon.out on macOS); MSVC
            # does not understand it at all. Skip the dead flag elsewhere and
            # warn once instead of letting the toolchain complain per edge.
            if self.build_toolchain.target_os == 'linux':
                cppflags.append('-pg')
                linkflags.append('-pg')
            else:
                _warn_gprof_unsupported(self.build_toolchain.target_os)

        if getattr(self.options, 'coverage', False):
            # `--coverage` is the gcc/clang driver flag (-fprofile-arcs
            # -ftest-coverage). This is the gcc/clang path only -- MSVC
            # toolchains (cl.exe *and* clang-cl) are cc_is('msvc') and never
            # reach here; they take the Windows rules instead. There cl.exe
            # collects coverage at run time (Microsoft.CodeCoverage.Console.exe,
            # see TestRunner), and clang-cl emits `--coverage` from the Windows
            # compile/link rules (is_clang_cl gate). See issue #1369.
            cppflags.append('--coverage')
            linkflags.append('--coverage')

        sanitizers = getattr(self.options, 'sanitizers', None)
        if sanitizers:
            # check_compat ran at the command line (toolchain-independent); only
            # the toolchain-support check needs the resolved toolchain here.
            sanitizer.check_toolchain(sanitizers, self.build_toolchain)
            # Compile-side instrumentation rides the overridable `${sanitize}`
            # ninja var (emitted by _generate_cc_vars) so a per-target
            # sanitize=False can blank it for that target's edges -- the same
            # mechanism the MSVC path uses, instead of subtracting -fno-sanitize.
            # Only the link flags (which pull in the runtime) stay global.
            linkflags += sanitizer.link_flags(sanitizers)

        # PGO -- see the module-level "PGO" note. This is the gcc/clang path
        # (MSVC uses /GL + /LTCG:PG* in the Windows rules and never gets here).
        pgo_gen = _pgo_option(self.options, 'profile-generate')
        if pgo_gen is not None:
            # gcc and clang share this spelling. The runtime (libgcov /
            # clang's profile runtime) is pulled in at link, so the flag
            # rides both cppflags and linkflags.
            flag = '-fprofile-generate' + ('=' + pgo_gen if pgo_gen else '')
            cppflags.append(flag)
            linkflags.append(flag)
            # Only the instrument build defines BLADE_PGO_GENERATE -- it lets
            # source flush profile data (__llvm_profile_write_file / __gcov_dump)
            # in long-running/forking servers. The use build behaves like a
            # normal release, so it gets no PGO define (avoid divergence).
            cppflags.append('-DBLADE_PGO_GENERATE')

        pgo_use = _pgo_option(self.options, 'profile-use')
        if pgo_use is not None:
            if self.build_toolchain.cc_is('clang'):
                # clang rejects -fprofile-correction and needs a *merged*
                # .profdata file (blade merges the .profraw for you).
                profdata = _resolve_clang_profdata(self.build_toolchain, pgo_use)
                cppflags.append('-fprofile-use=' + profdata if profdata
                                else '-fprofile-use')
                # Tolerate stale/partial profiles as warnings, not errors --
                # the clang analogues of gcc's -Wno-error=coverage-mismatch.
                cppflags.append('-Wno-error=profile-instr-out-of-date')
                cppflags.append('-Wno-error=profile-instr-unprofiled')
            else:  # gcc
                cppflags.append('-fprofile-use=' + pgo_use if pgo_use
                                else '-fprofile-use')
                cppflags.append('-fprofile-correction')
                cppflags.append('-Wno-error=coverage-mismatch')

        # AutoFDO (sample-based PGO) -- see the module-level "AutoFDO" note.
        # gcc/clang path; native MSVC never reaches here -- it drives SPGO in the
        # Windows rules (_spgo_msvc_* flags); clang-cl warns there. Linux-only in
        # practice for gcc/clang (perf+LBR), but the flags are portable, so
        # collection-vs-use platform is the user's concern.
        if getattr(self.options, 'autofdo-generate', False):
            # Collection build: a normal optimized build plus the debug info
            # that lets samples map back to source. clang adds function/inlining
            # attribution (-fdebug-info-for-profiling, which augments line
            # tables); gcc relies on its debug line tables.
            if self.build_toolchain.cc_is('clang'):
                cppflags.append('-fdebug-info-for-profiling')
                cppflags.append('-funique-internal-linkage-names')
            # AutoFDO is useless without line tables to map samples to. If the
            # configured debug level emits none (e.g. debug_info_level=no), add
            # minimal line tables (clang -gmlt / gcc -g1) so collection works;
            # never touch an existing -g -- a later -gmlt would *downgrade* it.
            if not _has_line_table_debug(debug_info_options):
                flag = '-gmlt' if self.build_toolchain.cc_is('clang') else '-g1'
                cppflags.append(flag)
                _notice_autofdo_debug_added(flag)
            # No define: AutoFDO samples a *normal* binary (no instrumentation
            # runtime to flush), and the collection build should stay identical
            # to what ships -- that's the whole point of "profile what you ship".

        autofdo_use = getattr(self.options, 'autofdo-use', None)
        if autofdo_use:
            profile = _resolve_autofdo_profile(autofdo_use)
            if profile:
                if self.build_toolchain.cc_is('clang'):
                    cppflags.append('-fprofile-sample-use=' + profile)
                else:  # gcc
                    cppflags.append('-fauto-profile=' + profile)
                # No define: the AutoFDO use build is a normal optimized binary.

        # Recover -fPIE-level optimization under -fPIC: tell the compiler the
        # current TU's symbol definitions aren't interposable, so it can
        # reference/inline its own globals directly instead of going through
        # the GOT. Default-on (cc_config.no_semantic_interposition defaults
        # to True); users with plugin frameworks that LD_PRELOAD-override
        # exe-internal symbols opt out by setting it to False.
        #
        # GCC-only: Clang (incl. Apple Clang) is already non-interposing by
        # default, so emitting the flag is redundant -- and on the C++ driver
        # specifically Clang fires `-Wunused-command-line-argument`, which
        # `-Werror` projects then refuse to compile. filter_cc_flags can't
        # screen this out because it probes in C, where Clang stays silent.
        # See issue #1258.
        if (cc_config['no_semantic_interposition']
                and self.build_toolchain.cc_is('gcc')):
            cppflags.append('-fno-semantic-interposition')

        # macOS / Xcode 15+ ld64 warns "ignoring duplicate libraries" when
        # several objects each carry an embedded `-lc++` auto-link option
        # (LC_LINKER_OPTION) -- benign noise inherent to compiling C++ on
        # macOS, and not something on blade's command line to dedup away.
        # Silence it with ld64's own flag, but only when the linker accepts
        # it (older ld64 doesn't know the flag and doesn't emit the warning).
        if self.build_toolchain.target_os == 'darwin':
            no_warn_dup = '-Wl,-no_warn_duplicate_libraries'
            if self.build_toolchain.supports_link_flag(no_warn_dup):
                linkflags.append(no_warn_dup)

        cppflags = self.build_toolchain.filter_cc_flags(cppflags)
        return cppflags, linkflags

    def _get_warning_flags(self):
        """Get the warning flags."""
        cc_config = config.get_section('cc_config')
        cuda_config = config.get_section('cuda_config')
        cppflags = cc_config['warnings']
        cxxflags = cc_config['cxx_warnings']
        cflags = cc_config['c_warnings']
        cuflags = cuda_config['cu_warnings']

        filtered_cppflags = self.build_toolchain.filter_cc_flags(cppflags)
        filtered_cxxflags = self.build_toolchain.filter_cc_flags(cxxflags, 'c++')
        filtered_cflags = self.build_toolchain.filter_cc_flags(cflags, 'c')

        return filtered_cppflags, filtered_cxxflags, filtered_cflags, cuflags

    def generate_cc_rules(self):
        if self.build_toolchain.cc_is('msvc'):
            self._generate_windows_cc_rules()
        else:
            cc, cxx, ld = self.build_accelerator.get_cc_commands()
            cppflags, linkflags = self._get_intrinsic_cc_flags()
            self._generate_cc_compile_rules(cc, cxx, cppflags)
            self._generate_cc_inclusion_check_rule()
            self._generate_cc_check_undefined_rule()
            self._generate_cc_ar_rules()
            self._generate_cc_link_rules(ld, linkflags)
            # ${strip_options} is set per target (defaults to --strip-unneeded;
            # see CcTarget._strip_command_options), so each binary/plugin can
            # control what `strip` removes (issue #694).
            self.generate_rule(name='strip',
                               command='strip ${strip_options} -o ${out} ${in}',
                               description='STRIP ${out}')

    def _generate_windows_cc_rules(self):
        """Generate Windows/MSVC-specific CC rules."""
        cc, cxx, ld = self.build_accelerator.get_cc_commands()
        self._generate_windows_cc_vars()
        self._generate_windows_cc_compile_rules(cc, cxx)
        self._generate_windows_asm_rule()
        self._generate_cc_inclusion_check_rule()
        self._generate_cc_check_undefined_rule()
        self._generate_windows_ar_rules()
        self._generate_windows_link_rules()

    def _generate_windows_cc_vars(self):
        """Generate Windows-specific CC variables."""
        windows_config = config.get_section('msvc_config')
        cc_config = config.get_section('cc_config')
        # Combine windows_config warnings with filtered cc_config warnings
        c_warnings = (windows_config['warnings'] +
                      self.build_toolchain.filter_cc_flags(cc_config['c_warnings'], 'c'))
        cxx_warnings = (windows_config['warnings'] +
                        self.build_toolchain.filter_cc_flags(cc_config['cxx_warnings'], 'c++'))
        self._add_line(textwrap.dedent('''\
                c_warnings = %s
                cxx_warnings = %s
                ''') % (' '.join(c_warnings), ' '.join(cxx_warnings)))

        # Sanitizer instrumentation (issue #1038) as an overridable variable: the
        # global default is the active set's compile flags (/fsanitize=address),
        # and a per-target `sanitize=False` blanks it on that target's edges --
        # cl has no `-fno-sanitize` to subtract per file. The compile rules below
        # reference `${sanitize}`. (check_compat ran at the command line.)
        sanitizers = getattr(self.options, 'sanitizers', None)
        sanitize = ''
        if sanitizers:
            sanitizer.check_toolchain(sanitizers, self.build_toolchain)
            sanitize = ' '.join(sanitizer.msvc_compile_flags(sanitizers))
        self._add_line('sanitize = %s\n' % sanitize)

    def _generate_windows_cc_compile_rules(self, cc, cxx):
        """Generate Windows CC compilation rules."""
        windows_config = config.get_section('msvc_config')
        cc_config = config.get_section('cc_config')

        # Combine windows_config flags with filtered cc_config flags.
        # cc_config flags (from BLADE_ROOT) typically use GCC syntax and get
        # mapped/filtered by the toolchain (e.g. -std=c++17 → /std:c++17).
        filtered_cc_cflags = self.build_toolchain.filter_cc_flags(cc_config['cflags'], 'c')
        filtered_cc_cxxflags = self.build_toolchain.filter_cc_flags(cc_config['cxxflags'], 'c++')
        filtered_cc_cppflags = self.build_toolchain.filter_cc_flags(cc_config['cppflags'])

        cppflags = windows_config['cppflags'] + filtered_cc_cppflags
        cflags = windows_config['cflags'] + filtered_cc_cflags
        cxxflags = windows_config['cxxflags'] + filtered_cc_cxxflags
        # System includes (MSVC + Windows SDK) discovered by the toolchain,
        # then user-specified extra_incs, then build directory.
        system_includes = self.build_toolchain.get_system_include_paths()
        includes = system_includes + cc_config['extra_incs'] + ['.', self.build_dir]
        # MSVC accepts /I"path with spaces" (quoted, no space after /I).
        # Use a helper that quotes paths containing spaces.
        def _quote_if_needed(p):
            return f'/I"{p}"' if ' ' in p else f'/I{p}'
        include_flags = ' '.join([_quote_if_needed(inc) for inc in includes])

        optimize_flags = windows_config['optimize']
        optimize = ' '.join(optimize_flags.get(self.options.profile, []))

        # Runtime library (CRT) tracks the build profile unless the user pinned
        # one in cc_config: debug -> /MDd, release -> /MD. default_linked_libs
        # reads the actually-selected variant back from /DEFAULTLIB directives.
        crt_flags = ('/MD', '/MDd', '/MT', '/MTd', '/LD', '/LDd')
        if not any(f in crt_flags for f in cppflags + cflags + cxxflags):
            cppflags = ['/MDd' if self.options.profile == 'debug' else '/MD'] + cppflags

        # Debug info (previously unwired on MSVC, so -p debug produced no PDB).
        # /Z7 embeds CodeView in each .obj -- parallel-safe under ninja, unlike
        # the PDB-server /Zi; the matching linker /DEBUG is added in the link rule.
        global_config = config.get_section('global_config')
        msvc_debug = windows_config['debug_info_levels'][global_config['debug_info_level']]
        cppflags = cppflags + msvc_debug

        # Instrumentation (#1369): clang-cl takes the LLVM mechanism (gcov-style
        # --coverage, -fprofile-* PGO); native cl.exe uses /GL + LTCG PGO (and
        # collects coverage at run time, not via a compile flag).
        if self.build_toolchain.is_clang_cl():
            cppflags = cppflags + _instrument_clang_cl_compile_flags(
                self.build_toolchain, self.options)
            # clang-cl can't do sample PGO on Windows (SPGO is cl-only, AutoFDO
            # needs perf); warn and skip if --autofdo-* was passed (#1372).
            if _autofdo_active(self.options):
                _warn_autofdo_clang_cl()
        else:
            # PGO (#1366): `/GL` on every compile when a profile mode is active,
            # so the link can do LTCG instrumentation / optimization.
            cppflags = cppflags + _pgo_msvc_compile_flags(self.options)
            # SPGO (#1372): native cl.exe sample PGO also needs /GL (modes are
            # mutually exclusive, so at most one of these adds it).
            cppflags = cppflags + _spgo_msvc_compile_flags(self.options)
            # SPGO correlates samples via PDB symbols; like AutoFDO's line
            # tables, guarantee /Z7 for the collection build if debug_info_level
            # emits none (don't override an existing /Z7//Zi). Notify once.
            if getattr(self.options, 'autofdo-generate', False) \
                    and not _has_msvc_debug_info(msvc_debug):
                cppflags = cppflags + ['/Z7']
                _notice_autofdo_debug_added('/Z7')

        # The Python stderr-tee wrapper captures /showIncludes output and tees
        # it to both stderr (for Ninja's deps=msvc) and the inclusion stack
        # file (for inclusion checking).
        py = sys.executable
        wrapper = self._msvc_tee_wrapper_py()
        template = '"%s" -B %s ${inclusion_stack} -- ' % (py, wrapper)

        cc_command = template + ('"%s" /nologo /c /showIncludes %s %s %s %s /Fo${out} ${c_warnings} /external:W0 ${cppflags} ${sanitize} ${includes} ${extra_compile_flags} ${in}' % (
            cc, optimize, ' '.join(cppflags), ' '.join(cflags), include_flags))
        self.generate_rule(name='cc',
                           command=cc_command,
                           description='CC ${in}',
                           deps='msvc',
                           restat=True)

        cxx_command = template + ('"%s" /nologo /c /showIncludes %s %s %s %s /Fo${out} ${cxx_warnings} /external:W0 ${cppflags} ${sanitize} ${includes} ${extra_compile_flags} ${in}' % (
            cxx, optimize, ' '.join(cppflags), ' '.join(cxxflags), include_flags))
        self.generate_rule(name='cxx',
                           command=cxx_command,
                           description='CXX ${in}',
                           deps='msvc',
                           restat=True)

        # For cxxhdrs: use /showIncludes to generate inclusion info for header
        # files. /P preprocesses (like GCC -E), /Tp forces C++ treatment of .h.
        # The Python wrapper captures /showIncludes to ${out} (.incstk file);
        # /Fi writes the preprocessed body to ${out}.pre.
        hdrs_template = '"%s" -B %s ${out} -- ' % (py, wrapper)
        hdrs_command = hdrs_template + ('"%s" /nologo /P /Tp${in} /showIncludes %s /external:W0 ${cppflags} ${includes} %s %s %s /Fi${out}.pre' % (
            cxx, optimize, ' '.join(cppflags), ' '.join(cxxflags), include_flags))
        self.generate_rule(name='cxxhdrs',
                           command=hdrs_command,
                           description='CXX HDRS ${in}',
                           deps='msvc',
                           restat=True)

    def _generate_windows_asm_rule(self):
        """Generate the MSVC assembler (``ml64`` / ``ml``) rule for ``.asm``.

        ``cl.exe`` cannot assemble MASM source; ``.asm`` files must go through
        ``ml64.exe`` (x64) / ``ml.exe`` (x86), resolved by the toolchain as the
        ``'as'`` tool. ``CcTarget._get_rule_from_suffix`` routes ``.asm`` here on
        MSVC. Per-target inc dirs ride on ``${includes}`` (already ``/I`` form
        on MSVC) and per-target asm flags on ``${extra_compile_flags}`` (from
        ``extra_asflags``). No ``/showIncludes`` / inclusion-stack plumbing --
        assembly is not header-dependency-checked.
        """
        asm = self.build_toolchain.tool('as')
        if not asm:
            return
        self.generate_rule(
            name='as',
            command='"%s" /nologo /c /Fo${out} ${extra_compile_flags} '
                    '${includes} ${in}' % asm,
            description='AS ${in}')

    def _generate_windows_ar_rules(self):
        """Generate Windows static library rules."""
        cc_lib = config.get_section('cc_library_config')
        deterministic = cc_lib.get('deterministic', False)
        thin = cc_lib.get('thin', False)
        if thin:
            console.warning('cc_library_config.thin=True has no effect on MSVC (lib.exe '
                            'does not support thin archives)')
        ar = self.build_accelerator.get_ar_command()
        brepro = ' /Brepro' if deterministic else ''
        # PGO (#1366): lib.exe needs /LTCG to archive the /GL objects a native
        # MSVC PGO build emits. clang-cl PGO objects are ordinary objects (LLVM
        # instrumentation, not /GL), so llvm-lib needs nothing extra. (#1369)
        if self.build_toolchain.is_clang_cl():
            pgo = ''
        else:
            # /LTCG to archive /GL objects from either native PGO or SPGO
            # (mutually exclusive modes, so at most one contributes).
            pgo = ''.join(' ' + f for f in (_pgo_msvc_lib_flags(self.options) +
                                            _spgo_msvc_lib_flags(self.options)))
        self.generate_rule(name='ar',
                           command=f'{ar} /nologo{brepro}{pgo} /out:${{out}} ${{in}}',
                           description='LIB ${out}')

    def _generate_windows_link_rules(self):
        """Generate Windows linking rules."""
        _, _, ld = self.build_accelerator.get_cc_commands()
        windows_config = config.get_section('msvc_config')
        cc_config = config.get_section('cc_config')
        # Combine windows_config linkflags with filtered cc_config linkflags
        linkflags = (windows_config['linkflags'] +
                     self.build_toolchain.filter_cc_flags(cc_config['linkflags']))

        # /DEBUG emits a PDB from the /Z7 CodeView in the objects (matches the
        # compiler debug-info level). For release, also dead-strip and fold
        # (/OPT:REF,/OPT:ICF) and disable incremental linking that /DEBUG would
        # otherwise turn on, keeping release binaries lean and deterministic.
        global_config = config.get_section('global_config')
        # SPGO needs a PDB to correlate samples; force /DEBUG for the collection
        # build even when debug_info_level=no (paired with the /Z7 added on the
        # compile side). #1372.
        spgo_collect = (not self.build_toolchain.is_clang_cl()
                        and getattr(self.options, 'autofdo-generate', False))
        if global_config['debug_info_level'] != 'no' or spgo_collect:
            linkflags = linkflags + ['/DEBUG']
        if self.options.profile == 'release':
            linkflags = linkflags + ['/OPT:REF', '/OPT:ICF', '/INCREMENTAL:NO']

        # Sanitizers (issue #1038): ASan needs incremental linking off (the
        # runtime libs auto-link via /DEFAULTLIB). Harmless if already added
        # above for release.
        sanitizers = getattr(self.options, 'sanitizers', None)
        if sanitizers:
            for flag in sanitizer.msvc_link_flags(sanitizers):
                if flag not in linkflags:
                    linkflags = linkflags + [flag]

        # Instrumentation (#1369): clang-cl pulls in the LLVM profile runtime via
        # /LIBPATH (objects autolink clang_rt.profile); native cl.exe uses LTCG
        # PGO. LTCG is incompatible with incremental linking, so force it off (a
        # release build already did). The .pgd is auto-named from /out, so each
        # binary gets its own profile in the shared build_*_pgo dir.
        if self.build_toolchain.is_clang_cl():
            for flag in _instrument_clang_cl_link_flags(self.build_toolchain,
                                                        self.options):
                if flag not in linkflags:
                    linkflags = linkflags + [flag]
        else:
            # Native cl.exe: instrumentation PGO (/GENPROFILE|/USEPROFILE) or
            # SPGO sample PGO (/spgo | /LTCG /spdin:). Mutually exclusive, so at
            # most one is non-empty. Both need LTCG -> incremental linking off.
            pgo_link = (_pgo_msvc_link_flags(self.options) or
                        _spgo_msvc_link_flags(self.options))
            if pgo_link:
                for flag in pgo_link + ['/INCREMENTAL:NO']:
                    if flag not in linkflags:
                        linkflags = linkflags + [flag]

        # System library paths (MSVC + Windows SDK) discovered by the toolchain
        lib_paths = self.build_toolchain.get_system_lib_paths()
        def _libpath_flag(p):
            if ' ' in p:
                return '/LIBPATH:"%s"' % p
            return '/LIBPATH:%s' % p
        libpath_flags = ' '.join([_libpath_flag(p) for p in lib_paths])

        self._add_line('linkflags = %s\n' % ' '.join(linkflags))

        # MSVC + Windows SDK bin dirs, so link.exe can find tools it spawns by
        # name (e.g. mt.exe in the SDK bin for /MANIFEST:EMBED -- a different dir
        # from link.exe). blade calls link by absolute path, but link resolves
        # its own sub-tools via PATH; the link wrapper prepends these.
        tool_dirs = []
        for _key in ('ld', 'cc', 'rc', 'as'):
            _t = self.build_toolchain.tool(_key)
            if _t:
                _d = os.path.dirname(_t)
                if _d and _d not in tool_dirs:
                    tool_dirs.append(_d)
        prepend_path = os.pathsep.join(tool_dirs)

        link_wrapper = self._msvc_link_wrapper_py()
        wrap = f'"{sys.executable}" -B {link_wrapper} --prepend-path "{prepend_path}" --'

        self.generate_rule(name='link',
                           command=f'{wrap} {ld} /nologo /out:${{out}} ${{linkflags}} {libpath_flags} ${{target_linkflags}} ${{extra_linkflags}} ${{in}}',
                           description='LINK EXE ${out}')

        # ${dllflags} carries the per-target `/DEF:<def> /IMPLIB:<implib>` for a
        # cc_library DLL (empty for other solink edges, e.g. cc_plugin). The
        # `.def` (auto-export, COMDAT-filtered) makes the DLL export its symbols
        # without source annotations; the import library is what dependents link.
        # Route the DLL link through the same Python wrapper, which drops
        # link.exe's redundant "Creating library ... and object ..." notice (the
        # import lib is always created for a DLL, so it always prints) and
        # prepends the tool dirs to PATH. See `_MSVC_LINK_WRAPPER_PY`.
        # restat: link.exe doesn't rewrite the import library (`/IMPLIB`) when
        # the DLL's exports are unchanged, so its mtime can lag; re-stat outputs
        # after linking so an unchanged DLL/implib prunes dependent relinks.
        self.generate_rule(name='solink',
                           command=f'{wrap} {ld} /nologo /DLL ${{dllflags}} /out:${{out}} ${{linkflags}} {libpath_flags} ${{target_linkflags}} ${{extra_linkflags}} ${{in}}',
                           description='LINK DLL ${out}',
                           restat=True)

        # Synthesize the auto-export `.def` from the object files (see the
        # `cc_windef` builtin tool). Windows-only; nothing emits this edge
        # elsewhere.
        # restat: the `.def` is written write-if-changed, so when the export set
        # is unchanged ninja keeps its old mtime and prunes the downstream DLL
        # relink (the import lib stays newer than the def). See the
        # incremental-build fix / issue #1161 pattern.
        self.generate_rule(name='cc_windef',
                           command=self._builtin_command('cc_windef', '${defflags} ${out} ${in}'),
                           description='CC WINDEF ${out}',
                           restat=True)

    def _generate_cc_vars(self):
        warnings, cxx_warnings, c_warnings, cu_warnings = self._get_warning_flags()
        c_warnings += warnings
        cxx_warnings += warnings
        cu_warnings += ['-Xcompiler %s' % warning for warning in cxx_warnings]
        # optimize_flags is need for `always_optimize`
        optimize_flags = config.get_item('cc_config', 'optimize')
        optimize = '$optimize_flags' if self.options.profile == 'release' else ''
        # Sanitizer instrumentation (issue #1038) as an overridable variable:
        # the default is the active set's compile flags, and a per-target
        # sanitize=False blanks `${sanitize}` on that target's edges (see
        # CcTarget._get_cc_vars). The set is already validated in
        # _get_intrinsic_cc_flags, which runs first.
        sanitizers = getattr(self.options, 'sanitizers', None)
        sanitize = ' '.join(sanitizer.compile_flags(sanitizers)) if sanitizers else ''
        self._add_line(textwrap.dedent('''\
                c_warnings = %s
                cxx_warnings = %s
                cu_warnings = %s
                optimize_flags = %s
                optimize = %s
                sanitize = %s
                ''') % (' '.join(c_warnings), ' '.join(cxx_warnings),
                        ' '.join(cu_warnings),
                        ' '.join(optimize_flags), optimize, sanitize))

    def _generate_cc_compile_rules(self, cc, cxx, cppflags):
        self._generate_cc_vars()

        cc_config = config.get_section('cc_config')
        cflags, cxxflags = cc_config['cflags'], cc_config['cxxflags']
        cppflags = cc_config['cppflags'] + cppflags
        includes = cc_config['extra_incs']
        includes = includes + ['.', self.build_dir]
        includes = ' '.join(['-I%s' % inc for inc in includes])

        template = self._cc_compile_command_wrapper_template('${inclusion_stack}')

        cc_command = ('%s -o ${out} -MMD -MF ${out}.d -c -fPIC %s %s ${optimize} '
                      '${c_warnings} ${cppflags} ${sanitize} ${extra_compile_flags} %s ${includes} ${in}') % (
                              cc, ' '.join(cflags), ' '.join(cppflags), includes)
        self.generate_rule(name='cc',
                           command=template % cc_command,
                           description='CC ${in}',
                           depfile='${out}.d',
                           deps='gcc',
                           # restat lets ninja prune the inclusion check when the
                           # per-source `${inclusion_stack}` (`<src>.incstk`) is
                           # unchanged (written write-if-changed). See issue #1161.
                           restat=True)

        cxx_command = ('%s -o ${out} -MMD -MF ${out}.d -c -fPIC %s %s ${optimize} '
                       '${cxx_warnings} ${cppflags} ${sanitize} ${extra_compile_flags} %s ${includes} ${in}') % (
                               cxx, ' '.join(cxxflags), ' '.join(cppflags), includes)
        self.generate_rule(name='cxx',
                           command=template % cxx_command,
                           description='CXX ${in}',
                           depfile='${out}.d',
                           deps='gcc',
                           restat=True)  # see the cc rule / issue #1161

        self.generate_rule(name='secretcc',
                           command=template % (cc_config['secretcc'] + ' ' + cxx_command),
                           description='SECRET CC ${in}',
                           depfile='${out}.d',
                           restat=True)  # see the cc rule / issue #1161

        self._generate_cc_hdrs_rule(cc, cxx, cppflags, cflags, cxxflags, includes)

    def _generate_cc_hdrs_rule(self, cc, cxx, cppflags, cflags, cxxflags, includes):
        """
        Generate inclusion stack file for header file to check dependency missing.
        See the '-H' in https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html for details.
        """
        self.generate_rule(name='cxxhdrs',
                           command=self._hdrs_command(cxx, cxxflags, cppflags, includes),
                           depfile='${out}.d', deps='gcc',
                           # restat lets ninja prune the inclusion check when the
                           # header's inclusion stack is unchanged (the wrapper
                           # writes ${out} write-if-changed). See issue #1161.
                           restat=True,
                           description='CXX HDRS ${in}')

    def _hdrs_command(self, cc, flags, cppflags, includes):
        """Build the bare preprocess command for a header's inclusion file.

        Run by the `hdrs`-mode wrapper script (see `_INCLUSION_WRAPPER_SCRIPT`);
        `${out}` is the inclusion (`.incstk`) file. `-H` is what the wrapper's
        awk extracts -- without it the inclusion stack is never emitted and the
        `.incstk` ends up empty, silently breaking checks for header-only
        libraries. See issue #1169.
        """
        cmd = ('%s -o /dev/null -E -MMD -MF ${out}.d %s %s -w ${cppflags} %s ${includes} ${in} -H' % (
            cc, ' '.join(flags), ' '.join(cppflags), includes))
        return 'sh %s hdrs ${out} %s' % (self._inclusion_wrapper_script(), cmd)

    def _generate_cc_inclusion_check_rule(self):
        self.generate_rule(name='ccincchk',
                           command=self._builtin_command('cc_inclusion_check'),
                           description='CC INCLUSION CHECK ${in}')

    def _generate_cc_check_undefined_rule(self):
        # Two cooperating rules implement the static dep-completeness check
        # (issue #1225) and keep its total nm work linear in the dep graph,
        # not quadratic:
        #
        # 1. ``ccsyms`` runs ``nm`` on a single archive once and emits a
        #    sidecar ``<archive>.syms`` file with two sections (#U undefined
        #    externals, #D defined externals). One node per archive, ninja
        #    fans them out alongside the corresponding ``ar`` rules. Each
        #    archive is nm'd exactly once per build regardless of how many
        #    cc_libraries depend on it.
        # 2. ``ccchkund`` consumes the ``.syms`` files (target's own + each
        #    transitive dep's + the system-symbols caches) and decides if
        #    the target's undefined set is closed. Pure file reads and set
        #    arithmetic; no ``nm`` at check time.
        #
        # Previously this was a single ``ccchkund`` rule that took raw
        # ``.a`` archives and re-ran ``nm`` on every dep for every target's
        # check, making the total cost O(targets × deps) and scaling badly
        # on diamond-shaped dep graphs.
        # On MSVC the archives are COFF .lib files and nm is unavailable, so the
        # emit-syms tool reads symbols with dumpbin instead; pass its path.
        syms_args = '${out} ${in}'
        if self.build_toolchain.cc_is('msvc'):
            syms_args += ' --dumpbin="%s"' % self.build_toolchain.dumpbin
        self.generate_rule(name='ccsyms',
                           command=self._builtin_command('cc_emit_syms', syms_args),
                           description='CC SYMS ${in}')
        # Single batch rule: ``${in}`` is the manifest JSON (built by
        # BuildManager after all cc_libraries have generated), ``${out}``
        # is the project-wide stamp file. The ``.syms`` files referenced
        # by the manifest are pulled in as implicit deps by the rule the
        # batch emitter registers (each .syms is also an explicit input
        # there, so ninja still re-runs the batch when any archive's
        # symbol set changes).
        # Severity is project-global, baked into the rule command at generate
        # time so a config flip triggers a normal ninja regen (the build.ninja
        # text changes -> ninja reloads). 'warning' (default while the check is
        # experimental) logs findings but doesn't fail the build; 'error' fails.
        severity = config.get_item('cc_library_config', 'check_undefined_severity')
        batch_args = '${out} ${in} --severity=%s' % severity
        self.generate_rule(name='ccchkund_batch',
                           command=self._builtin_command(
                               'cc_check_undefined_batch', batch_args),
                           description='CC CHECK UNDEFINED [batch]')

    def _generate_cc_ar_rules(self):
        cc_lib = config.get_section('cc_library_config')
        deterministic = cc_lib.get('deterministic', False)
        thin = cc_lib.get('thin', False)
        target_os = self.build_toolchain.target_os

        if target_os == 'darwin':
            if thin:
                console.error('cc_library_config.thin=True is not supported on macOS '
                              '(Apple ar does not support thin archives)')
            # Route the archive through a shell wrapper that drops Apple's benign
            # "table of contents is empty" warning for symbol-less libraries
            # (no suppression flag exists for it). See _DARWIN_AR_WRAPPER_SH.
            wrap = f'/bin/bash {self._darwin_ar_wrapper_sh()}'
            if deterministic:
                command = (f'rm -f $out; {wrap} libtool -static '
                           '-no_warning_for_no_symbols -o $out $in')
            else:
                ar = self.build_accelerator.get_ar_command()
                command = f'rm -f $out; {wrap} {ar} rcs $out $in'
        elif target_os == 'linux':
            ar = self.build_accelerator.get_ar_command()
            extra = ''
            if deterministic:
                extra += 'D'
            if thin:
                extra += 'T'
            command = f'rm -f $out; {ar} rcs{extra} $out $in'
        else:
            arflags = ''.join(cc_lib.get('arflags', ['rcs']))
            ar = self.build_accelerator.get_ar_command()
            command = f'rm -f $out; {ar} {arflags} $out $in'

        self.generate_rule(name='ar', command=command, description='AR ${out}')

    def _generate_cc_link_rules(self, ld, linkflags):
        self._add_line('linkflags = %s' % ' '.join(config.get_item('cc_config', 'linkflags')))
        self._add_line('intrinsic_linkflags = %s' % ' '.join(linkflags))
        # PIE posture for the executable link (see cc_config.pie, issue #1258).
        # Linux only -- macOS executables are PIE by default and ld64 removed
        # -no_pie in recent versions; MSVC has no PIC/PIE concept. The flag is
        # emitted as its own ninja variable so it lands only on the `link`
        # rule, not `solink` (a shared library + -pie is contradictory and
        # GCC/ld will error or warn).
        pie_flag = ''
        if self.build_toolchain.target_os == 'linux':
            pie = config.get_item('cc_config', 'pie')
            if pie == 'yes':
                pie_flag = '-pie'
            elif pie == 'no':
                pie_flag = '-no-pie'
        self._add_line('pie_flag = %s\n' % pie_flag)

        link_jobs = config.get_item('link_config', 'link_jobs')
        if link_jobs:
            link_jobs = min(link_jobs, self.blade.build_jobs_num())
            console.info('Adjust parallel link jobs number to %s' % link_jobs)
            pool = 'link_pool'
            self._add_line(textwrap.dedent('''\
                    pool %s
                      depth = %s''') % (pool, link_jobs))
        else:
            pool = None

        # Linking might have a lot of object files exceeding maximal length of a bash command line.
        # Using response file can resolve this problem.
        # Refer to: https://ninja-build.org/manual.html
        # Note: `${pie_flag}` is on the executable `link` rule only (it's a
        # no-op when cc_config.pie == 'auto', the project-wide default).
        link_args = '-o ${out} ${intrinsic_linkflags} ${linkflags} @${out}.rsp ${extra_linkflags}'
        self.generate_rule(name='link',
                           command=ld + ' ${pie_flag} ' + link_args,
                           rspfile='${out}.rsp',
                           rspfile_content='${target_linkflags} ${in}',
                           description='LINK BINARY ${out}',
                           pool=pool)
        self.generate_rule(name='solink',
                           command=ld + ' -shared ' + link_args,
                           rspfile='${out}.rsp',
                           rspfile_content='${target_linkflags} ${in}',
                           description='LINK SHARED ${out}',
                           pool=pool)
        self.generate_rule(name='dwp',
                           command=self._builtin_command('dwp', '${out} @${out}.rsp'),
                           rspfile='${out}.rsp',
                           rspfile_content='${in}',
                           description='DWP ${out}',
                           pool=pool)
        # macOS-only: translate a GNU-ld export_map (--version-script) into
        # ld64's native -exported_symbols_list. See the `cc_macos_exports`
        # builtin tool. restat=True so that an unchanged exports list prunes
        # the dependent dylib relink, matching the cc_windef pattern.
        if self.build_toolchain.target_os == 'darwin':
            self.generate_rule(
                name='cc_macos_exports',
                command=self._builtin_command(
                    'cc_macos_exports', '${out} ${export_map} ${in}'),
                description='MAC EXPORTS ${out}',
                restat=True)

    def _cc_compile_command_wrapper_template(self, inclusion_stack_file, cuda=False):
        """Calculate the cc compile command wrapper template.

        Returns a template whose single `%s` is the raw compile command. The
        wrapper script runs it, then splits gcc's `-H` inclusion stack into
        *inclusion_stack_file* (see `_inclusion_wrapper_script`).
        """
        # When dumping compdb, a raw compile command without wrapper should be generated,
        # otherwise some tools can't handle it.
        if self.command == 'dump' and self.options.dump_compdb:
            return '%s'

        print_header_option = '-Xcompiler -H' if cuda else '-H'
        return 'sh %s compile %s %%s %s' % (
            self._inclusion_wrapper_script(), inclusion_stack_file, print_header_option)

    def generate_cuda_rules(self):
        if self.build_toolchain.cc_is('msvc'):
            self._generate_msvc_cuda_rules()
        else:
            self._generate_gcc_cuda_rules()

    def _generate_gcc_cuda_rules(self):
        nvcc_cmd = '${cmd}'

        cc_config = config.get_section('cc_config')
        cuda_config = config.get_section('cuda_config')
        cxxflags = cc_config['cxxflags']
        cppflags, _ = self._get_intrinsic_cc_flags()
        # cc/cxx carry sanitizer instrumentation via the overridable ${sanitize}
        # var (so per-target opt-out can blank it); the cuda rule has no such var,
        # so fold the compile flags in here directly -- cuda has no per-target
        # opt-out, so it just always instruments under --sanitizer (as before).
        sanitizers = getattr(self.options, 'sanitizers', None)
        if sanitizers:
            cppflags = cppflags + sanitizer.compile_flags(sanitizers)
        cppflags = cc_config['cppflags'] + cppflags
        cxxflags = ['-Xcompiler %s' % flag for flag in cxxflags]
        cppflags = ['-Xcompiler %s' % flag for flag in cppflags]
        cuflags = cuda_config['cuflags']
        includes = cc_config['extra_incs']
        includes = includes + ['.', self.build_dir]
        includes = ' '.join(['-I%s' % inc for inc in includes])

        template = self._cc_compile_command_wrapper_template('${inclusion_stack}', cuda=True)

        _, cxx, _ = self.build_accelerator.get_cc_commands()
        cu_command = '%s -ccbin "%s" -o ${out} -MMD -MF ${out}.d ' \
            '-Xcompiler -fPIC %s %s %s ${optimize} ${cu_warnings} ' \
            '%s ${includes} ${cppflags} ${cuflags} -c ${in}' % (
                nvcc_cmd, cxx, ' '.join(cxxflags), ' '.join(cppflags),
                ' '.join(cuflags), includes)
        self.generate_rule(
            name='cudacc',
            command=template % cu_command,
            description='CUDA LIBRARY ${in}',
            depfile='${out}.d',
            deps='gcc',
        )

        # CUDA linking might have a lot of input files exceeding maximal length of a bash command line.
        # Using response file (nvcc --options-file) can resolve this problem.
        link_args = '-o ${out} ${includes} ${cppflags} --options-file ${out}.rsp ${extra_linkflags}'
        self.generate_rule(
            name='cudalink',
            command=nvcc_cmd + ' ' + link_args,
            rspfile='${out}.rsp',
            rspfile_content='${target_linkflags} ${in}',
            description='CUDA LINK BINARY ${out}')

        self.generate_rule(
            name='cudasolink',
            command=nvcc_cmd + ' -shared ' + link_args,
            rspfile='${out}.rsp',
            rspfile_content='${target_linkflags} ${in}',
            description='CUDA LINK SHARED ${out}')

    def _generate_msvc_cuda_rules(self):
        """Generate CUDA rules for MSVC host compiler on Windows.

        NVCC on Windows delegates host code to cl.exe.  Flags that pass
        through to the host compiler via -Xcompiler must be MSVC-compatible.
        """
        cc_config = config.get_section('cc_config')
        ms_config = config.get_section('msvc_config')
        cuda_config = config.get_section('cuda_config')

        # Build MSVC-compatible host compiler flags, filtered through the
        # toolchain so that GCC-isms from cc_config get mapped or dropped.
        filtered_cppflags = self.build_toolchain.filter_cc_flags(cc_config['cppflags'])
        filtered_cxxflags = self.build_toolchain.filter_cc_flags(cc_config['cxxflags'], 'c++')
        cppflags = ms_config['cppflags'] + filtered_cppflags
        cxxflags = ms_config['cxxflags'] + filtered_cxxflags

        # NVCC's cudafe++ (which preprocesses host code before MSVC) has a
        # limited C++ STL understanding.  /EHsc and /std:c++17 pull in STL
        # internal headers (e.g. xtr1common) that trigger an assertion in
        # cudafe++ — this is an NVCC limitation, not an MSVC version issue.
        cppflags = [f for f in cppflags if not f.startswith('/EH')]
        cxxflags = [f for f in cxxflags if not f.startswith('/EH')]
        cppflags = [f for f in cppflags if not f.startswith('/std:')]
        cxxflags = [f for f in cxxflags if not f.startswith('/std:')]

        # -Xcompiler passes flags to the host compiler (cl.exe); NVCC
        # itself understands -I / -D / etc. natively.
        host_cppflags = ' '.join('-Xcompiler %s' % f for f in cppflags)
        host_cxxflags = ' '.join('-Xcompiler %s' % f for f in cxxflags)

        cuflags = cuda_config['cuflags']
        system_includes = self.build_toolchain.get_system_include_paths()
        includes = system_includes + cc_config['extra_incs'] + ['.', self.build_dir]
        # NVCC uses -I natively, same across platforms.
        # Quote paths with spaces so nvcc parses them as a single argument.
        def _quote_if_needed(p):
            return '-I"%s"' % p if ' ' in p else '-I%s' % p
        include_flags = ' '.join(_quote_if_needed(inc) for inc in includes)

        # NVCC -Xcompiler /showIncludes lets Ninja deps=msvc track headers.
        # The Python wrapper tees /showIncludes to both stderr (for Ninja) and
        # the inclusion stack file.
        py = sys.executable
        wrapper = self._msvc_tee_wrapper_py()
        template = '"%s" -B %s ${inclusion_stack} -- ' % (py, wrapper)

        _, cxx, _ = self.build_accelerator.get_cc_commands()
        cu_command = template + ('"${cmd}" -ccbin "%s" -o ${out} -c '
                                 '-Xcompiler /nologo -Xcompiler /showIncludes '
                                 '%s %s %s '
                                 '%s ${includes} %s ${cu_warnings} ${in}' % (
                                     cxx,
                                     host_cppflags, host_cxxflags,
                                     ' '.join(cuflags),
                                     include_flags, '${cppflags}'))
        self.generate_rule(
            name='cudacc',
            command=cu_command,
            description='CUDA LIBRARY ${in}',
            deps='msvc',
            restat=True,
        )

        # NVCC linking delegates to the host linker automatically.
        # Include -ccbin so nvcc can find cl.exe even without a VS dev shell.
        # Route through the link scrubber so nvcc's echoed object name
        # (e.g. "test.cu.obj") doesn't leak past Ninja's "CUDA LINK ..." line.
        link_wrapper = self._msvc_link_wrapper_py()
        link_prefix = '"%s" -B %s -- "${cmd}" -ccbin "%s" ' % (
            sys.executable, link_wrapper, cxx)
        link_args = ('-o ${out} %s ${cppflags} '
                     '--options-file ${out}.rsp ${extra_linkflags}' % include_flags)
        self.generate_rule(
            name='cudalink',
            command=link_prefix + link_args,
            rspfile='${out}.rsp',
            rspfile_content='${target_linkflags} ${in}',
            description='CUDA LINK BINARY ${out}')

        self.generate_rule(
            name='cudasolink',
            command=link_prefix + '-shared ' + link_args,
            rspfile='${out}.rsp',
            rspfile_content='${target_linkflags} ${in}',
            description='CUDA LINK SHARED ${out}')


def generate_cc_rules(ctx):
    """Rule provider: cc-family rules (registered from cc_targets)."""
    CcRuleGenerator(ctx).generate_cc_rules()


def generate_cuda_rules(ctx):
    """Rule provider: cuda rules (registered from cu_targets)."""
    CcRuleGenerator(ctx).generate_cuda_rules()
