# Copyright (c) 2026 The Blade Authors.
# All rights reserved.

"""
cc / cuda ninja rule generation, extracted from backend.py (M2 of #1264).

``CcRuleGenerator`` is fed a :class:`~blade.rule_context.RuleContext` and emits
the cc-family rules. The original method bodies are kept verbatim; the thin
adapter below re-exposes the handful of ``self.*`` members those bodies use
(``generate_rule``, ``_add_line``, ``_builtin_command`` and the
toolchain/accelerator/options/build_dir/command/blade state) by delegating to
the RuleContext. ``_builtin_command`` is cross-language and stays in backend;
everything here is cc/cuda-specific.
"""

import os
import sys
import textwrap

from blade import config
from blade import console
from blade import util
from blade.ninja_rule import NinjaRule


# To verify whether a header is included without depending on the library it
# belongs to, we use gcc's `-H` option to print the inclusion stack
# (https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html). That goes to
# stderr, mixed with diagnostics, so this awk program separates them: lines of
# the inclusion stack (leading dots) go to stdout (-> the `.incstk` file),
# everything else is forwarded to stderr.
#
# `多个防止重包含可能对其有用：` is the Chinese of `Multiple include guards...`;
# after that marker the trailing file list is noise, but later lines (e.g. a
# cuda error) may still matter, so we don't `exit` early.
_INCLUSION_SPLITTER_AWK = r'''
/Multiple include guards may be useful for:|多个防止重包含可能对其有用：/ { stop = 1 }
/^\.+ [^\/]/ && !end { started = 1; print $0 }       # an inclusion-stack line
!/^\.+ / && started { end = 1 }                      # first line after the stack
!/^\.+ / && (!stop || (!/Multiple include guards may be useful for:|多个防止重包含可能对其有用：/ && !/^[a-zA-Z0-9\.\/\+_-]+$/)) { print $0 > "/dev/stderr" }
'''

_INCLUSION_WRAPPER_SCRIPT = '''\
#!/bin/sh
# Generated by blade; do not edit. See backend.py (_inclusion_wrapper_script).
mode=$1
out=$2
shift 2
err=$out.err
export LC_ALL=C
if [ "$mode" = hdrs ]; then
    # -fdirectives-only speeds up preprocessing but breaks on some edge cases
    # (e.g. __COUNTER__ tricks); retry without it, discarding the first
    # attempt's diagnostics.
    "$@" -fdirectives-only 2> "$err" || "$@" 2> "$err"
else
    "$@" 2> "$err"
fi
ec=$?
awk '%s' "$err" > "$out.new"
# write-if-changed: keep $out's mtime when the inclusion stack is unchanged, so
# ninja's `restat` can prune the inclusion check on recompiles that don't alter
# the set of included headers. See issue #1161.
if [ -f "$out" ] && cmp -s "$out.new" "$out"; then
    rm -f "$out.new"
else
    mv "$out.new" "$out"
fi
rm -f "$err"
exit $ec
''' % _INCLUSION_SPLITTER_AWK

_MSVC_TEE_WRAPPER_PY = r'''
import os, re, subprocess, sys, tempfile

outfile = sys.argv[1]
# sys.argv[2] is "--"
cmd = sys.argv[3:]

_NOTE_PREFIX = 'Note: including file:'
_cwd = os.getcwd()

# Compilers echo the basename of the file they process.  Ninja's
# CLParser::FilterInputFilename strips it for source files (.c/.cc/.cxx/.cpp/
# .c++) but NOT for headers, so the cxxhdrs rule (/P on a .h) leaks a bare
# "foo.h" onto the build console; nvcc additionally echoes its source (.cu)
# and a zoo of intermediate temp names (tmpxft_*.cpp1.ii, *.cudafe1.cpp, ...).
# Enumerating extensions is hopeless, so match any lone filename token: no
# whitespace, no path separator, at least one dot, only filename-safe chars.
# Real diagnostics always carry spaces/colons/parens and never match.
_BARE_FILENAME_RE = re.compile(r'^[\w.+\-]+\.[\w.+\-]+$')

def _in_workspace(hdr):
    try:
        return os.path.commonpath([_cwd, hdr]) == _cwd
    except ValueError:  # different drive -> outside the workspace
        return False

# nvcc writes its intermediates (tmpxft_*.cudafe1.stub.c, *.fatbin.c, ...) into
# a temp dir and lists them in /showIncludes. They are deleted after the build,
# so recording them as deps makes ninja rebuild the CUDA object every time (the
# dep targets are perpetually "missing"). They are never real source deps ->
# drop such include lines entirely (neither incstk nor forwarded to ninja).
#
# All nvcc intermediates are named `tmpxft_*`, which is the reliable signal --
# independent of *where* nvcc puts them. Also catch anything under the temp dir
# as a backstop (normcase so the Windows case-insensitive match works; the temp
# dir nvcc uses may differ from this process's, so the name check is primary).
_TEMP_DIR = os.path.normcase(os.path.realpath(tempfile.gettempdir()))

def _in_temp(hdr):
    if os.path.basename(hdr).startswith('tmpxft_'):
        return True
    try:
        p = os.path.normcase(os.path.realpath(hdr))
        return p == _TEMP_DIR or p.startswith(_TEMP_DIR + os.sep)
    except (ValueError, OSError):  # bad path -> not in temp
        return False

# Force the English "Note: including file:" prefix. cl.exe (and nvcc's cl)
# localize /showIncludes on a non-English Visual Studio, which would silently
# break both the inclusion stack written below and Ninja's deps=msvc header
# tracking (the prefix _NOTE_PREFIX above and Ninja's msvc_deps_prefix are both
# the English string). VSLANG=1033 is the en-US LCID; set it on the child only,
# not the whole build, so nothing else is affected. See issue #1154.
env = dict(os.environ)
env['VSLANG'] = '1033'

# Merge stdout+stderr into one pipe (like Ninja).  Reading only stderr risks
# a pipe deadlock: if cl.exe writes enough to stdout (even with /nologo a
# leftover copyright banner fills the 4 KiB buffer), the process blocks and
# never drains its stderr output through the unread stdout pipe.
p = subprocess.Popen(cmd, env=env, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                     universal_newlines=True, encoding='utf-8', errors='replace')
with open(outfile + '.new', 'w', newline='', encoding='utf-8') as f:
    for line in p.stdout:
        if line.startswith(_NOTE_PREFIX):
            hdr = line[len(_NOTE_PREFIX):].lstrip().rstrip('\r\n')
            if os.path.isabs(hdr) and _in_temp(hdr):
                # nvcc intermediate in the temp dir -- not a real dependency;
                # drop entirely so ninja doesn't record it and rebuild forever.
                continue
            # Record only workspace headers in the incstk (smaller file; the
            # inclusion checker discards absolute/system paths anyway), but
            # forward every include line to ninja's deps=msvc parser below.
            if not os.path.isabs(hdr) or _in_workspace(hdr):
                f.write(line)
        elif _BARE_FILENAME_RE.match(line.strip()):
            continue  # echoed source/temp filename -- console noise, drop it
        sys.stderr.write(line)
        sys.stderr.flush()

ec = p.wait()

# Write-if-changed: keep mtime when the stack is unchanged, so ninja's
# restat can prune the inclusion check. See issue #1161.
try:
    with open(outfile + '.new', 'rb') as nf:
        new = nf.read()
    try:
        with open(outfile, 'rb') as of:
            old = of.read()
    except FileNotFoundError:
        old = None
    if new != old:
        os.replace(outfile + '.new', outfile)
    else:
        os.unlink(outfile + '.new')
except OSError:
    pass

sys.exit(ec)
'''

_MSVC_LINK_WRAPPER_PY = r'''
import os, re, subprocess, sys

# A lone filename token (no spaces/path, at least one dot) -- same shape the cc
# wrapper drops. Real diagnostics carry spaces/colons and never match.
_BARE_FILENAME_RE = re.compile(r'^[\w.+\-]+\.[\w.+\-]+$')

sep = sys.argv.index('--')
args = sys.argv[1:sep]
cmd = sys.argv[sep + 1:]
env = dict(os.environ)
env['VSLANG'] = '1033'  # force English so the filter below matches
# Prepend the MSVC + Windows SDK bin dirs so link.exe can find the helper
# tools it spawns by name -- notably mt.exe (in the SDK bin, a different dir
# from link.exe) for /MANIFEST:EMBED. blade invokes link by absolute path, but
# tools link itself spawns are resolved via PATH. See cc_rule_support.
if '--prepend-path' in args:
    _dirs = args[args.index('--prepend-path') + 1]
    if _dirs:
        env['PATH'] = _dirs + os.pathsep + env.get('PATH', '')

p = subprocess.Popen(cmd, env=env, stdout=subprocess.PIPE,
                     stderr=subprocess.STDOUT, universal_newlines=True,
                     encoding='utf-8', errors='replace')
for line in p.stdout:
    s = line.strip()
    if s.startswith('Creating library ') and ' and object ' in s:
        continue  # link.exe import-library notice (redundant with "LINK ...")
    if _BARE_FILENAME_RE.match(s):
        continue  # nvcc's echoed object/source name (e.g. test.cu.obj)
    sys.stdout.write(line)
    sys.stdout.flush()
sys.exit(p.wait())
'''


class CcRuleGenerator:
    """Generate cc/cuda ninja rules from a RuleContext (see module docstring)."""

    def __init__(self, ctx):
        self._ctx = ctx
        self.build_toolchain = ctx.toolchain
        self.build_accelerator = ctx.accelerator
        self.options = ctx.options
        self.build_dir = ctx.build_dir
        self.command = ctx.command
        self.blade = ctx.blade
        self.__inclusion_wrapper_path = None
        self.__msvc_wrapper_py_path = None
        self.__msvc_link_wrapper_py_path = None

    def _add_line(self, line):
        self._ctx.add_line(line)

    def _builtin_command(self, builder, args=''):
        return self._ctx.builtin_command(builder, args)

    def generate_rule(self, name, command, description=None, depfile=None,
                      generator=False, pool=None, restat=False, rspfile=None,
                      rspfile_content=None, deps=None):
        self._ctx.emit_rule(NinjaRule(
            name=name, command=command, description=description, depfile=depfile,
            generator=generator, pool=pool, restat=restat, rspfile=rspfile,
            rspfile_content=rspfile_content, deps=deps))

    def _inclusion_wrapper_script(self):
        """Path to the cc inclusion-stack splitter wrapper, written on first use.

        See `_INCLUSION_WRAPPER_SCRIPT`. Written into the build dir at ninja
        generation time; ninja runs from the workspace root, so the build-dir
        relative path resolves. The script is not a dependency of any edge, so
        rewriting it never triggers a rebuild.
        """
        if self.__inclusion_wrapper_path is None:
            path = os.path.join(self.build_dir, 'cc_wrapper.sh')
            util.write_if_changed(path, _INCLUSION_WRAPPER_SCRIPT)
            self.__inclusion_wrapper_path = path
        return self.__inclusion_wrapper_path

    def _msvc_tee_wrapper_py(self):
        """Path to the MSVC Python stderr-tee wrapper, written on first use."""
        if self.__msvc_wrapper_py_path is None:
            path = os.path.join(self.build_dir, 'cc_wrapper.py')
            util.write_if_changed(path, _MSVC_TEE_WRAPPER_PY)
            self.__msvc_wrapper_py_path = path
        return self.__msvc_wrapper_py_path

    def _msvc_link_wrapper_py(self):
        """Path to the MSVC link-output filter wrapper, written on first use."""
        if self.__msvc_link_wrapper_py_path is None:
            path = os.path.join(self.build_dir, 'link_wrapper.py')
            util.write_if_changed(path, _MSVC_LINK_WRAPPER_PY)
            self.__msvc_link_wrapper_py_path = path
        return self.__msvc_link_wrapper_py_path

    def _get_intrinsic_cc_flags(self):
        """Get the common c/c++ flags."""
        global_config = config.get_section('global_config')
        cc_config = config.get_section('cc_config')

        cppflags = []
        linkflags = []
        if self.options.m:
            cppflags = ['-m%s' % self.options.m]
            linkflags = ['-m%s' % self.options.m]
        # Add -fno-omit-frame-pointer to optimize mode for easy debugging.
        cppflags += ['-pipe', '-fno-omit-frame-pointer']

        if cc_config["fission"]:
            cppflags += ['-gsplit-dwarf']
            linkflags += ['-Wl,--gdb-index']

        # Debugging information setting
        debug_info_level = global_config['debug_info_level']
        debug_info_options = cc_config['debug_info_levels'][debug_info_level]
        cppflags += debug_info_options

        # Option debugging flags
        if self.options.profile == 'debug':
            cppflags.append('-fstack-protector')
        elif self.options.profile == 'release':
            cppflags.append('-DNDEBUG')

        cppflags += [
            '-D_FILE_OFFSET_BITS=64',
            '-D__STDC_CONSTANT_MACROS',
            '-D__STDC_FORMAT_MACROS',
            '-D__STDC_LIMIT_MACROS',
        ]

        if getattr(self.options, 'gprof', False):
            cppflags.append('-pg')
            linkflags.append('-pg')

        if getattr(self.options, 'coverage', False):
            cppflags.append('--coverage')
            linkflags.append('--coverage')

        if hasattr(self.options, 'profile-generate') and getattr(self.options, 'profile-generate') is not None:
            pgo_gen_dir = getattr(self.options, 'profile-generate')
            if not pgo_gen_dir:
                cppflags.append('-fprofile-generate')
                linkflags.append('-fprofile-generate')
            else:
                cppflags.append('-fprofile-generate=' + pgo_gen_dir)
                linkflags.append('-fprofile-generate=' + pgo_gen_dir)
            cppflags.append('-DPROFILE_GUIDED_OPTIMIZATION')

        if hasattr(self.options, 'profile-use') and getattr(self.options, 'profile-use') is not None:
            pgo_use_dir = getattr(self.options, 'profile-use')
            if not pgo_use_dir:
                cppflags.append('-fprofile-use')
            else:
                cppflags.append('-fprofile-use=' + pgo_use_dir)
            cppflags.append('-fprofile-correction')
            cppflags.append('-Wno-error=coverage-mismatch')
            cppflags.append('-DPROFILE_GUIDED_OPTIMIZATION')

        # Recover -fPIE-level optimization under -fPIC: tell the compiler the
        # current TU's symbol definitions aren't interposable, so it can
        # reference/inline its own globals directly instead of going through
        # the GOT. Default-on (cc_config.no_semantic_interposition defaults
        # to True); users with plugin frameworks that LD_PRELOAD-override
        # exe-internal symbols opt out by setting it to False.
        #
        # GCC-only: Clang (incl. Apple Clang) is already non-interposing by
        # default, so emitting the flag is redundant -- and on the C++ driver
        # specifically Clang fires `-Wunused-command-line-argument`, which
        # `-Werror` projects then refuse to compile. filter_cc_flags can't
        # screen this out because it probes in C, where Clang stays silent.
        # See issue #1258.
        if (cc_config['no_semantic_interposition']
                and self.build_toolchain.cc_is('gcc')):
            cppflags.append('-fno-semantic-interposition')

        cppflags = self.build_toolchain.filter_cc_flags(cppflags)
        return cppflags, linkflags

    def _get_warning_flags(self):
        """Get the warning flags."""
        cc_config = config.get_section('cc_config')
        cuda_config = config.get_section('cuda_config')
        cppflags = cc_config['warnings']
        cxxflags = cc_config['cxx_warnings']
        cflags = cc_config['c_warnings']
        cuflags = cuda_config['cu_warnings']

        filtered_cppflags = self.build_toolchain.filter_cc_flags(cppflags)
        filtered_cxxflags = self.build_toolchain.filter_cc_flags(cxxflags, 'c++')
        filtered_cflags = self.build_toolchain.filter_cc_flags(cflags, 'c')

        return filtered_cppflags, filtered_cxxflags, filtered_cflags, cuflags

    def generate_cc_rules(self):
        if self.build_toolchain.cc_is('msvc'):
            self._generate_windows_cc_rules()
        else:
            cc, cxx, ld = self.build_accelerator.get_cc_commands()
            cppflags, linkflags = self._get_intrinsic_cc_flags()
            self._generate_cc_compile_rules(cc, cxx, cppflags)
            self._generate_cc_inclusion_check_rule()
            self._generate_cc_check_undefined_rule()
            self._generate_cc_ar_rules()
            self._generate_cc_link_rules(ld, linkflags)
            self.generate_rule(name='strip',
                               command='strip --strip-unneeded -o ${out} ${in}',
                               description='STRIP ${out}')

    def _generate_windows_cc_rules(self):
        """Generate Windows/MSVC-specific CC rules."""
        cc, cxx, ld = self.build_accelerator.get_cc_commands()
        self._generate_windows_cc_vars()
        self._generate_windows_cc_compile_rules(cc, cxx)
        self._generate_windows_asm_rule()
        self._generate_cc_inclusion_check_rule()
        self._generate_cc_check_undefined_rule()
        self._generate_windows_ar_rules()
        self._generate_windows_link_rules()

    def _generate_windows_cc_vars(self):
        """Generate Windows-specific CC variables."""
        windows_config = config.get_section('msvc_config')
        cc_config = config.get_section('cc_config')
        # Combine windows_config warnings with filtered cc_config warnings
        c_warnings = (windows_config['warnings'] +
                      self.build_toolchain.filter_cc_flags(cc_config['c_warnings'], 'c'))
        cxx_warnings = (windows_config['warnings'] +
                        self.build_toolchain.filter_cc_flags(cc_config['cxx_warnings'], 'c++'))
        self._add_line(textwrap.dedent('''\
                c_warnings = %s
                cxx_warnings = %s
                ''') % (' '.join(c_warnings), ' '.join(cxx_warnings)))

    def _generate_windows_cc_compile_rules(self, cc, cxx):
        """Generate Windows CC compilation rules."""
        windows_config = config.get_section('msvc_config')
        cc_config = config.get_section('cc_config')

        # Combine windows_config flags with filtered cc_config flags.
        # cc_config flags (from BLADE_ROOT) typically use GCC syntax and get
        # mapped/filtered by the toolchain (e.g. -std=c++17 → /std:c++17).
        filtered_cc_cflags = self.build_toolchain.filter_cc_flags(cc_config['cflags'], 'c')
        filtered_cc_cxxflags = self.build_toolchain.filter_cc_flags(cc_config['cxxflags'], 'c++')
        filtered_cc_cppflags = self.build_toolchain.filter_cc_flags(cc_config['cppflags'])

        cppflags = windows_config['cppflags'] + filtered_cc_cppflags
        cflags = windows_config['cflags'] + filtered_cc_cflags
        cxxflags = windows_config['cxxflags'] + filtered_cc_cxxflags
        # System includes (MSVC + Windows SDK) discovered by the toolchain,
        # then user-specified extra_incs, then build directory.
        system_includes = self.build_toolchain.get_system_include_paths()
        includes = system_includes + cc_config['extra_incs'] + ['.', self.build_dir]
        # MSVC accepts /I"path with spaces" (quoted, no space after /I).
        # Use a helper that quotes paths containing spaces.
        def _quote_if_needed(p):
            return f'/I"{p}"' if ' ' in p else f'/I{p}'
        include_flags = ' '.join([_quote_if_needed(inc) for inc in includes])

        optimize_flags = windows_config['optimize']
        optimize = ' '.join(optimize_flags.get(self.options.profile, []))

        # The Python stderr-tee wrapper captures /showIncludes output and tees
        # it to both stderr (for Ninja's deps=msvc) and the inclusion stack
        # file (for inclusion checking).
        py = sys.executable
        wrapper = self._msvc_tee_wrapper_py()
        template = '"%s" -B %s ${inclusion_stack} -- ' % (py, wrapper)

        cc_command = template + ('"%s" /nologo /c /showIncludes %s %s %s %s /Fo${out} ${c_warnings} /external:W0 ${cppflags} ${includes} ${extra_compile_flags} ${in}' % (
            cc, optimize, ' '.join(cppflags), ' '.join(cflags), include_flags))
        self.generate_rule(name='cc',
                           command=cc_command,
                           description='CC ${in}',
                           deps='msvc',
                           restat=True)

        cxx_command = template + ('"%s" /nologo /c /showIncludes %s %s %s %s /Fo${out} ${cxx_warnings} /external:W0 ${cppflags} ${includes} ${extra_compile_flags} ${in}' % (
            cxx, optimize, ' '.join(cppflags), ' '.join(cxxflags), include_flags))
        self.generate_rule(name='cxx',
                           command=cxx_command,
                           description='CXX ${in}',
                           deps='msvc',
                           restat=True)

        # For cxxhdrs: use /showIncludes to generate inclusion info for header
        # files. /P preprocesses (like GCC -E), /Tp forces C++ treatment of .h.
        # The Python wrapper captures /showIncludes to ${out} (.incstk file);
        # /Fi writes the preprocessed body to ${out}.pre.
        hdrs_template = '"%s" -B %s ${out} -- ' % (py, wrapper)
        hdrs_command = hdrs_template + ('"%s" /nologo /P /Tp${in} /showIncludes %s /external:W0 ${cppflags} ${includes} %s %s %s /Fi${out}.pre' % (
            cxx, optimize, ' '.join(cppflags), ' '.join(cxxflags), include_flags))
        self.generate_rule(name='cxxhdrs',
                           command=hdrs_command,
                           description='CXX HDRS ${in}',
                           deps='msvc',
                           restat=True)

    def _generate_windows_asm_rule(self):
        """Generate the MSVC assembler (``ml64`` / ``ml``) rule for ``.asm``.

        ``cl.exe`` cannot assemble MASM source; ``.asm`` files must go through
        ``ml64.exe`` (x64) / ``ml.exe`` (x86), resolved by the toolchain as the
        ``'as'`` tool. ``CcTarget._get_rule_from_suffix`` routes ``.asm`` here on
        MSVC. Per-target inc dirs ride on ``${includes}`` (already ``/I`` form
        on MSVC) and per-target asm flags on ``${extra_compile_flags}`` (from
        ``extra_asflags``). No ``/showIncludes`` / inclusion-stack plumbing --
        assembly is not header-dependency-checked.
        """
        asm = self.build_toolchain.tool('as')
        if not asm:
            return
        self.generate_rule(
            name='as',
            command='"%s" /nologo /c /Fo${out} ${extra_compile_flags} '
                    '${includes} ${in}' % asm,
            description='AS ${in}')

    def _generate_windows_ar_rules(self):
        """Generate Windows static library rules."""
        cc_lib = config.get_section('cc_library_config')
        deterministic = cc_lib.get('deterministic', False)
        thin = cc_lib.get('thin', False)
        if thin:
            console.warning('cc_library_config.thin=True has no effect on MSVC (lib.exe '
                            'does not support thin archives)')
        ar = self.build_accelerator.get_ar_command()
        brepro = ' /Brepro' if deterministic else ''
        self.generate_rule(name='ar',
                           command=f'{ar} /nologo{brepro} /out:${{out}} ${{in}}',
                           description='LIB ${out}')

    def _generate_windows_link_rules(self):
        """Generate Windows linking rules."""
        _, _, ld = self.build_accelerator.get_cc_commands()
        windows_config = config.get_section('msvc_config')
        cc_config = config.get_section('cc_config')
        # Combine windows_config linkflags with filtered cc_config linkflags
        linkflags = (windows_config['linkflags'] +
                     self.build_toolchain.filter_cc_flags(cc_config['linkflags']))

        # System library paths (MSVC + Windows SDK) discovered by the toolchain
        lib_paths = self.build_toolchain.get_system_lib_paths()
        def _libpath_flag(p):
            if ' ' in p:
                return '/LIBPATH:"%s"' % p
            return '/LIBPATH:%s' % p
        libpath_flags = ' '.join([_libpath_flag(p) for p in lib_paths])

        self._add_line('linkflags = %s\n' % ' '.join(linkflags))

        # MSVC + Windows SDK bin dirs, so link.exe can find tools it spawns by
        # name (e.g. mt.exe in the SDK bin for /MANIFEST:EMBED -- a different dir
        # from link.exe). blade calls link by absolute path, but link resolves
        # its own sub-tools via PATH; the link wrapper prepends these.
        tool_dirs = []
        for _key in ('ld', 'cc', 'rc', 'as'):
            _t = self.build_toolchain.tool(_key)
            if _t:
                _d = os.path.dirname(_t)
                if _d and _d not in tool_dirs:
                    tool_dirs.append(_d)
        prepend_path = os.pathsep.join(tool_dirs)

        link_wrapper = self._msvc_link_wrapper_py()
        wrap = f'"{sys.executable}" -B {link_wrapper} --prepend-path "{prepend_path}" --'

        self.generate_rule(name='link',
                           command=f'{wrap} {ld} /nologo /out:${{out}} ${{linkflags}} {libpath_flags} ${{target_linkflags}} ${{extra_linkflags}} ${{in}}',
                           description='LINK EXE ${out}')

        # ${dllflags} carries the per-target `/DEF:<def> /IMPLIB:<implib>` for a
        # cc_library DLL (empty for other solink edges, e.g. cc_plugin). The
        # `.def` (auto-export, COMDAT-filtered) makes the DLL export its symbols
        # without source annotations; the import library is what dependents link.
        # Route the DLL link through the same Python wrapper, which drops
        # link.exe's redundant "Creating library ... and object ..." notice (the
        # import lib is always created for a DLL, so it always prints) and
        # prepends the tool dirs to PATH. See `_MSVC_LINK_WRAPPER_PY`.
        # restat: link.exe doesn't rewrite the import library (`/IMPLIB`) when
        # the DLL's exports are unchanged, so its mtime can lag; re-stat outputs
        # after linking so an unchanged DLL/implib prunes dependent relinks.
        self.generate_rule(name='solink',
                           command=f'{wrap} {ld} /nologo /DLL ${{dllflags}} /out:${{out}} ${{linkflags}} {libpath_flags} ${{target_linkflags}} ${{extra_linkflags}} ${{in}}',
                           description='LINK DLL ${out}',
                           restat=True)

        # Synthesize the auto-export `.def` from the object files (see the
        # `cc_windef` builtin tool). Windows-only; nothing emits this edge
        # elsewhere.
        # restat: the `.def` is written write-if-changed, so when the export set
        # is unchanged ninja keeps its old mtime and prunes the downstream DLL
        # relink (the import lib stays newer than the def). See the
        # incremental-build fix / issue #1161 pattern.
        self.generate_rule(name='cc_windef',
                           command=self._builtin_command('cc_windef', '${defflags} ${out} ${in}'),
                           description='CC WINDEF ${out}',
                           restat=True)

    def _generate_cc_vars(self):
        warnings, cxx_warnings, c_warnings, cu_warnings = self._get_warning_flags()
        c_warnings += warnings
        cxx_warnings += warnings
        cu_warnings += ['-Xcompiler %s' % warning for warning in cxx_warnings]
        # optimize_flags is need for `always_optimize`
        optimize_flags = config.get_item('cc_config', 'optimize')
        optimize = '$optimize_flags' if self.options.profile == 'release' else ''
        self._add_line(textwrap.dedent('''\
                c_warnings = %s
                cxx_warnings = %s
                cu_warnings = %s
                optimize_flags = %s
                optimize = %s
                ''') % (' '.join(c_warnings), ' '.join(cxx_warnings),
                        ' '.join(cu_warnings),
                        ' '.join(optimize_flags), optimize))

    def _generate_cc_compile_rules(self, cc, cxx, cppflags):
        self._generate_cc_vars()

        cc_config = config.get_section('cc_config')
        cflags, cxxflags = cc_config['cflags'], cc_config['cxxflags']
        cppflags = cc_config['cppflags'] + cppflags
        includes = cc_config['extra_incs']
        includes = includes + ['.', self.build_dir]
        includes = ' '.join(['-I%s' % inc for inc in includes])

        template = self._cc_compile_command_wrapper_template('${inclusion_stack}')

        cc_command = ('%s -o ${out} -MMD -MF ${out}.d -c -fPIC %s %s ${optimize} '
                      '${c_warnings} ${cppflags} ${extra_compile_flags} %s ${includes} ${in}') % (
                              cc, ' '.join(cflags), ' '.join(cppflags), includes)
        self.generate_rule(name='cc',
                           command=template % cc_command,
                           description='CC ${in}',
                           depfile='${out}.d',
                           deps='gcc',
                           # restat lets ninja prune the inclusion check when the
                           # per-source `${inclusion_stack}` (`<src>.incstk`) is
                           # unchanged (written write-if-changed). See issue #1161.
                           restat=True)

        cxx_command = ('%s -o ${out} -MMD -MF ${out}.d -c -fPIC %s %s ${optimize} '
                       '${cxx_warnings} ${cppflags} ${extra_compile_flags} %s ${includes} ${in}') % (
                               cxx, ' '.join(cxxflags), ' '.join(cppflags), includes)
        self.generate_rule(name='cxx',
                           command=template % cxx_command,
                           description='CXX ${in}',
                           depfile='${out}.d',
                           deps='gcc',
                           restat=True)  # see the cc rule / issue #1161

        self.generate_rule(name='secretcc',
                           command=template % (cc_config['secretcc'] + ' ' + cxx_command),
                           description='SECRET CC ${in}',
                           depfile='${out}.d',
                           restat=True)  # see the cc rule / issue #1161

        self._generate_cc_hdrs_rule(cc, cxx, cppflags, cflags, cxxflags, includes)

    def _generate_cc_hdrs_rule(self, cc, cxx, cppflags, cflags, cxxflags, includes):
        """
        Generate inclusion stack file for header file to check dependency missing.
        See the '-H' in https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html for details.
        """
        self.generate_rule(name='cxxhdrs',
                           command=self._hdrs_command(cxx, cxxflags, cppflags, includes),
                           depfile='${out}.d', deps='gcc',
                           # restat lets ninja prune the inclusion check when the
                           # header's inclusion stack is unchanged (the wrapper
                           # writes ${out} write-if-changed). See issue #1161.
                           restat=True,
                           description='CXX HDRS ${in}')

    def _hdrs_command(self, cc, flags, cppflags, includes):
        """Build the bare preprocess command for a header's inclusion file.

        Run by the `hdrs`-mode wrapper script (see `_INCLUSION_WRAPPER_SCRIPT`);
        `${out}` is the inclusion (`.incstk`) file. `-H` is what the wrapper's
        awk extracts -- without it the inclusion stack is never emitted and the
        `.incstk` ends up empty, silently breaking checks for header-only
        libraries. See issue #1169.
        """
        cmd = ('%s -o /dev/null -E -MMD -MF ${out}.d %s %s -w ${cppflags} %s ${includes} ${in} -H' % (
            cc, ' '.join(flags), ' '.join(cppflags), includes))
        return 'sh %s hdrs ${out} %s' % (self._inclusion_wrapper_script(), cmd)

    def _generate_cc_inclusion_check_rule(self):
        self.generate_rule(name='ccincchk',
                           command=self._builtin_command('cc_inclusion_check'),
                           description='CC INCLUSION CHECK ${in}')

    def _generate_cc_check_undefined_rule(self):
        # Two cooperating rules implement the static dep-completeness check
        # (issue #1225) and keep its total nm work linear in the dep graph,
        # not quadratic:
        #
        # 1. ``ccsyms`` runs ``nm`` on a single archive once and emits a
        #    sidecar ``<archive>.syms`` file with two sections (#U undefined
        #    externals, #D defined externals). One node per archive, ninja
        #    fans them out alongside the corresponding ``ar`` rules. Each
        #    archive is nm'd exactly once per build regardless of how many
        #    cc_libraries depend on it.
        # 2. ``ccchkund`` consumes the ``.syms`` files (target's own + each
        #    transitive dep's + the system-symbols caches) and decides if
        #    the target's undefined set is closed. Pure file reads and set
        #    arithmetic; no ``nm`` at check time.
        #
        # Previously this was a single ``ccchkund`` rule that took raw
        # ``.a`` archives and re-ran ``nm`` on every dep for every target's
        # check, making the total cost O(targets × deps) and scaling badly
        # on diamond-shaped dep graphs.
        # On MSVC the archives are COFF .lib files and nm is unavailable, so the
        # emit-syms tool reads symbols with dumpbin instead; pass its path.
        syms_args = '${out} ${in}'
        if self.build_toolchain.cc_is('msvc'):
            syms_args += ' --dumpbin="%s"' % self.build_toolchain.dumpbin
        self.generate_rule(name='ccsyms',
                           command=self._builtin_command('cc_emit_syms', syms_args),
                           description='CC SYMS ${in}')
        # Single batch rule: ``${in}`` is the manifest JSON (built by
        # BuildManager after all cc_libraries have generated), ``${out}``
        # is the project-wide stamp file. The ``.syms`` files referenced
        # by the manifest are pulled in as implicit deps by the rule the
        # batch emitter registers (each .syms is also an explicit input
        # there, so ninja still re-runs the batch when any archive's
        # symbol set changes).
        # Severity is project-global, baked into the rule command at generate
        # time so a config flip triggers a normal ninja regen (the build.ninja
        # text changes -> ninja reloads). 'warning' (default while the check is
        # experimental) logs findings but doesn't fail the build; 'error' fails.
        severity = config.get_item('cc_library_config', 'check_undefined_severity')
        batch_args = '${out} ${in} --severity=%s' % severity
        self.generate_rule(name='ccchkund_batch',
                           command=self._builtin_command(
                               'cc_check_undefined_batch', batch_args),
                           description='CC CHECK UNDEFINED [batch]')

    def _generate_cc_ar_rules(self):
        cc_lib = config.get_section('cc_library_config')
        deterministic = cc_lib.get('deterministic', False)
        thin = cc_lib.get('thin', False)
        target_os = self.build_toolchain.target_os

        if target_os == 'darwin':
            if thin:
                console.error('cc_library_config.thin=True is not supported on macOS '
                              '(Apple ar does not support thin archives)')
            if deterministic:
                command = 'rm -f $out; libtool -static -no_warning_for_no_symbols -o $out $in'
            else:
                ar = self.build_accelerator.get_ar_command()
                command = f'rm -f $out; {ar} rcs $out $in'
        elif target_os == 'linux':
            ar = self.build_accelerator.get_ar_command()
            extra = ''
            if deterministic:
                extra += 'D'
            if thin:
                extra += 'T'
            command = f'rm -f $out; {ar} rcs{extra} $out $in'
        else:
            arflags = ''.join(cc_lib.get('arflags', ['rcs']))
            ar = self.build_accelerator.get_ar_command()
            command = f'rm -f $out; {ar} {arflags} $out $in'

        self.generate_rule(name='ar', command=command, description='AR ${out}')

    def _generate_cc_link_rules(self, ld, linkflags):
        self._add_line('linkflags = %s' % ' '.join(config.get_item('cc_config', 'linkflags')))
        self._add_line('intrinsic_linkflags = %s' % ' '.join(linkflags))
        # PIE posture for the executable link (see cc_config.pie, issue #1258).
        # Linux only -- macOS executables are PIE by default and ld64 removed
        # -no_pie in recent versions; MSVC has no PIC/PIE concept. The flag is
        # emitted as its own ninja variable so it lands only on the `link`
        # rule, not `solink` (a shared library + -pie is contradictory and
        # GCC/ld will error or warn).
        pie_flag = ''
        if self.build_toolchain.target_os == 'linux':
            pie = config.get_item('cc_config', 'pie')
            if pie == 'yes':
                pie_flag = '-pie'
            elif pie == 'no':
                pie_flag = '-no-pie'
        self._add_line('pie_flag = %s\n' % pie_flag)

        link_jobs = config.get_item('link_config', 'link_jobs')
        if link_jobs:
            link_jobs = min(link_jobs, self.blade.build_jobs_num())
            console.info('Adjust parallel link jobs number to %s' % link_jobs)
            pool = 'link_pool'
            self._add_line(textwrap.dedent('''\
                    pool %s
                      depth = %s''') % (pool, link_jobs))
        else:
            pool = None

        # Linking might have a lot of object files exceeding maximal length of a bash command line.
        # Using response file can resolve this problem.
        # Refer to: https://ninja-build.org/manual.html
        # Note: `${pie_flag}` is on the executable `link` rule only (it's a
        # no-op when cc_config.pie == 'auto', the project-wide default).
        link_args = '-o ${out} ${intrinsic_linkflags} ${linkflags} @${out}.rsp ${extra_linkflags}'
        self.generate_rule(name='link',
                           command=ld + ' ${pie_flag} ' + link_args,
                           rspfile='${out}.rsp',
                           rspfile_content='${target_linkflags} ${in}',
                           description='LINK BINARY ${out}',
                           pool=pool)
        self.generate_rule(name='solink',
                           command=ld + ' -shared ' + link_args,
                           rspfile='${out}.rsp',
                           rspfile_content='${target_linkflags} ${in}',
                           description='LINK SHARED ${out}',
                           pool=pool)
        self.generate_rule(name='dwp',
                           command=self._builtin_command('dwp', '${out} @${out}.rsp'),
                           rspfile='${out}.rsp',
                           rspfile_content='${in}',
                           description='DWP ${out}',
                           pool=pool)
        # macOS-only: translate a GNU-ld export_map (--version-script) into
        # ld64's native -exported_symbols_list. See the `cc_macos_exports`
        # builtin tool. restat=True so that an unchanged exports list prunes
        # the dependent dylib relink, matching the cc_windef pattern.
        if self.build_toolchain.target_os == 'darwin':
            self.generate_rule(
                name='cc_macos_exports',
                command=self._builtin_command(
                    'cc_macos_exports', '${out} ${export_map} ${in}'),
                description='MAC EXPORTS ${out}',
                restat=True)

    def _cc_compile_command_wrapper_template(self, inclusion_stack_file, cuda=False):
        """Calculate the cc compile command wrapper template.

        Returns a template whose single `%s` is the raw compile command. The
        wrapper script runs it, then splits gcc's `-H` inclusion stack into
        *inclusion_stack_file* (see `_inclusion_wrapper_script`).
        """
        # When dumping compdb, a raw compile command without wrapper should be generated,
        # otherwise some tools can't handle it.
        if self.command == 'dump' and self.options.dump_compdb:
            return '%s'

        print_header_option = '-Xcompiler -H' if cuda else '-H'
        return 'sh %s compile %s %%s %s' % (
            self._inclusion_wrapper_script(), inclusion_stack_file, print_header_option)

    def generate_cuda_rules(self):
        if self.build_toolchain.cc_is('msvc'):
            self._generate_msvc_cuda_rules()
        else:
            self._generate_gcc_cuda_rules()

    def _generate_gcc_cuda_rules(self):
        nvcc_cmd = '${cmd}'

        cc_config = config.get_section('cc_config')
        cuda_config = config.get_section('cuda_config')
        cxxflags = cc_config['cxxflags']
        cppflags, _ = self._get_intrinsic_cc_flags()
        cppflags = cc_config['cppflags'] + cppflags
        cxxflags = ['-Xcompiler %s' % flag for flag in cxxflags]
        cppflags = ['-Xcompiler %s' % flag for flag in cppflags]
        cuflags = cuda_config['cuflags']
        includes = cc_config['extra_incs']
        includes = includes + ['.', self.build_dir]
        includes = ' '.join(['-I%s' % inc for inc in includes])

        template = self._cc_compile_command_wrapper_template('${inclusion_stack}', cuda=True)

        _, cxx, _ = self.build_accelerator.get_cc_commands()
        cu_command = '%s -ccbin "%s" -o ${out} -MMD -MF ${out}.d ' \
            '-Xcompiler -fPIC %s %s %s ${optimize} ${cu_warnings} ' \
            '%s ${includes} ${cppflags} ${cuflags} -c ${in}' % (
                nvcc_cmd, cxx, ' '.join(cxxflags), ' '.join(cppflags),
                ' '.join(cuflags), includes)
        self.generate_rule(
            name='cudacc',
            command=template % cu_command,
            description='CUDA LIBRARY ${in}',
            depfile='${out}.d',
            deps='gcc',
        )

        # CUDA linking might have a lot of input files exceeding maximal length of a bash command line.
        # Using response file (nvcc --options-file) can resolve this problem.
        link_args = '-o ${out} ${includes} ${cppflags} --options-file ${out}.rsp ${extra_linkflags}'
        self.generate_rule(
            name='cudalink',
            command=nvcc_cmd + ' ' + link_args,
            rspfile='${out}.rsp',
            rspfile_content='${target_linkflags} ${in}',
            description='CUDA LINK BINARY ${out}')

        self.generate_rule(
            name='cudasolink',
            command=nvcc_cmd + ' -shared ' + link_args,
            rspfile='${out}.rsp',
            rspfile_content='${target_linkflags} ${in}',
            description='CUDA LINK SHARED ${out}')

    def _generate_msvc_cuda_rules(self):
        """Generate CUDA rules for MSVC host compiler on Windows.

        NVCC on Windows delegates host code to cl.exe.  Flags that pass
        through to the host compiler via -Xcompiler must be MSVC-compatible.
        """
        cc_config = config.get_section('cc_config')
        ms_config = config.get_section('msvc_config')
        cuda_config = config.get_section('cuda_config')

        # Build MSVC-compatible host compiler flags, filtered through the
        # toolchain so that GCC-isms from cc_config get mapped or dropped.
        filtered_cppflags = self.build_toolchain.filter_cc_flags(cc_config['cppflags'])
        filtered_cxxflags = self.build_toolchain.filter_cc_flags(cc_config['cxxflags'], 'c++')
        cppflags = ms_config['cppflags'] + filtered_cppflags
        cxxflags = ms_config['cxxflags'] + filtered_cxxflags

        # NVCC's cudafe++ (which preprocesses host code before MSVC) has a
        # limited C++ STL understanding.  /EHsc and /std:c++17 pull in STL
        # internal headers (e.g. xtr1common) that trigger an assertion in
        # cudafe++ — this is an NVCC limitation, not an MSVC version issue.
        cppflags = [f for f in cppflags if not f.startswith('/EH')]
        cxxflags = [f for f in cxxflags if not f.startswith('/EH')]
        cppflags = [f for f in cppflags if not f.startswith('/std:')]
        cxxflags = [f for f in cxxflags if not f.startswith('/std:')]

        # -Xcompiler passes flags to the host compiler (cl.exe); NVCC
        # itself understands -I / -D / etc. natively.
        host_cppflags = ' '.join('-Xcompiler %s' % f for f in cppflags)
        host_cxxflags = ' '.join('-Xcompiler %s' % f for f in cxxflags)

        cuflags = cuda_config['cuflags']
        system_includes = self.build_toolchain.get_system_include_paths()
        includes = system_includes + cc_config['extra_incs'] + ['.', self.build_dir]
        # NVCC uses -I natively, same across platforms.
        # Quote paths with spaces so nvcc parses them as a single argument.
        def _quote_if_needed(p):
            return '-I"%s"' % p if ' ' in p else '-I%s' % p
        include_flags = ' '.join(_quote_if_needed(inc) for inc in includes)

        # NVCC -Xcompiler /showIncludes lets Ninja deps=msvc track headers.
        # The Python wrapper tees /showIncludes to both stderr (for Ninja) and
        # the inclusion stack file.
        py = sys.executable
        wrapper = self._msvc_tee_wrapper_py()
        template = '"%s" -B %s ${inclusion_stack} -- ' % (py, wrapper)

        _, cxx, _ = self.build_accelerator.get_cc_commands()
        cu_command = template + ('"${cmd}" -ccbin "%s" -o ${out} -c '
                                 '-Xcompiler /nologo -Xcompiler /showIncludes '
                                 '%s %s %s '
                                 '%s ${includes} %s ${cu_warnings} ${in}' % (
                                     cxx,
                                     host_cppflags, host_cxxflags,
                                     ' '.join(cuflags),
                                     include_flags, '${cppflags}'))
        self.generate_rule(
            name='cudacc',
            command=cu_command,
            description='CUDA LIBRARY ${in}',
            deps='msvc',
            restat=True,
        )

        # NVCC linking delegates to the host linker automatically.
        # Include -ccbin so nvcc can find cl.exe even without a VS dev shell.
        # Route through the link scrubber so nvcc's echoed object name
        # (e.g. "test.cu.obj") doesn't leak past Ninja's "CUDA LINK ..." line.
        link_wrapper = self._msvc_link_wrapper_py()
        link_prefix = '"%s" -B %s -- "${cmd}" -ccbin "%s" ' % (
            sys.executable, link_wrapper, cxx)
        link_args = ('-o ${out} %s ${cppflags} '
                     '--options-file ${out}.rsp ${extra_linkflags}' % include_flags)
        self.generate_rule(
            name='cudalink',
            command=link_prefix + link_args,
            rspfile='${out}.rsp',
            rspfile_content='${target_linkflags} ${in}',
            description='CUDA LINK BINARY ${out}')

        self.generate_rule(
            name='cudasolink',
            command=link_prefix + '-shared ' + link_args,
            rspfile='${out}.rsp',
            rspfile_content='${target_linkflags} ${in}',
            description='CUDA LINK SHARED ${out}')


def generate_cc_rules(ctx):
    """Rule provider: cc-family rules (registered from cc_targets)."""
    CcRuleGenerator(ctx).generate_cc_rules()


def generate_cuda_rules(ctx):
    """Rule provider: cuda rules (registered from cu_targets)."""
    CcRuleGenerator(ctx).generate_cuda_rules()
