# Copyright (c) 2020 Tencent Inc.
# All rights reserved.
#
# Author: chen3feng <chen3feng@gmail.com>
# Date:   Jane 03, 2020

"""
Code Test Coverage.
"""


import collections
import os
import re
import shlex
import shutil
import subprocess
import zipfile

from blade import config  # lgtm[py/cyclic-import]
from blade import console


def _glob_to_regex(pattern):
    r"""Translate a POSIX-globstar coverage-exclude glob into a regex.

    Mirrors blade's BUILD-file glob semantics (see load_build_files): ``**``
    matches across path separators, ``*`` / ``?`` do not. The result is meant
    for ``re.search`` (matches anywhere in the path) and treats ``/`` and ``\``
    interchangeably so it works on both gcovr's `/`-paths and the Windows
    `\`-paths in MSVC Cobertura. Used for both the gcovr ``--exclude`` filter
    and the native-MSVC Cobertura post-filter (#1369 follow-up).
    """
    sep = r'[/\\]'
    out = []
    i, n = 0, len(pattern)
    while i < n:
        c = pattern[i]
        if c == '*':
            if pattern[i:i + 2] == '**':
                i += 2
                if pattern[i:i + 1] == '/':  # `**/` -> zero or more dirs
                    out.append('(?:.*' + sep + ')?')
                    i += 1
                else:
                    out.append('.*')
            else:
                out.append('[^/\\\\]*')
                i += 1
        elif c == '?':
            out.append('[^/\\\\]')
            i += 1
        elif c == '/':
            out.append(sep)
            i += 1
        else:
            out.append(re.escape(c))
            i += 1
    return ''.join(out)


def _cobertura_rate(covered, valid):
    """Cobertura ``line-rate`` string. An empty unit is vacuously 1 (the same
    convention Microsoft.CodeCoverage.Console emits for empty packages)."""
    return str(covered / valid) if valid else '1'


class JacocoReporter:
    """
    Jacoco Coverage Report Generator
    """
    def __init__(self, build_dir, target_database, command_targets, test_jobs):
        self.__build_dir = build_dir
        self.__target_database = target_database
        self.__command_targets = command_targets
        self.__test_jobs = test_jobs
        # Collect coverage targets
        self.__coverage_targets = []
        for key in self.__command_targets:
            target = self.__target_database[key]
            if target.attr.get('jacoco_coverage'):
                self.__coverage_targets.append(target)

    def _executable(self, target):
        """Returns the executable path."""
        executable_name = target.attr.get('executable_name', target.name)
        return os.path.join(self.__build_dir, target.path, executable_name)

    # Copied from BinaryRunner
    def _runfiles_dir(self, target):
        """Returns runfiles dir."""
        return '%s.runfiles' % self._executable(target)

    @staticmethod
    def _list_classes(path):
        """Return all *.class files in a dir"""
        result = []
        for root, dirs, files in os.walk(path):
            for file in files:
                if file.endswith('.class'):
                    result.append(os.path.join(root, file))
        return result

    @staticmethod
    def _list_jar_classes(jar):
        """Return all *.class files in a jar"""
        with zipfile.ZipFile(jar) as zip:
            return [f for f in zip.namelist() if f.endswith('.class')]

    @staticmethod
    def _classes_conflict(checked_classes, classes_path, classes):
        """Check whether classes in class_path already in checked_classes and then ignore this path..
        jacoco will raise exception if it meets different classes with same name when report.
        """
        for cls in classes:
            if cls in checked_classes:
                console.warning(f'Conflict: {classes_path}/{cls} already existed in {checked_classes[cls]}')
                return True
            checked_classes[cls] = classes_path
        return False

    def _collect_execfiles(self):
        """Return all jacoco.exec files generated by jacoco agent after testing."""
        execfiles = []
        for key in self.__test_jobs:
            target = self.__target_database[key]

            execution_data = os.path.join(self._runfiles_dir(target), 'jacoco.exec')
            if not os.path.isfile(execution_data):
                continue
            execfiles.append(execution_data)
        return execfiles

    def _collect_classes(self):
        """Collect classes to be used as coverage base.
        Returns:
            class directory: class directory of target under test
        """
        checked_classes = {}  # dict[classfile, classes_dir]
        classes_dirs = set()
        for target in self.__coverage_targets:
            classes_dir = target._get_classes_dir()
            if not os.path.exists(classes_dir):
                classes_dir = target._get_target_file('jar')
                classes = self._list_jar_classes(classes_dir)
            else:
                classes = self._list_classes(classes_dir)
            if not self._classes_conflict(checked_classes, classes_dir, classes):
                classes_dirs.add(classes_dir)

        return classes_dirs

    def _collect_sources(self):
        """Collect sources to be used as coverage base.
        Returns:
            source directory: source directory of target under test
        """
        return [target._get_sources_dir() for target in self.__coverage_targets]

    @staticmethod
    def _cut_in_before_each(value, items):
        """Cut in `value` before each elements of items"""
        # See https://www.w3resource.com/python-exercises/list/python-data-type-list-exercise-47.php
        return [v for elt in items for v in (value, elt)]

    @staticmethod
    def _check_java_debug_options():
        from blade import java_targets  # pylint: disable=import-outside-toplevel
        options = java_targets.debug_info_options()
        for option in options:
            if 'line' in option:  # "-g:line" is required to generate line coverage
                return
        console.warning('"global_config.debug_info_level" is too low to generate java line coverage')

    @staticmethod
    def _common_dir(files):
        """Common dir of a group of files"""
        dirname = ''
        for file in files:
            d = os.path.dirname(file)
            if not dirname or len(d) < len(dirname):
                dirname = d
        return dirname

    def _package_source_mapping(self):
        # Merge all pacage sources mappings
        merged = collections.defaultdict(list)
        for target in self.__coverage_targets:
            mapping = target.get_java_package_source_mapping()
            for package, sources in mapping.items():
                merged[package] += sources
        return {package: self._common_dir(sources) for package, sources in merged.items()}

    def _postprocess_report(self, report_dir):
        """Do more works on generated report"""
        # Replace the package names to source file dirs in index.html for better blaming
        mapping = self._package_source_mapping()
        index_html = os.path.join(report_dir, 'index.html')
        with open(index_html) as f:
            content = f.read()
        for package, path in mapping.items():
            content = content.replace('>%s</a>' % package, '>%s</a>' % path)
        with open(index_html, 'w') as f:
            f.write(content)
        # Also generate a package_mapping file
        with open(report_dir + '.packages.csv', 'w') as f:
            f.write('package_name,source_path\r\n')
            for package, path in mapping.items():
                f.write(f'{package},{path}\r\n')

    def generate(self):
        """Run jacococli to generate coverage report"""
        if not self.__coverage_targets:
            console.debug('No jacoco supported targets')
            return

        report_dir = os.path.join(self.__build_dir, 'jacoco_coverage_report')
        console.info('Generating java coverage report `%s`' % report_dir)

        execfiles = self._collect_execfiles()
        if not execfiles:
            console.warning('jacoco exec files not found')
            return

        jacoco_home = config.get_item('java_test_config', 'jacoco_home')
        if not jacoco_home:
            console.warning('Missing jacoco home in java_test configuration. '
                            'Abort java coverage report generation.')
            return

        self._check_java_debug_options()
        if not os.path.exists(report_dir):
            os.makedirs(report_dir)

        java = 'java'
        java_home = config.get_item('java_config', 'java_home')
        if java_home:
            java = os.path.join(java_home, 'bin', 'java')
        jacococli = os.path.join(jacoco_home, 'lib', 'jacococli.jar')

        classes_dirs = self._collect_classes()
        source_dirs = self._collect_sources()

        # See https://www.jacoco.org/jacoco/trunk/doc/cli.html
        cmd = [java, '-jar', jacococli, 'report', '--quiet']
        cmd += execfiles
        cmd += self._cut_in_before_each('--classfiles', classes_dirs)
        cmd += self._cut_in_before_each('--sourcefiles', source_dirs)
        cmd += ['--html', report_dir]
        cmd += ['--csv', report_dir + '.csv']
        cmd += ['--xml', report_dir + '.xml']

        console.debug(' '.join(cmd))

        # NOTE: If call with(cmd:str, shell=True), may cause a 'command line too long' error
        # Pass cmd as a list and shell=False solves this problem
        if subprocess.call(cmd, shell=False) != 0:
            console.warning('Failed to generate java coverage report')
            return
        self._postprocess_report(report_dir)


class CcCoverageReporter:
    """Generate a C/C++ coverage report from gcov data using gcovr.

    Under ``blade test --coverage`` cc targets are compiled and linked with
    ``--coverage``, emitting ``.gcno`` (at compile) and ``.gcda`` (at run)
    next to the objects in the build dir. gcovr turns those into an HTML
    report. The reporter degrades gracefully: it is a no-op when there is no
    coverage data, and only warns (never fails the build) when gcovr is
    missing or errors.
    """

    def __init__(self, build_dir, root_dir, cc_is_clang, excludes=None):
        self.__build_dir = build_dir
        self.__root_dir = root_dir
        self.__cc_is_clang = cc_is_clang
        self.__excludes = excludes or []

    def _has_coverage_data(self):
        for _dirpath, _dirnames, filenames in os.walk(self.__build_dir):
            if any(f.endswith('.gcda') for f in filenames):
                return True
        return False

    def _gcov_executable(self):
        """The `gcov` command for the active toolchain, or None for the default.

        gcovr defaults to GNU `gcov`, which is right for GCC. Clang provides
        gcov compatibility via `llvm-cov gcov`; on Apple toolchains llvm-cov is
        reachable only through `xcrun`, not directly on PATH.
        """
        if not self.__cc_is_clang:
            return None
        if shutil.which('llvm-cov'):
            return 'llvm-cov gcov'
        if shutil.which('xcrun'):
            return 'xcrun llvm-cov gcov'
        return 'llvm-cov gcov'

    def build_gcovr_command(self, gcovr, report_dir, gcov_executable=None):
        """Build the gcovr command line (split out for testing)."""
        cmd = [
            gcovr,
            '--root', self.__root_dir,
            self.__build_dir,
            # Exclude everything under the build dir: generated sources
            # (e.g. *.pb.cc, scm.cc) and vendored deps (vcpkg installs under
            # the build dir) are not the project's own code. Without this the
            # report is diluted by uncovered library headers.
            '--exclude', re.escape(self.__build_dir) + '/',
            # gcov's counters can overflow / go negative on hot concurrent code
            # (spin loops etc.) -- a known gcov bug (gcc #68080). Warn and keep
            # going instead of aborting the whole report on one bad line.
            '--gcov-ignore-parse-errors=all',
            '--print-summary',
            # Nested HTML: navigable directory-by-directory, drilling down to
            # per-file line views (vs the flat file list of --html-details).
            '--html-nested', '-o', os.path.join(report_dir, 'index.html'),
            '--xml', os.path.join(report_dir, 'coverage.xml'),
        ]
        # User-configured coverage_config.exclude globs (translated to regex).
        # gcovr drops any source whose path matches, from both HTML and XML.
        for glob in self.__excludes:
            cmd += ['--exclude', '.*' + _glob_to_regex(glob)]
        if gcov_executable:
            cmd += ['--gcov-executable', gcov_executable]
        return cmd

    def generate(self):
        """Run gcovr to produce an HTML (+ XML) C/C++ coverage report."""
        if not self._has_coverage_data():
            console.debug('No C/C++ coverage data (.gcda) found, '
                          'skipping the C/C++ coverage report')
            return

        gcovr = shutil.which('gcovr')
        if not gcovr:
            console.warning('gcovr not found, skipping the C/C++ coverage '
                            'report (install it with `pip install gcovr`)')
            return

        report_dir = os.path.join(self.__build_dir, 'cc_coverage_report')
        if not os.path.exists(report_dir):
            os.makedirs(report_dir)
        console.info('Generating C/C++ coverage report `%s`' % report_dir)

        cmd = self.build_gcovr_command(gcovr, report_dir, self._gcov_executable())
        console.debug(' '.join(cmd))
        if subprocess.call(cmd, shell=False) != 0:
            console.warning('Failed to generate the C/C++ coverage report')


class MsvcCoverageReporter:
    """Merge native cl.exe (MSVC) per-test Cobertura reports into one.

    Unlike GCC/Clang (gcov `.gcda` -> gcovr), cl.exe has no gcov data. Under
    ``blade test --coverage`` each cc_test is run through
    ``Microsoft.CodeCoverage.Console.exe collect`` (see TestRunner.run), which
    instruments the test exe dynamically via its PDB and writes a
    ``<exe>.cobertura.xml`` next to it. This reporter merges those per-test
    files into one Cobertura report with the same tool's ``merge`` command.

    Like the other reporters it degrades gracefully: a no-op when no per-test
    Cobertura exists, and only warns (never fails) when the tool is missing or
    merge errors. See issue #1369.
    """

    def __init__(self, build_dir, collector, excludes=None):
        self.__build_dir = build_dir
        self.__collector = collector
        self.__excludes = excludes or []

    def _cobertura_files(self):
        files = []
        for dirpath, _dirnames, filenames in os.walk(self.__build_dir):
            for f in filenames:
                if f.endswith('.cobertura.xml'):
                    files.append(os.path.join(dirpath, f))
        return sorted(files)

    def generate(self):
        """Merge per-test Cobertura into one report under the build dir."""
        report_dir = os.path.join(self.__build_dir, 'cc_coverage_report')
        merged = os.path.join(report_dir, 'coverage.cobertura.xml')
        # The merge tool refuses to overwrite, and a stale merged file would be
        # re-merged into itself on the next run -- drop it first.
        if os.path.isfile(merged):
            os.remove(merged)

        files = self._cobertura_files()
        if not files:
            console.debug('No C/C++ (MSVC) coverage data (.cobertura.xml) '
                          'found, skipping the MSVC coverage report')
            return
        if not self.__collector:
            console.warning('Microsoft.CodeCoverage.Console.exe not found, '
                            'skipping the MSVC coverage report')
            return

        if not os.path.exists(report_dir):
            os.makedirs(report_dir)
        console.info('Generating C/C++ (MSVC) coverage report `%s`' % merged)
        cmd = ([self.__collector, 'merge', '-o', merged,
                '-f', 'cobertura', '--nologo'] + files)
        console.debug(' '.join(cmd))
        if subprocess.call(cmd, shell=False) != 0:
            console.warning('Failed to generate the MSVC coverage report')
        elif self.__excludes:
            self._apply_excludes(merged)

    def _apply_excludes(self, merged):
        """Drop excluded sources from the merged Cobertura and recompute totals.

        The collector's ``merge`` has no source filter, so apply
        coverage_config.exclude here: remove every ``<class>`` whose filename
        matches an exclude glob, then recompute each package's and the
        top-level line counts / line-rate so the summary stays consistent.
        """
        import xml.etree.ElementTree as ET  # pylint: disable=import-outside-toplevel
        regexes = [re.compile(_glob_to_regex(g)) for g in self.__excludes]
        try:
            tree = ET.parse(merged)
        except (ET.ParseError, OSError):
            return
        root = tree.getroot()

        def _class_lines(cls):
            covered = valid = 0
            lines = cls.find('lines')
            if lines is not None:
                for ln in lines.findall('line'):
                    valid += 1
                    if int(ln.get('hits', '0')) > 0:
                        covered += 1
            return covered, valid

        total_cov = total_val = 0
        for package in root.iter('package'):
            classes_el = package.find('classes')
            if classes_el is None:
                continue
            for cls in list(classes_el):
                fn = cls.get('filename', '')
                if any(r.search(fn) for r in regexes):
                    classes_el.remove(cls)
            pcov = pval = 0
            for cls in classes_el:
                c, v = _class_lines(cls)
                pcov += c
                pval += v
            package.set('line-rate', _cobertura_rate(pcov, pval))
            total_cov += pcov
            total_val += pval

        root.set('lines-covered', str(total_cov))
        root.set('lines-valid', str(total_val))
        root.set('line-rate', _cobertura_rate(total_cov, total_val))
        tree.write(merged, encoding='utf-8', xml_declaration=True)


class GoCoverageReporter:
    """Generate a Go coverage report from `go test` coverage profiles.

    Under ``blade test --coverage`` go_test binaries are built with `-cover`
    and run with `-test.coverprofile`, dropping a `<binary>.coverprofile` next
    to each. This merges them and renders an HTML report via `go tool cover`.
    Degrades gracefully: a no-op when go is unconfigured or no profile exists,
    and only warns (never fails the build) on error.
    """

    def __init__(self, build_dir, go, go_home):
        self.__build_dir = build_dir
        self.__go = go
        self.__go_home = go_home

    def _profiles(self):
        found = []
        for dirpath, _dirnames, filenames in os.walk(self.__build_dir):
            for name in filenames:
                if name.endswith('.coverprofile'):
                    found.append(os.path.join(dirpath, name))
        return found

    @staticmethod
    def merge_profiles(profiles, dest):
        """Merge Go coverprofiles into one (single `mode:` header + all rows)."""
        mode = 'mode: count'
        rows = []
        for profile in profiles:
            with open(profile, encoding='utf-8') as f:
                for line in f:
                    line = line.rstrip('\n')
                    if line.startswith('mode:'):
                        mode = line
                    elif line:
                        rows.append(line)
        with open(dest, 'w', encoding='utf-8') as f:
            f.write(mode + '\n')
            for row in rows:
                f.write(row + '\n')

    def generate(self):
        """Merge profiles and render `go tool cover -html`."""
        if not self.__go:
            return  # go toolchain not configured
        profiles = self._profiles()
        if not profiles:
            console.debug('No Go coverage profiles found, '
                          'skipping the Go coverage report')
            return

        report_dir = os.path.join(self.__build_dir, 'go_coverage_report')
        if not os.path.exists(report_dir):
            os.makedirs(report_dir)
        merged = os.path.join(report_dir, 'merged.coverprofile')
        self.merge_profiles(profiles, merged)
        console.info('Generating Go coverage report `%s`' % report_dir)

        env = dict(os.environ)
        if self.__go_home:
            env['GOPATH'] = os.path.abspath(self.__go_home)
        cmd = [self.__go, 'tool', 'cover', '-html=' + merged,
               '-o', os.path.join(report_dir, 'index.html')]
        console.debug(' '.join(cmd))
        if subprocess.call(cmd, shell=False, env=env) != 0:
            console.warning('Failed to generate the Go coverage report')


class PyCoverageReporter:
    """Generate a Python coverage report from coverage.py data.

    Under ``blade test --coverage`` py_test wrappers run under
    ``coverage run -p`` and write parallel-mode data files into
    <build_dir>/py_coverage_data (the runner sets COVERAGE_FILE). This
    combines them and renders an HTML report via ``coverage html``. The test
    code runs from the test zipapp, so file paths in the report carry a
    ``.zip/`` prefix. Degrades gracefully: a no-op when there is no data, and
    only warns (never fails the build) when coverage.py is unavailable.
    """

    def __init__(self, build_dir, interpreter):
        self.__build_dir = build_dir
        self.__data_dir = os.path.join(build_dir, 'py_coverage_data')
        # The interpreter the tests ran under -- it must have coverage.py.
        self.__interp = shlex.split(interpreter) if interpreter else ['python3']

    def _has_data(self):
        if not os.path.isdir(self.__data_dir):
            return False
        return any(name.startswith('.coverage')
                   for name in os.listdir(self.__data_dir))

    def _coverage(self, *args, env=None, quiet=False):
        out = subprocess.DEVNULL if quiet else None
        return subprocess.call(self.__interp + ['-m', 'coverage', *args],
                               env=env, stdout=out, stderr=out)

    def generate(self):
        """Combine per-test coverage data and render an HTML report."""
        if not self._has_data():
            console.debug('No Python coverage data found, '
                          'skipping the Python coverage report')
            return

        if self._coverage('--version', quiet=True) != 0:
            console.warning('coverage.py not available for the test interpreter, '
                            'skipping the Python coverage report (install it '
                            'with `pip install coverage`)')
            return

        report_dir = os.path.join(self.__build_dir, 'py_coverage_report')
        env = dict(os.environ)
        env['COVERAGE_FILE'] = os.path.join(self.__data_dir, '.coverage')
        if self._coverage('combine', env=env) != 0:
            console.warning('Failed to combine Python coverage data')
            return
        console.info('Generating Python coverage report `%s`' % report_dir)
        if self._coverage('html', '-d', report_dir, env=env) != 0:
            console.warning('Failed to generate the Python coverage report')
